# Generated by Django 5.2.17 on 2026-09-19 23:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # ADR-0011: accounts.0001 (OperationalUser) must be the first
        # project application migration in the whole graph. events.0001 has
        # no FK-driven dependency on it, so this ordering edge is explicit
        # rather than incidental.
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventEdition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("timezone", models.CharField(help_text="IANA timezone name.", max_length=64)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("registration_opens_at", models.DateTimeField(blank=True, null=True)),
                ("registration_closes_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REGISTRATION_OPEN", "Registration open"),
                            ("REGISTRATION_CLOSED", "Registration closed"),
                            ("EVENT_OPERATIONS", "Event operations"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("default_language", models.CharField(default="en", max_length=8)),
                (
                    "supported_languages",
                    models.JSONField(
                        default=list,
                        help_text="BCP-47 codes; app-validated against ('en', 'fr', 'ar').",
                    ),
                ),
                ("settings_version", models.PositiveIntegerField(default=1)),
                ("next_registration_sequence", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "events_event_edition",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gte", models.F("starts_at"))),
                        name="events_edition_ends_at_after_starts_at",
                    )
                ],
            },
        ),
    ]
