# Generated by Django 5.2.17 on 2026-09-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_seed_current_event_edition"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventedition",
            name="passport_identity_page_upload_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
