# Generated by Django 5.2.17 on 2026-09-22 21:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_eventedition_passport_identity_page_upload_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("name_fr", models.CharField(blank=True, default="", max_length=200)),
                ("name_ar", models.CharField(blank=True, default="", max_length=200)),
                ("code", models.CharField(max_length=32)),
                ("address_summary", models.CharField(blank=True, default="", max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venues",
                        to="events.eventedition",
                    ),
                ),
            ],
            options={
                "db_table": "events_venue",
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("name_fr", models.CharField(blank=True, default="", max_length=200)),
                ("name_ar", models.CharField(blank=True, default="", max_length=200)),
                ("code", models.CharField(max_length=32)),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("RESTRICTED", "Restricted"),
                            ("HIGH_SECURITY", "High security"),
                        ],
                        default="STANDARD",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="events.zone",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zones",
                        to="events.venue",
                    ),
                ),
            ],
            options={
                "db_table": "events_zone",
            },
        ),
        migrations.CreateModel(
            name="Gate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("name_fr", models.CharField(blank=True, default="", max_length=200)),
                ("name_ar", models.CharField(blank=True, default="", max_length=200)),
                ("code", models.CharField(max_length=32)),
                ("supports_entry", models.BooleanField(default=True)),
                ("supports_exit", models.BooleanField(default=False)),
                (
                    "offline_policy",
                    models.CharField(
                        choices=[("NOT_PERMITTED", "Not permitted")],
                        default="NOT_PERMITTED",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gates",
                        to="events.venue",
                    ),
                ),
                (
                    "default_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.zone",
                    ),
                ),
            ],
            options={
                "db_table": "events_gate",
            },
        ),
        migrations.AddConstraint(
            model_name="venue",
            constraint=models.UniqueConstraint(
                fields=("event_edition", "code"), name="events_venue_code_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="zone",
            constraint=models.UniqueConstraint(
                fields=("venue", "code"), name="events_zone_code_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="zone",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="events_zone_no_self_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="gate",
            constraint=models.UniqueConstraint(
                fields=("venue", "code"), name="events_gate_code_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="gate",
            constraint=models.CheckConstraint(
                condition=models.Q(("offline_policy", "NOT_PERMITTED")),
                name="events_gate_offline_not_permitted",
            ),
        ),
    ]
