# Generated by Django 5.2.17 on 2026-09-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_venue_zone_gate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventedition",
            options={
                "permissions": [
                    (
                        "manage_registration_channels",
                        "Can open, restrict or close registration channels",
                    )
                ]
            },
        ),
        migrations.AddField(
            model_name="eventedition",
            name="public_registration_mode",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("INVITATION_ONLY", "Invitation only"),
                    ("CLOSED", "Closed"),
                ],
                default="OPEN",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="eventedition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("registration_opens_at__isnull", True),
                    ("registration_closes_at__isnull", True),
                    ("registration_closes_at__gt", models.F("registration_opens_at")),
                    _connector="OR",
                ),
                name="events_edition_registration_window_order",
            ),
        ),
    ]
