# Generated by Django 5.2.17 on 2026-09-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_registration_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventedition",
            name="minimum_participant_age",
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AddField(
            model_name="eventedition",
            name="name_ar",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="eventedition",
            name="name_fr",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
