"""Stable audit action-code constants for Phase 2 Prompt 2 (Schema §15.1).

Phase 1 action codes remained ad-hoc string literals at each call site
(e.g. `"REGISTRATION_DRAFT_CREATED"`); this module introduces a stable
catalogue for Prompt 2's new invitation/delegation/on-behalf actions only,
without touching or renaming any existing Phase 1 literal (out of this
prompt's bounded scope). A later prompt MAY migrate the Phase 1 literals
into a catalogue like this one.
"""

from __future__ import annotations

CAMPAIGN_CREATED = "INV_CAMPAIGN_CREATED"
CAMPAIGN_STATUS_CHANGED = "INV_CAMPAIGN_STATUS_CHANGED"

LINK_CREATED = "INV_LINK_CREATED"
LINK_ROTATED = "INV_LINK_ROTATED"
LINK_REVOKED = "INV_LINK_REVOKED"

INVITATION_USE_RECORDED = "INV_USE_RECORDED"
INVITATION_LINK_REJECTED = "INV_LINK_REJECTED"

DELEGATION_BATCH_UPLOADED = "INV_DELEGATION_BATCH_UPLOADED"
DELEGATION_BATCH_UPLOAD_REJECTED = "INV_DELEGATION_BATCH_UPLOAD_REJECTED"
DELEGATION_BATCH_DRY_RUN = "INV_DELEGATION_BATCH_DRY_RUN"
DELEGATION_BATCH_APPLIED = "INV_DELEGATION_BATCH_APPLIED"

ON_BEHALF_DRAFT_CREATED = "INV_ON_BEHALF_DRAFT_CREATED"
ON_BEHALF_CLAIM_SUCCEEDED = "INV_ON_BEHALF_CLAIM_SUCCEEDED"
ON_BEHALF_CLAIM_FAILED = "INV_ON_BEHALF_CLAIM_FAILED"

# Shared by BOTH claim-creation paths (a direct on-behalf draft and an
# applied delegation row) -- one `OnBehalfClaim` shape, one audit code,
# regardless of how the underlying Registration was created. Distinct
# from `ON_BEHALF_DRAFT_CREATED` (the Registration itself) so the two
# facts are never conflated into one audit event.
CLAIM_ISSUED = "INV_CLAIM_ISSUED"

ORGANIZATION_WORKSPACE_DETAIL_VIEWED = "INV_ORG_WORKSPACE_DETAIL_VIEWED"
ORGANIZATION_SCOPE_DENIED = "INV_ORGANIZATION_SCOPE_DENIED"

# Delegated-claim delivery (Phase 2 Prompt 2 V2 correction pass "make
# delegated-claim delivery durable and recoverable") -- never carries the
# raw claim token or the candidate email; only the fact and outcome of a
# delivery attempt.
DELEGATION_CLAIM_DELIVERY_QUEUED = "INV_DELEGATION_CLAIM_DELIVERY_QUEUED"
DELEGATION_CLAIM_DELIVERY_SENT = "INV_DELEGATION_CLAIM_DELIVERY_SENT"
DELEGATION_CLAIM_DELIVERY_FAILED = "INV_DELEGATION_CLAIM_DELIVERY_FAILED"

# ---------------------------------------------------------------------------
# Phase 2 Prompt 3: operations review, additional-information requests,
# duplicate-candidate review, and decision history.
# ---------------------------------------------------------------------------

REVIEW_CASE_OPENED = "REV_CASE_OPENED"
REVIEW_CASE_STARTED = "REV_CASE_STARTED"
REVIEW_CASE_STATUS_CHANGED = "REV_CASE_STATUS_CHANGED"
REVIEW_CASE_COMPLETED = "REV_CASE_COMPLETED"
REVIEW_CASE_CANCELLED = "REV_CASE_CANCELLED"
REVIEW_ASSIGNMENT_RECORDED = "REV_ASSIGNMENT_RECORDED"
REVIEW_CHECKLIST_RESULT_RECORDED = "REV_CHECKLIST_RESULT_RECORDED"
REVIEW_INTERNAL_NOTE_ADDED = "REV_INTERNAL_NOTE_ADDED"
REVIEW_INFORMATION_REQUEST_DRAFTED = "REV_INFORMATION_REQUEST_DRAFTED"
REVIEW_INFORMATION_REQUEST_SENT = "REV_INFORMATION_REQUEST_SENT"
REVIEW_INFORMATION_REQUEST_CANCELLED = "REV_INFORMATION_REQUEST_CANCELLED"
REVIEW_INFORMATION_REQUEST_CLOSED = "REV_INFORMATION_REQUEST_CLOSED"
REVIEW_INFORMATION_RESPONSE_DRAFT_SAVED = "REV_INFORMATION_RESPONSE_DRAFT_SAVED"
REVIEW_INFORMATION_RESPONSE_SUBMITTED = "REV_INFORMATION_RESPONSE_SUBMITTED"
REVIEW_DUPLICATE_RESOLVED = "REV_DUPLICATE_RESOLVED"
REVIEW_DECISION_RECORDED = "REV_DECISION_RECORDED"
REVIEW_APPROVAL_BLOCKED_PENDING_ASSIGNMENTS = "REV_APPROVAL_BLOCKED_PENDING_ASSIGNMENTS"
# Owner decision IDV-Q1: an approval refused for want of a current, valid,
# verified identity (reason code = the clearance code, never identity data).
REVIEW_APPROVAL_BLOCKED_IDENTITY = "REV_APPROVAL_BLOCKED_IDENTITY"
REVIEW_REGISTRATION_REOPENED = "REV_REGISTRATION_REOPENED"
REVIEW_PARTICIPANT_WITHDRAWAL = "REV_PARTICIPANT_WITHDRAWAL"
REVIEW_OPERATIONAL_CANCELLATION = "REV_OPERATIONAL_CANCELLATION"
# Protected-document view/download audit reuses the EXISTING
# `apps.documents.views.document_stream` evidence path (its own
# "DOCUMENT_STREAMED" audit event, already scoped by
# `registrations.view_registration`) -- no separate reviews-specific code,
# since the same document may be viewed by a non-review operational
# workflow too and must be audited identically either way.

# ---------------------------------------------------------------------------
# Phase 2 Prompt 4: accreditation assignments and temporary external-
# security operational accounts.
# ---------------------------------------------------------------------------

PARTICIPANT_ROLE_ASSIGNED = "ACC_PARTICIPANT_ROLE_ASSIGNED"
PARTICIPANT_ROLE_CHANGED = "ACC_PARTICIPANT_ROLE_CHANGED"
PARTICIPANT_ROLE_REVOKED = "ACC_PARTICIPANT_ROLE_REVOKED"
BADGE_TYPE_ASSIGNED = "ACC_BADGE_TYPE_ASSIGNED"
BADGE_TYPE_CHANGED = "ACC_BADGE_TYPE_CHANGED"
BADGE_TYPE_REVOKED = "ACC_BADGE_TYPE_REVOKED"
ACCESS_PROFILE_ASSIGNED = "ACC_ACCESS_PROFILE_ASSIGNED"
ACCESS_PROFILE_CHANGED = "ACC_ACCESS_PROFILE_CHANGED"
ACCESS_PROFILE_REVOKED = "ACC_ACCESS_PROFILE_REVOKED"
ACCESS_RULE_ASSIGNED = "ACC_ACCESS_RULE_ASSIGNED"
ACCESS_RULE_CHANGED = "ACC_ACCESS_RULE_CHANGED"
ACCESS_RULE_REVOKED = "ACC_ACCESS_RULE_REVOKED"
ASSIGNMENT_EXPIRED = "ACC_ASSIGNMENT_EXPIRED"
BULK_ASSIGNMENT_PREVIEWED = "ACC_BULK_ASSIGNMENT_PREVIEWED"
BULK_ASSIGNMENT_EXECUTED = "ACC_BULK_ASSIGNMENT_EXECUTED"
ELIGIBILITY_EVALUATED = "ACC_ELIGIBILITY_EVALUATED"

EXTERNAL_SECURITY_ACCOUNT_CREATED = "ACC_EXTERNAL_SECURITY_ACCOUNT_CREATED"
EXTERNAL_SECURITY_ACCOUNT_SCOPE_CHANGED = "ACC_EXTERNAL_SECURITY_ACCOUNT_SCOPE_CHANGED"
EXTERNAL_SECURITY_ACCOUNT_ACTIVATED = "ACC_EXTERNAL_SECURITY_ACCOUNT_ACTIVATED"
EXTERNAL_SECURITY_ACCOUNT_DEACTIVATED = "ACC_EXTERNAL_SECURITY_ACCOUNT_DEACTIVATED"
EXTERNAL_SECURITY_ACCOUNT_EXPIRED_USE_DENIED = "ACC_EXTERNAL_SECURITY_ACCOUNT_EXPIRED_USE_DENIED"

# P4-4 (AF-AUTH-03): operational sign-in outcomes. The target is a keyed
# fingerprint of the typed email; never the address or the password.
OPERATIONAL_SIGN_IN_SUCCEEDED = "ACC_OPERATIONAL_SIGN_IN_SUCCEEDED"
OPERATIONAL_SIGN_IN_FAILED = "ACC_OPERATIONAL_SIGN_IN_FAILED"
OPERATIONAL_SIGN_IN_THROTTLED = "ACC_OPERATIONAL_SIGN_IN_THROTTLED"

# ---------------------------------------------------------------------------
# Phase 2 Prompt 5: controlled exports, privacy foundations.
# ---------------------------------------------------------------------------

EXPORT_REQUEST_READY = "EXP_REQUEST_READY"
EXPORT_RETRIEVED = "EXP_RETRIEVED"
EXPORT_RETRIEVAL_DENIED = "EXP_RETRIEVAL_DENIED"

PRIVACY_REQUEST_RECEIVED = "PRV_REQUEST_RECEIVED"
PRIVACY_REQUEST_STATUS_CHANGED = "PRV_REQUEST_STATUS_CHANGED"
LEGAL_HOLD_PLACED = "PRV_LEGAL_HOLD_PLACED"
LEGAL_HOLD_RELEASED = "PRV_LEGAL_HOLD_RELEASED"

# ---------------------------------------------------------------------------
# Phase 3 Prompt 2: Digital Entry Pass credentials and verification keys.
# ---------------------------------------------------------------------------

CREDENTIAL_GENERATED = "BDG_PASS_GENERATED"
CREDENTIAL_ACTIVATED = "BDG_PASS_ACTIVATED"
CREDENTIAL_SUSPENDED = "BDG_PASS_SUSPENDED"
CREDENTIAL_RESUMED = "BDG_PASS_RESUMED"
CREDENTIAL_REVOKED = "BDG_PASS_REVOKED"
CREDENTIAL_REPLACED = "BDG_PASS_REPLACED"
CREDENTIAL_EXPIRY_PERSISTED = "BDG_PASS_EXPIRY_PERSISTED"
CREDENTIAL_LIFECYCLE_REPLAYED = "BDG_PASS_LIFECYCLE_REPLAYED"
CREDENTIAL_GENERATION_BLOCKED = "BDG_PASS_GENERATION_BLOCKED"

FALLBACK_REFERENCE_LOOKUP = "BDG_PASS_FALLBACK_REFERENCE_LOOKUP"

VERIFICATION_KEY_PUBLISHED = "BDG_VERIFICATION_KEY_PUBLISHED"
VERIFICATION_KEY_PROMOTED = "BDG_VERIFICATION_KEY_PROMOTED"
VERIFICATION_KEY_RETIRED = "BDG_VERIFICATION_KEY_RETIRED"
VERIFICATION_KEY_REVOKED = "BDG_VERIFICATION_KEY_REVOKED"

# ---------------------------------------------------------------------------
# Phase 3 Prompt 3: generic physical badge stock (ADR-0020).
# ---------------------------------------------------------------------------

STOCK_LOCATION_CREATED = "BDG_STOCK_LOCATION_CREATED"
PRINT_BATCH_CREATED = "BDG_PRINT_BATCH_CREATED"
PRINT_BATCH_STATUS_CHANGED = "BDG_PRINT_BATCH_STATUS_CHANGED"
PRINT_BATCH_RECEIVED = "BDG_PRINT_BATCH_RECEIVED"
STOCK_TRANSFERRED = "BDG_STOCK_TRANSFERRED"
STOCK_ISSUED = "BDG_STOCK_ISSUED"
STOCK_ISSUANCE_REPLACED = "BDG_STOCK_ISSUANCE_REPLACED"
STOCK_RETURNED = "BDG_STOCK_RETURNED"
STOCK_ISSUANCE_LOST = "BDG_STOCK_ISSUANCE_LOST"
STOCK_ISSUANCE_VOIDED = "BDG_STOCK_ISSUANCE_VOIDED"
STOCK_ISSUANCE_BLOCKED = "BDG_STOCK_ISSUANCE_BLOCKED"
STOCK_ADJUSTED = "BDG_STOCK_ADJUSTED"
STOCK_RECONCILIATION_RECORDED = "BDG_STOCK_RECONCILIATION_RECORDED"
STOCK_ALLOCATED = "BDG_STOCK_ALLOCATED"
STOCK_ALLOCATION_RELEASED = "BDG_STOCK_ALLOCATION_RELEASED"
STOCK_COMMAND_SCOPE_REJECTED = "BDG_STOCK_COMMAND_SCOPE_REJECTED"

# ---------------------------------------------------------------------------
# Phase 3 Prompt 4: venue structure, entry devices, checkpoint sessions,
# online verification, restrictions, overrides, Entry Events (ADR-0021).
# None of these ever carries a QR token, a NIN/passport value, a search
# string, a device secret, or an activation code.
# ---------------------------------------------------------------------------

VENUE_CREATED = "EVT_VENUE_CREATED"
ZONE_CREATED = "EVT_ZONE_CREATED"
GATE_CREATED = "EVT_GATE_CREATED"

# UX-4 (M24, D-12): registration channel control and enforcement. The
# summaries carry the mode, the window and the operator's bounded reason;
# never a participant identifier.
REGISTRATION_CHANNEL_CHANGED = "EVT_REGISTRATION_CHANNEL_CHANGED"
REGISTRATION_CHANNEL_CHANGE_DENIED = "EVT_REGISTRATION_CHANNEL_CHANGE_DENIED"
REGISTRATION_CHANNEL_REFUSED = "EVT_REGISTRATION_CHANNEL_REFUSED"

# UX-3 (M21, S-18): accommodation data. Never carries a category or the note.
ACCOMMODATION_REQUEST_VIEWED = "REG_ACCOMMODATION_REQUEST_VIEWED"
ACCOMMODATION_CONSENT_WITHDRAWN = "REG_ACCOMMODATION_CONSENT_WITHDRAWN"

# Owner correction (2026-10-04): a participant registers again after withdrawing.
# Recorded on the WITHDRAWN registration, whose context is released; the summary
# carries the new registration's reference and its origin, never personal data.
REGISTRATION_RESTARTED_AFTER_WITHDRAWAL = "REG_RESTARTED_AFTER_WITHDRAWAL"

EXTERNAL_SECURITY_ACCOUNT_EXPIRED = "ACC_EXTERNAL_SECURITY_ACCOUNT_EXPIRED"

DEVICE_REGISTERED = "ENT_DEVICE_REGISTERED"
DEVICE_ACTIVATION_CODE_ISSUED = "ENT_DEVICE_ACTIVATION_CODE_ISSUED"
DEVICE_ENROLLED = "ENT_DEVICE_ENROLLED"
DEVICE_ENROLLMENT_REJECTED = "ENT_DEVICE_ENROLLMENT_REJECTED"
DEVICE_SCOPE_CHANGED = "ENT_DEVICE_SCOPE_CHANGED"
DEVICE_SUSPENDED = "ENT_DEVICE_SUSPENDED"
DEVICE_RESUMED = "ENT_DEVICE_RESUMED"
DEVICE_REVOKED = "ENT_DEVICE_REVOKED"
DEVICE_EXPIRED = "ENT_DEVICE_EXPIRED"
DEVICE_AUTHENTICATION_REJECTED = "ENT_DEVICE_AUTHENTICATION_REJECTED"

DEVICE_SESSION_STARTED = "ENT_DEVICE_SESSION_STARTED"
DEVICE_SESSION_ENDED = "ENT_DEVICE_SESSION_ENDED"
DEVICE_SESSION_REJECTED = "ENT_DEVICE_SESSION_REJECTED"
OPERATOR_SESSION_STARTED = "ENT_OPERATOR_SESSION_STARTED"
OPERATOR_SESSION_ENDED = "ENT_OPERATOR_SESSION_ENDED"

ENTRY_VERIFICATION_PERFORMED = "ENT_VERIFICATION_PERFORMED"
ENTRY_IDENTITY_LOOKUP = "ENT_IDENTITY_LOOKUP"
ENTRY_REFERENCE_LOOKUP = "ENT_REFERENCE_LOOKUP"
ENTRY_MANUAL_SEARCH = "ENT_MANUAL_SEARCH"
ENTRY_LOOKUP_DENIED = "ENT_LOOKUP_DENIED"
ENTRY_PHOTO_VIEWED = "ENT_PHOTO_VIEWED"
ENTRY_EVENT_RECORDED = "ENT_EVENT_RECORDED"
ENTRY_DECISION_REJECTED = "ENT_DECISION_REJECTED"
ENTRY_OVERRIDE_RECORDED = "ENT_OVERRIDE_RECORDED"
ENTRY_OVERRIDE_REJECTED = "ENT_OVERRIDE_REJECTED"
# Phase 3 Prompt 5 (ADR-0022): abuse limiting and anomaly signals. Counts
# and checkpoint coordinates only -- never a token, value, or search text.
ENTRY_LOOKUP_THROTTLED = "ENT_LOOKUP_THROTTLED"
ENTRY_ANOMALY_SIGNAL = "ENT_ANOMALY_SIGNAL"

SECURITY_RESTRICTION_CREATED = "ENT_SECURITY_RESTRICTION_CREATED"
SECURITY_RESTRICTION_REVOKED = "ENT_SECURITY_RESTRICTION_REVOKED"

# ---------------------------------------------------------------------------
# Phase 4 Prompt 2: enrolled-device offline PREPARATION (ADR-0023). None of
# these ever carries package content, a data key, a device private key, a
# nonce, a grant token, a participant value, or an operation body --
# versions, hashes, counts and reason codes only.
# ---------------------------------------------------------------------------

OFFLINE_EVENT_ENABLED = "ENT_OFFLINE_EVENT_ENABLED"
OFFLINE_EVENT_DISABLED = "ENT_OFFLINE_EVENT_DISABLED"
DEVICE_OFFLINE_PROVISIONED = "ENT_DEVICE_OFFLINE_PROVISIONED"
DEVICE_OFFLINE_PROVISION_REJECTED = "ENT_DEVICE_OFFLINE_PROVISION_REJECTED"
DEVICE_OFFLINE_SELF_TEST_PASSED = "ENT_DEVICE_OFFLINE_SELF_TEST_PASSED"
DEVICE_OFFLINE_SELF_TEST_FAILED = "ENT_DEVICE_OFFLINE_SELF_TEST_FAILED"
DEVICE_OFFLINE_READY = "ENT_DEVICE_OFFLINE_READY"
DEVICE_OFFLINE_READINESS_WITHDRAWN = "ENT_DEVICE_OFFLINE_READINESS_WITHDRAWN"
DEVICE_OFFLINE_BLOCKED = "ENT_DEVICE_OFFLINE_BLOCKED"
OFFLINE_PACKAGE_BUILT = "ENT_OFFLINE_PACKAGE_BUILT"
OFFLINE_PACKAGE_BUILD_REQUESTED = "ENT_OFFLINE_PACKAGE_BUILD_REQUESTED"
OFFLINE_PACKAGE_BUILD_ENDED = "ENT_OFFLINE_PACKAGE_BUILD_ENDED"
OFFLINE_PACKAGE_DOWNLOADED = "ENT_OFFLINE_PACKAGE_DOWNLOADED"
OFFLINE_PACKAGE_DOWNLOAD_DENIED = "ENT_OFFLINE_PACKAGE_DOWNLOAD_DENIED"
OFFLINE_PACKAGE_REVOKED = "ENT_OFFLINE_PACKAGE_REVOKED"
OFFLINE_PACKAGE_CIPHERTEXT_PURGED = "ENT_OFFLINE_PACKAGE_CIPHERTEXT_PURGED"
OFFLINE_DELTA_ISSUED = "ENT_OFFLINE_DELTA_ISSUED"
OFFLINE_GRANT_ISSUED = "ENT_OFFLINE_GRANT_ISSUED"
OFFLINE_GRANT_REVOKED = "ENT_OFFLINE_GRANT_REVOKED"
OFFLINE_REQUEST_REJECTED = "ENT_OFFLINE_REQUEST_REJECTED"
DEVICE_EMERGENCY_WIPE_ORDERED = "ENT_DEVICE_EMERGENCY_WIPE_ORDERED"
DEVICE_EMERGENCY_WIPE_REFUSED = "ENT_DEVICE_EMERGENCY_WIPE_REFUSED"
DEVICE_EVIDENCE_REPORTED = "ENT_DEVICE_EVIDENCE_REPORTED"

# ---------------------------------------------------------------------------
# Phase 4 Prompt 3: offline verification, synchronization and
# reconciliation (ADR-0024). Codes, counts, sequence numbers, public ids and
# checkpoint coordinates only -- never a token, a participant value, an
# operation body, an override or reconciliation note, or a signature.
# ---------------------------------------------------------------------------

OFFLINE_SYNC_BATCH_RECEIVED = "ENT_OFFLINE_SYNC_BATCH_RECEIVED"
OFFLINE_SYNC_REFUSED = "ENT_OFFLINE_SYNC_REFUSED"
OFFLINE_EVENT_APPLIED = "ENT_OFFLINE_EVENT_APPLIED"
OFFLINE_CONFLICT = "ENT_OFFLINE_CONFLICT"
OFFLINE_SECURITY_CONFLICT = "ENT_OFFLINE_SECURITY_CONFLICT"
OFFLINE_OPERATION_REJECTED = "ENT_OFFLINE_OPERATION_REJECTED"
OFFLINE_OPERATION_QUARANTINED = "ENT_OFFLINE_OPERATION_QUARANTINED"
OFFLINE_VERIFICATION_ATTEMPT = "ENT_OFFLINE_VERIFICATION_ATTEMPT"
RECONCILIATION_CASE_OPENED = "ENT_RECONCILIATION_CASE_OPENED"
RECONCILIATION_NOTE_ADDED = "ENT_RECONCILIATION_NOTE_ADDED"
RECONCILIATION_CASE_CLOSED = "ENT_RECONCILIATION_CASE_CLOSED"
RECONCILIATION_ACCESS_DENIED = "ENT_RECONCILIATION_ACCESS_DENIED"

# ---------------------------------------------------------------------------
# IDV-1 to IDV-4: post-submission identity verification (amendment A-13,
# ADR-0026). Codes, statuses, reason codes, counts and public ids only --
# never a NIN, a passport number, a name, a birth date, a provider response,
# a token or an internal note.
# ---------------------------------------------------------------------------

IDENTITY_VERIFICATION_STARTED = "IDV_VERIFICATION_STARTED"
IDENTITY_PROVIDER_RESULT_APPLIED = "IDV_PROVIDER_RESULT_APPLIED"
IDENTITY_PROVIDER_RESULT_DISCARDED = "IDV_PROVIDER_RESULT_DISCARDED"
IDENTITY_PROVIDER_RETRY_SCHEDULED = "IDV_PROVIDER_RETRY_SCHEDULED"
IDENTITY_VERIFIED_MANUALLY = "IDV_VERIFIED_MANUALLY"
IDENTITY_VERIFIED_BY_EXCEPTION = "IDV_VERIFIED_BY_EXCEPTION"
IDENTITY_RETURNED_FOR_CORRECTION = "IDV_RETURNED_FOR_CORRECTION"
IDENTITY_NIN_CORRECTED = "IDV_NIN_CORRECTED"
IDENTITY_RECHECK_REQUESTED = "IDV_RECHECK_REQUESTED"
IDENTITY_REJECTED = "IDV_REJECTED"
IDENTITY_PARTICIPANT_RESUBMITTED = "IDV_PARTICIPANT_RESUBMITTED"
IDENTITY_ACTION_REFUSED = "IDV_ACTION_REFUSED"
IDENTITY_CASE_VIEWED = "IDV_CASE_VIEWED"
IDENTITY_EVIDENCE_VIEWED = "IDV_EVIDENCE_VIEWED"
# IDV-C1 (R-IDV-01, -02, -04, -05, -06).
IDENTITY_LINKED_CASE_UPDATED = "IDV_LINKED_CASE_UPDATED"
IDENTITY_OFFICIAL_NAME_APPLIED = "IDV_OFFICIAL_NAME_APPLIED"
IDENTITY_PROVIDER_ATTEMPTS_EXHAUSTED = "IDV_PROVIDER_ATTEMPTS_EXHAUSTED"
IDENTITY_CLOSED_WITH_REGISTRATION = "IDV_CLOSED_WITH_REGISTRATION"
IDENTITY_QUEUE_SEARCHED = "IDV_QUEUE_SEARCHED"
# Owner decisions IDV-Q2 and IDV-Q3 (2026-10-02).
IDENTITY_REGISTRATION_RESTARTED = "IDV_REGISTRATION_RESTARTED"
IDENTITY_NIN_EXEMPTION_GRANTED = "IDV_NIN_EXEMPTION_GRANTED"
IDENTITY_NIN_EXEMPTION_REVOKED = "IDV_NIN_EXEMPTION_REVOKED"
IDENTITY_NIN_EXEMPTION_DOCUMENT_DECLARED = "IDV_NIN_EXEMPTION_DOCUMENT_DECLARED"
IDENTITY_NIN_EXEMPTION_USED = "IDV_NIN_EXEMPTION_USED"

# Staging UAT provisioning (`manage.py provision_staging_uat`, staging only).
# Codes, ids and counts only; never an email address or a password.
STAGING_UAT_PROVISIONED = "CORE_STAGING_UAT_PROVISIONED"
STAGING_UAT_DATA_PROVISIONED = "CORE_STAGING_UAT_DATA_PROVISIONED"
STAGING_UAT_ACCOUNT_CREATED = "ACC_STAGING_UAT_ACCOUNT_CREATED"
STAGING_UAT_MEMBERSHIP_GRANTED = "ACC_STAGING_UAT_MEMBERSHIP_GRANTED"
STAGING_UAT_RETIRED = "CORE_STAGING_UAT_RETIRED"
