# Generated by Django 5.2.17 on 2026-09-19 23:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0001_initial"),
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentPurpose",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("name_fr", models.CharField(blank=True, default="", max_length=200)),
                ("name_ar", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "privacy_consent_purpose",
            },
        ),
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PRIVACY_NOTICE", "Privacy notice"),
                            ("TERMS", "Terms"),
                            ("OTHER", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
            ],
            options={
                "db_table": "privacy_legal_document",
            },
        ),
        migrations.CreateModel(
            name="LegalDocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language", models.CharField(max_length=8)),
                ("version_label", models.CharField(max_length=32)),
                ("content", models.TextField(blank=True, default="")),
                ("published_url", models.CharField(blank=True, default="", max_length=500)),
                ("content_hash", models.CharField(max_length=64)),
                ("effective_from", models.DateTimeField()),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "legal_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="privacy.legaldocument",
                    ),
                ),
            ],
            options={
                "db_table": "privacy_legal_document_version",
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("GRANTED", "Granted"), ("WITHDRAWN", "Withdrawn")], max_length=16
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("PUBLIC_WEB", "Public web"),
                            ("ASSISTED_REGISTRATION", "Assisted registration"),
                            ("MIGRATION", "Migration"),
                        ],
                        max_length=24,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consents",
                        to="people.person",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="privacy.consentpurpose",
                    ),
                ),
                (
                    "legal_document_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="privacy.legaldocumentversion",
                    ),
                ),
            ],
            options={
                "db_table": "privacy_consent_record",
            },
        ),
        migrations.CreateModel(
            name="AcceptanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("ACCEPTED", "Accepted"), ("ACKNOWLEDGED", "Acknowledged")],
                        max_length=16,
                    ),
                ),
                ("accepted_at", models.DateTimeField()),
                ("language", models.CharField(max_length=8)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("PUBLIC_WEB", "Public web"),
                            ("ASSISTED_REGISTRATION", "Assisted registration"),
                            ("MIGRATION", "Migration"),
                        ],
                        max_length=24,
                    ),
                ),
                ("session_reference", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="people.person",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="registrations.registration",
                    ),
                ),
                (
                    "legal_document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="privacy.legaldocumentversion",
                    ),
                ),
            ],
            options={
                "db_table": "privacy_acceptance_record",
            },
        ),
        migrations.AddConstraint(
            model_name="legaldocumentversion",
            constraint=models.UniqueConstraint(
                fields=("legal_document", "language", "version_label"),
                name="prv_docversion_doc_lang_label_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["person", "purpose", "occurred_at"], name="prv_consent_person_purpose_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="acceptancerecord",
            index=models.Index(
                fields=["person", "legal_document_version"], name="prv_acceptance_person_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="acceptancerecord",
            index=models.Index(fields=["registration"], name="prv_acceptance_reg_idx"),
        ),
    ]
