# Generated by Django 5.2.17 on 2026-09-20 23:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("events", "0003_eventedition_passport_identity_page_upload_enabled"),
        ("organizations", "0003_professionalaffiliation_biography_and_more"),
        ("registrations", "0004_registrationsubmission_reg_submission_one_initial_uq"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DelegationBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("VALIDATED", "Validated"),
                            ("APPLYING", "Applying"),
                            ("APPLIED", "Applied"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADED",
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("valid_row_count", models.PositiveIntegerField(default=0)),
                ("applied_row_count", models.PositiveIntegerField(default=0)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegation_batches",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegation_batches",
                        to="organizations.organization",
                    ),
                ),
                (
                    "stored_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.storedobject",
                    ),
                ),
            ],
            options={
                "db_table": "invitations_delegation_batch",
            },
        ),
        migrations.CreateModel(
            name="DelegationRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.PositiveIntegerField()),
                (
                    "candidate_email_encrypted",
                    apps.core.fields.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "candidate_email_hash",
                    apps.core.fields.BlindIndexField(blank=True, default="", max_length=64),
                ),
                (
                    "candidate_email_hash_key_version",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VALID", "Valid"),
                            ("INVALID", "Invalid"),
                            ("APPLIED", "Applied"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("error_codes", models.JSONField(blank=True, default=list)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="invitations.delegationbatch",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "db_table": "invitations_delegation_row",
            },
        ),
        migrations.CreateModel(
            name="InvitationCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("public_reference", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("EXPIRED", "Expired"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("language", models.CharField(default="en", max_length=8)),
                (
                    "fallback_mode",
                    models.CharField(
                        choices=[
                            ("DENY", "Deny"),
                            ("OFFER_OPEN_REGISTRATION", "Offer open registration"),
                        ],
                        default="OFFER_OPEN_REGISTRATION",
                        max_length=32,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitation_campaigns",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitation_campaigns",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "invitations_campaign",
            },
        ),
        migrations.CreateModel(
            name="InvitationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ROTATED", "Rotated"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="invitations.invitationcampaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rotated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rotated_to",
                        to="invitations.invitationlink",
                    ),
                ),
            ],
            options={
                "db_table": "invitations_link",
            },
        ),
        migrations.CreateModel(
            name="InvitationUse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "use_kind",
                    models.CharField(
                        choices=[("DRAFT_CREATED", "Draft created"), ("SUBMITTED", "Submitted")],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("operation_id", models.CharField(max_length=100, unique=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uses",
                        to="invitations.invitationcampaign",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uses",
                        to="invitations.invitationlink",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitation_uses",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "db_table": "invitations_use",
            },
        ),
        migrations.CreateModel(
            name="OnBehalfClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("claim_token_hash", models.CharField(max_length=64, unique=True)),
                ("intended_email_encrypted", apps.core.fields.EncryptedTextField()),
                ("intended_email_hash", apps.core.fields.BlindIndexField(max_length=64)),
                ("intended_email_hash_key_version", models.SmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CLAIMED", "Claimed"),
                            ("EXPIRED", "Expired"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="on_behalf_claim",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "db_table": "invitations_on_behalf_claim",
            },
        ),
        migrations.AddIndex(
            model_name="delegationbatch",
            index=models.Index(fields=["organization", "created_at"], name="inv_delbatch_org_idx"),
        ),
        migrations.AddIndex(
            model_name="delegationrow",
            index=models.Index(fields=["batch", "status"], name="inv_delrow_batch_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="delegationrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_number"), name="inv_delrow_batch_rownum_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="delegationrow",
            constraint=models.UniqueConstraint(
                condition=models.Q(("candidate_email_hash", ""), _negated=True),
                fields=("batch", "candidate_email_hash"),
                name="inv_delrow_batch_identity_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="invitationcampaign",
            index=models.Index(
                fields=["event_edition", "organization"], name="inv_campaign_event_org_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitationcampaign",
            index=models.Index(fields=["status"], name="inv_campaign_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="invitationcampaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capacity__isnull", True), ("capacity__gte", 0), _connector="OR"
                ),
                name="inv_campaign_capacity_nonneg",
            ),
        ),
        migrations.AddIndex(
            model_name="invitationlink",
            index=models.Index(fields=["campaign", "status"], name="inv_link_campaign_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="invitationlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("campaign",),
                name="inv_link_one_active_per_campaign_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="invitationuse",
            index=models.Index(fields=["campaign", "occurred_at"], name="inv_use_campaign_idx"),
        ),
        migrations.AddIndex(
            model_name="invitationuse",
            index=models.Index(fields=["campaign", "use_kind"], name="inv_use_campaign_kind_idx"),
        ),
        migrations.AddConstraint(
            model_name="invitationuse",
            constraint=models.UniqueConstraint(
                fields=("registration", "use_kind"), name="inv_use_reg_kind_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="onbehalfclaim",
            index=models.Index(fields=["intended_email_hash"], name="inv_claim_email_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="onbehalfclaim",
            index=models.Index(fields=["status", "expires_at"], name="inv_claim_status_expiry_idx"),
        ),
    ]
