# Generated by Django 5.2.17 on 2026-09-21 10:34

import django.db.models.deletion
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0003_seed_delegation_claim_template"),
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegationrow",
            name="claim_delivery_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="communications.communicationmessage",
            ),
        ),
        migrations.AddField(
            model_name="delegationrow",
            name="claim_delivery_status",
            field=models.CharField(
                blank=True,
                choices=[("QUEUED", "Queued"), ("SENT", "Sent"), ("FAILED", "Failed")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="delegationrow",
            name="claim_delivery_url_encrypted",
            field=apps.core.fields.EncryptedTextField(blank=True, default=""),
        ),
    ]
