# Generated by Django 5.2.17 on 2026-09-19 23:17

import uuid

from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email_normalized", models.EmailField(max_length=254, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Internal"),
                            ("EXTERNAL_SECURITY", "External security"),
                            ("ORGANIZATION", "Organization"),
                            ("SUPPORT", "Support"),
                        ],
                        default="INTERNAL",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INVITED", "Invited"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("EXPIRED", "Expired"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="INVITED",
                        max_length=16,
                    ),
                ),
                (
                    "authentication_source",
                    models.CharField(
                        choices=[("LOCAL", "Local"), ("SSO", "SSO")], default="LOCAL", max_length=8
                    ),
                ),
                (
                    "mfa_state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("RESET_REQUIRED", "Reset required"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("active_from", models.DateTimeField(blank=True, null=True)),
                ("active_until", models.DateTimeField(blank=True, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_operational_user",
                "indexes": [models.Index(fields=["status"], name="accounts_user_status_idx")],
            },
            managers=[
                ("objects", apps.accounts.models.OperationalUserManager()),
            ],
        ),
    ]
