# Generated by Django 5.2.17 on 2026-09-19 23:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("events", "0001_initial"),
        ("organizations", "0002_professionalaffiliation"),
        ("people", "0002_identityverificationattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticationChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(choices=[("EMAIL", "Email"), ("SMS", "SMS")], max_length=8),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("PARTICIPANT_LOGIN", "Participant login")],
                        default="PARTICIPANT_LOGIN",
                        max_length=32,
                    ),
                ),
                ("recipient_fingerprint", models.CharField(max_length=64)),
                ("recipient_fingerprint_key_version", models.SmallIntegerField()),
                ("network_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                (
                    "network_fingerprint_key_version",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("otp_hash", models.CharField(max_length=200)),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("resend_available_at", models.DateTimeField(blank=True, null=True)),
                (
                    "request_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Bounded, non-identifying request context only -- never a plaintext recipient address, OTP value, or IP address.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="people.contactpoint",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_authentication_challenge",
                "indexes": [
                    models.Index(
                        fields=["recipient_fingerprint", "issued_at"],
                        name="acc_challenge_recipient_idx",
                    ),
                    models.Index(
                        fields=["network_fingerprint", "issued_at"],
                        name="acc_challenge_network_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScopedGroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("active_from", models.DateTimeField(blank=True, null=True)),
                ("active_until", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoped_memberships",
                        to="auth.group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoped_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_scoped_group_membership",
                "indexes": [
                    models.Index(fields=["user", "status"], name="acc_scopedmembership_user_idx"),
                    models.Index(
                        fields=["event_edition", "organization"],
                        name="acc_scopedmembership_scope_idx",
                    ),
                ],
            },
        ),
    ]
