# Generated by Django 5.2.17 on 2026-09-22 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_versioned_challenge_indexes"),
        ("events", "0004_venue_zone_gate"),
    ]

    operations = [
        migrations.AddField(
            model_name="scopedgroupmembership",
            name="gate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="events.gate",
            ),
        ),
        migrations.AddField(
            model_name="scopedgroupmembership",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="events.venue",
            ),
        ),
    ]
