# Generated by Django 5.2.17 on 2026-10-06 21:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_scopedgroupmembership_venue_gate"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialSetupToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("INVITATION", "Invitation"), ("RESET", "Password reset")],
                        max_length=16,
                    ),
                ),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credential_setup_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_credential_setup_token",
                "permissions": [
                    (
                        "manage_operational_accounts",
                        "Can create staff accounts, manage their status and grant scoped access",
                    )
                ],
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="acc_setup_token_user_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True), ("used_at__isnull", True)),
                        fields=("user",),
                        name="acc_setup_token_one_open_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("created_at"))),
                        name="acc_setup_token_expiry_after_creation",
                    ),
                ],
            },
        ),
    ]
