# Generated by Django 5.2.17 on 2026-09-19 23:20

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("MOBILE", "Mobile")], max_length=8
                    ),
                ),
                ("value_encrypted", apps.core.fields.EncryptedTextField()),
                ("value_hash", apps.core.fields.BlindIndexField(max_length=64)),
                ("value_hash_key_version", models.SmallIntegerField()),
                ("masked_value", models.CharField(max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("login_enabled", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("REPLACED", "Replaced"),
                            ("BOUNCED", "Bounced"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "country_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "db_table": "people_contact_point",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("MERGED", "Merged"),
                            ("ANONYMIZED", "Anonymized"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("birth_place", models.CharField(blank=True, default="", max_length=200)),
                (
                    "sex_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNSPECIFIED", "Unspecified"),
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("preferred_language", models.CharField(default="en", max_length=8)),
                (
                    "retention_class",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("EXTENDED", "Extended"),
                            ("LEGAL_HOLD", "Legal hold"),
                        ],
                        default="STANDARD",
                        max_length=16,
                    ),
                ),
                ("purge_after", models.DateTimeField(blank=True, null=True)),
                (
                    "birth_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.country",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merged_persons",
                        to="people.person",
                    ),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "db_table": "people_person",
            },
        ),
        migrations.CreateModel(
            name="ParticipantAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("LOCKED", "Locked"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "primary_login_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="people.contactpoint",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participant_account",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "people_participant_account",
            },
        ),
        migrations.CreateModel(
            name="IdentityIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[("NIN", "National identity number"), ("PASSPORT", "Passport")],
                        max_length=16,
                    ),
                ),
                ("value_encrypted", apps.core.fields.EncryptedTextField()),
                ("search_hash", apps.core.fields.BlindIndexField(max_length=64)),
                ("hash_key_version", models.SmallIntegerField()),
                ("masked_value", models.CharField(max_length=200)),
                ("issued_at", models.DateField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DECLARED", "Declared"),
                            ("VERIFIED", "Verified"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                            ("REPLACED", "Replaced"),
                        ],
                        default="DECLARED",
                        max_length=16,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "country_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.country",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_identifiers",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "people_identity_identifier",
            },
        ),
        migrations.AddField(
            model_name="contactpoint",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_points",
                to="people.person",
            ),
        ),
        migrations.CreateModel(
            name="PersonName",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name_type",
                    models.CharField(
                        choices=[
                            ("LEGAL", "Legal"),
                            ("PREFERRED", "Preferred"),
                            ("FORMER", "Former"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "script_code",
                    models.CharField(
                        default="Latn", help_text="ISO 15924, e.g. Latn, Arab.", max_length=8
                    ),
                ),
                ("given_names", models.CharField(max_length=200)),
                ("family_name", models.CharField(max_length=200)),
                ("full_name", models.CharField(max_length=400)),
                (
                    "normalized_search_name",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                ("is_current", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("APPLICANT", "Applicant"),
                            ("VERIFICATION_SERVICE", "Verification service"),
                            ("OPERATOR_CORRECTION", "Operator correction"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "people_person_name",
            },
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["status"], name="ppl_person_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                condition=models.Q(("merged_into", models.F("id")), _negated=True),
                name="ppl_person_no_self_merge",
            ),
        ),
        migrations.AddIndex(
            model_name="identityidentifier",
            index=models.Index(
                fields=["identifier_type", "country_code", "search_hash"],
                name="ppl_identid_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="identityidentifier",
            index=models.Index(fields=["person"], name="ppl_identid_person_idx"),
        ),
        migrations.AddConstraint(
            model_name="identityidentifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "VERIFIED")),
                fields=("identifier_type", "country_code", "search_hash"),
                name="ppl_identid_verified_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="contactpoint",
            index=models.Index(fields=["person", "type"], name="ppl_contact_person_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="contactpoint",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_verified", True),
                    ("login_enabled", True),
                    ("status", "ACTIVE"),
                    ("type", "EMAIL"),
                ),
                fields=("value_hash",),
                name="ppl_contact_active_login_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="personname",
            index=models.Index(fields=["person", "name_type"], name="ppl_pname_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="personname",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True), ("name_type", "LEGAL")),
                fields=("person", "script_code"),
                name="ppl_pname_cur_legal_uq",
            ),
        ),
    ]
