# Generated by Django 5.2.17 on 2026-09-19 23:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
        ("registrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityVerificationAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("EXTERNAL_SERVICE", "External service"),
                            ("MANUAL_DOCUMENT", "Manual document"),
                            ("SUPERVISED_CORRECTION", "Supervised correction"),
                        ],
                        max_length=24,
                    ),
                ),
                ("provider_code", models.CharField(blank=True, default="", max_length=64)),
                ("request_reference", models.CharField(blank=True, default="", max_length=200)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("MATCH", "Match"),
                            ("NO_MATCH", "No match"),
                            ("INCONCLUSIVE", "Inconclusive"),
                            ("UNAVAILABLE", "Unavailable"),
                            ("ERROR", "Error"),
                        ],
                        max_length=16,
                    ),
                ),
                ("matched_fields", models.JSONField(blank=True, default=dict)),
                ("provider_metadata", models.JSONField(blank=True, default=dict)),
                ("attempted_at", models.DateTimeField()),
                (
                    "identity_identifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_attempts",
                        to="people.identityidentifier",
                    ),
                ),
                (
                    "performed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_attempts",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "db_table": "people_identity_verification_attempt",
                "indexes": [
                    models.Index(
                        fields=["identity_identifier"], name="ppl_verifattempt_identid_idx"
                    ),
                    models.Index(fields=["registration"], name="ppl_verifattempt_reg_idx"),
                ],
            },
        ),
    ]
