# Generated by Django 5.2.17 on 2026-10-01 20:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_ux2_sector_taxonomy"),
        ("documents", "0002_national_id_card_document_type"),
        ("events", "0007_ux2_localized_event_names"),
        ("organizations", "0004_professionalaffiliation_operating_scope_and_more"),
        ("people", "0002_identityverificationattempt"),
        ("registrations", "0010_ux2_grouped_interest_topics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="identityverificationattempt",
            name="applied",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="attempt_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="comparison",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="detail_code",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="duration_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="evidence_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="http_status",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="is_official_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="official_birth_date",
            field=apps.core.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="official_birth_date_text",
            field=apps.core.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="official_family_name_latin",
            field=apps.core.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="official_given_names_latin",
            field=apps.core.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="outcome",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="policy_basis",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="presume_flag",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="reason_code",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.CreateModel(
            name="IdentityRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SUBMISSION", "Final submission"),
                            ("PARTICIPANT_RESUBMISSION", "Participant correction"),
                            ("STAFF_NIN_CORRECTION", "Staff NIN correction"),
                            ("STAFF_RECHECK", "Staff recheck"),
                        ],
                        max_length=32,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("fingerprint_key_version", models.SmallIntegerField()),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="people.person",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "identifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_revisions",
                        to="people.identityidentifier",
                    ),
                ),
            ],
            options={
                "db_table": "people_identity_revision",
            },
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="people.identityrevision",
            ),
        ),
        migrations.CreateModel(
            name="IdentityVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("NIN", "Algerian national identity number"),
                            ("PASSPORT", "Foreign passport"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Verification pending"),
                            ("API_VERIFIED", "Verified by the ministry service"),
                            ("MANUAL_REVIEW", "Needs manual review"),
                            ("MANUALLY_VERIFIED", "Verified manually"),
                            ("RETURNED_FOR_CORRECTION", "Returned for correction"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NOT_FOUND", "The ministry service did not find this NIN"),
                            (
                                "PROVIDER_IDENTITY_MISMATCH",
                                "The service answered for a different NIN",
                            ),
                            (
                                "DATA_MISMATCH",
                                "Names or birth date differ from the official record",
                            ),
                            ("AMBIGUOUS_DATE", "The official birth date could not be read safely"),
                            (
                                "PRESUME_FLAG_UNRECOGNIZED",
                                "The presumed-date flag is missing or not recognized",
                            ),
                            ("INVALID_RESPONSE", "The service response was invalid"),
                            ("PROVIDER_AUTH_ERROR", "The service refused authentication"),
                            (
                                "PROVIDER_UNAVAILABLE",
                                "The service was unavailable after every retry",
                            ),
                            ("PROVIDER_NOT_CONFIGURED", "The ministry service is not configured"),
                            (
                                "DUPLICATE_IDENTIFIER",
                                "Another person's registration uses this identifier",
                            ),
                            (
                                "FOREIGN_PASSPORT_REVIEW",
                                "Foreign participant: passport review required",
                            ),
                            (
                                "PARTICIPANT_RESUBMITTED",
                                "The participant resubmitted after a correction request",
                            ),
                            (
                                "IDENTITY_DATA_CHANGED",
                                "The identity data changed while a check was pending",
                            ),
                        ],
                        default="",
                        max_length=40,
                    ),
                ),
                (
                    "verification_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MINISTRY_API", "Ministry service"),
                            ("SIMULATED_API", "Development simulation (not official)"),
                            (
                                "MANUAL_NATIONAL_ID_CARD",
                                "Manual review of the national identity card",
                            ),
                            ("MANUAL_PASSPORT", "Manual review of the passport identity page"),
                            ("STAFF_EXCEPTION", "Staff-assisted exception"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("status_changed_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="people.identityrevision",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.country",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_verifications",
                        to="people.person",
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_verification",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "db_table": "people_identity_verification",
                "permissions": [
                    ("view_identity_evidence", "Can view identity evidence and full identifiers"),
                    ("verify_identity_manually", "Can verify an identity manually from evidence"),
                    ("correct_identity_nin", "Can correct a NIN from evidence and recheck it"),
                    ("return_identity_for_correction", "Can return an identity for correction"),
                    ("reject_identity", "Can finally reject an identity"),
                    (
                        "apply_identity_exception",
                        "Can verify an identity by staff-assisted exception",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="identityrevision",
            name="verification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="people.identityverification",
            ),
        ),
        migrations.CreateModel(
            name="IdentityDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("MANUAL_VERIFY", "Verified manually"),
                            ("EXCEPTION_VERIFY", "Verified by staff-assisted exception"),
                            ("RETURN_FOR_CORRECTION", "Returned for correction"),
                            ("NIN_CORRECTION", "NIN corrected and rechecked"),
                            ("RECHECK", "Rechecked with the ministry service"),
                            ("REJECT", "Rejected"),
                            ("PARTICIPANT_RESUBMISSION", "Participant resubmitted"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Verification pending"),
                            ("API_VERIFIED", "Verified by the ministry service"),
                            ("MANUAL_REVIEW", "Needs manual review"),
                            ("MANUALLY_VERIFIED", "Verified manually"),
                            ("RETURNED_FOR_CORRECTION", "Returned for correction"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Verification pending"),
                            ("API_VERIFIED", "Verified by the ministry service"),
                            ("MANUAL_REVIEW", "Needs manual review"),
                            ("MANUALLY_VERIFIED", "Verified manually"),
                            ("RETURNED_FOR_CORRECTION", "Returned for correction"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, default="", max_length=64)),
                ("note_encrypted", apps.core.fields.EncryptedTextField(blank=True, default="")),
                ("requested_items", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="people.person",
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evidence_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="people.identityrevision",
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="people.identityverification",
                    ),
                ),
            ],
            options={
                "db_table": "people_identity_decision",
            },
        ),
        migrations.CreateModel(
            name="IdentityVerificationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("DISCARDED_STALE", "Discarded (stale)"),
                            ("EXHAUSTED", "Retries exhausted"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField()),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_outcome", models.CharField(blank=True, default="", max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job",
                        to="people.identityrevision",
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="people.identityverification",
                    ),
                ),
            ],
            options={
                "db_table": "people_identity_verification_job",
            },
        ),
        migrations.AddField(
            model_name="identityverificationattempt",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provider_attempts",
                to="people.identityverificationjob",
            ),
        ),
        migrations.AddIndex(
            model_name="identityverificationattempt",
            index=models.Index(fields=["revision"], name="ppl_verifattempt_rev_idx"),
        ),
        migrations.AddIndex(
            model_name="identityverification",
            index=models.Index(
                fields=["event_edition", "status", "status_changed_at"],
                name="ppl_idv_event_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="identityverification",
            index=models.Index(fields=["organization", "status"], name="ppl_idv_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="identityverification",
            index=models.Index(fields=["status", "status_changed_at"], name="ppl_idv_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="identityverification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["API_VERIFIED", "MANUALLY_VERIFIED"]),
                        ("verification_source__gt", ""),
                    ),
                    models.Q(
                        models.Q(
                            ("status__in", ["API_VERIFIED", "MANUALLY_VERIFIED"]), _negated=True
                        ),
                        ("verification_source", ""),
                    ),
                    _connector="OR",
                ),
                name="ppl_idv_source_iff_verified",
            ),
        ),
        migrations.AddConstraint(
            model_name="identityrevision",
            constraint=models.UniqueConstraint(
                fields=("verification", "number"), name="ppl_idrev_verification_number_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="identitydecision",
            index=models.Index(
                fields=["verification", "created_at"], name="ppl_iddecision_ver_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identityverificationjob",
            index=models.Index(fields=["status", "next_attempt_at"], name="ppl_idjob_due_idx"),
        ),
        migrations.AddIndex(
            model_name="identityverificationjob",
            index=models.Index(fields=["status", "lease_expires_at"], name="ppl_idjob_lease_idx"),
        ),
    ]
