# Generated by Django 5.2.17 on 2026-10-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0003_identity_verification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identitydecision",
            name="action",
            field=models.CharField(
                choices=[
                    ("MANUAL_VERIFY", "Verified manually"),
                    ("EXCEPTION_VERIFY", "Verified by staff-assisted exception"),
                    ("RETURN_FOR_CORRECTION", "Returned for correction"),
                    ("NIN_CORRECTION", "NIN corrected and rechecked"),
                    ("RECHECK", "Rechecked with the ministry service"),
                    ("REJECT", "Rejected"),
                    ("PARTICIPANT_RESUBMISSION", "Participant resubmitted"),
                    (
                        "LINKED_IDENTITY_CHANGE",
                        "Identifier changed in another registration of the same person",
                    ),
                    ("OFFICIAL_NAME_APPLIED", "Official name form applied"),
                    ("REGISTRATION_CLOSED", "Registration closed"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="identityrevision",
            name="source",
            field=models.CharField(
                choices=[
                    ("SUBMISSION", "Final submission"),
                    ("PARTICIPANT_RESUBMISSION", "Participant correction"),
                    ("STAFF_NIN_CORRECTION", "Staff NIN correction"),
                    ("STAFF_RECHECK", "Staff recheck"),
                    (
                        "LINKED_IDENTITY_CHANGE",
                        "Identifier corrected in another registration of the same person",
                    ),
                    (
                        "OFFICIAL_NAME_NORMALIZATION",
                        "Official name form applied (case or spacing only)",
                    ),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_FOUND", "The ministry service did not find this NIN"),
                    ("PROVIDER_IDENTITY_MISMATCH", "The service answered for a different NIN"),
                    ("DATA_MISMATCH", "Names or birth date differ from the official record"),
                    ("AMBIGUOUS_DATE", "The official birth date could not be read safely"),
                    (
                        "PRESUME_FLAG_UNRECOGNIZED",
                        "The presumed-date flag is missing or not recognized",
                    ),
                    ("INVALID_RESPONSE", "The service response was invalid"),
                    ("PROVIDER_AUTH_ERROR", "The service refused authentication"),
                    ("PROVIDER_UNAVAILABLE", "The service was unavailable after every retry"),
                    ("PROVIDER_NOT_CONFIGURED", "The ministry service is not configured"),
                    ("DUPLICATE_IDENTIFIER", "Another person's registration uses this identifier"),
                    ("FOREIGN_PASSPORT_REVIEW", "Foreign participant: passport review required"),
                    (
                        "PARTICIPANT_RESUBMITTED",
                        "The participant resubmitted after a correction request",
                    ),
                    (
                        "IDENTITY_DATA_CHANGED",
                        "The identity data changed while a check was pending",
                    ),
                    (
                        "REGISTRATION_CLOSED",
                        "The registration was withdrawn, cancelled or not approved",
                    ),
                    (
                        "PROVIDER_ATTEMPTS_EXHAUSTED",
                        "Automatic checks stopped after the attempt limit",
                    ),
                ],
                default="",
                max_length=40,
            ),
        ),
    ]
