# Generated by Django 5.2.17 on 2026-10-02 09:56
"""Owner decisions IDV-Q1 to IDV-Q3 (2026-10-02).

* Choices only (no SQL): the NIN exemption route, the national identity card
  number identifier type, the documentary verification source and the
  documentary review reason (IDV-Q3).
* One new table, `people_nin_exemption` (IDV-Q3), with the
  `people.grant_nin_exemption` permission.

Additive. Rollback: `migrate people 0004` drops the table (and the exemption
history recorded since); rows written with the new choice values remain
readable as plain text.
"""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_ux2_localized_event_names"),
        ("organizations", "0004_professionalaffiliation_operating_scope_and_more"),
        ("people", "0004_idv_c1_lifecycle_choices"),
        ("registrations", "0010_ux2_grouped_interest_topics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="identityidentifier",
            name="identifier_type",
            field=models.CharField(
                choices=[
                    ("NIN", "National identity number"),
                    ("PASSPORT", "Passport"),
                    ("NATIONAL_ID_CARD", "National identity card number"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_FOUND", "The ministry service did not find this NIN"),
                    ("PROVIDER_IDENTITY_MISMATCH", "The service answered for a different NIN"),
                    ("DATA_MISMATCH", "Names or birth date differ from the official record"),
                    ("AMBIGUOUS_DATE", "The official birth date could not be read safely"),
                    (
                        "PRESUME_FLAG_UNRECOGNIZED",
                        "The presumed-date flag is missing or not recognized",
                    ),
                    ("INVALID_RESPONSE", "The service response was invalid"),
                    ("PROVIDER_AUTH_ERROR", "The service refused authentication"),
                    ("PROVIDER_UNAVAILABLE", "The service was unavailable after every retry"),
                    ("PROVIDER_NOT_CONFIGURED", "The ministry service is not configured"),
                    ("DUPLICATE_IDENTIFIER", "Another person's registration uses this identifier"),
                    ("FOREIGN_PASSPORT_REVIEW", "Foreign participant: passport review required"),
                    (
                        "PARTICIPANT_RESUBMITTED",
                        "The participant resubmitted after a correction request",
                    ),
                    (
                        "IDENTITY_DATA_CHANGED",
                        "The identity data changed while a check was pending",
                    ),
                    (
                        "REGISTRATION_CLOSED",
                        "The registration was withdrawn, cancelled or not approved",
                    ),
                    (
                        "PROVIDER_ATTEMPTS_EXHAUSTED",
                        "Automatic checks stopped after the attempt limit",
                    ),
                    (
                        "NIN_EXEMPTION_REVIEW",
                        "Algerian participant without a usable NIN: documentary review",
                    ),
                ],
                default="",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="route",
            field=models.CharField(
                choices=[
                    ("NIN", "Algerian national identity number"),
                    ("PASSPORT", "Foreign passport"),
                    ("NIN_EXEMPTION", "Algerian document without NIN (staff exemption)"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="verification_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MINISTRY_API", "Ministry service"),
                    ("SIMULATED_API", "Development simulation (not official)"),
                    ("MANUAL_NATIONAL_ID_CARD", "Manual review of the national identity card"),
                    ("MANUAL_PASSPORT", "Manual review of the passport identity page"),
                    ("STAFF_EXCEPTION", "Staff-assisted exception"),
                    ("MANUAL_NIN_EXEMPTION", "Manual documentary review (NIN exemption)"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="NinExemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active (draft may use the documentary route)"),
                            ("USED", "Used by the final submission"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            (
                                "NIN_NOT_ON_DOCUMENT",
                                "The participant's official Algerian document shows no NIN",
                            ),
                            (
                                "NIN_NOT_AVAILABLE",
                                "The participant has no NIN or cannot obtain it in time",
                            ),
                            ("OTHER_DOCUMENTED", "Other documented reason (explain below)"),
                        ],
                        max_length=40,
                    ),
                ),
                ("explanation_encrypted", apps.core.fields.EncryptedTextField()),
                ("granted_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_note_encrypted",
                    apps.core.fields.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "document_identifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="people.identityidentifier",
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nin_exemptions",
                        to="people.person",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nin_exemptions",
                        to="registrations.registration",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "people_nin_exemption",
                "permissions": [
                    ("grant_nin_exemption", "Can grant or revoke a NIN exemption for one draft")
                ],
                "indexes": [
                    models.Index(fields=["event_edition", "status"], name="ppl_ninexempt_event_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["ACTIVE", "USED"])),
                        fields=("registration",),
                        name="ppl_ninexempt_one_live_uq",
                    )
                ],
            },
        ),
    ]
