# Generated by Django 5.2.17 on 2026-10-07 05:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0005_idv_owner_decisions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="identityverification",
            options={
                "permissions": [
                    ("view_identity_evidence", "Can view identity evidence and full identifiers"),
                    ("verify_identity_manually", "Can verify an identity manually from evidence"),
                    ("correct_identity_nin", "Can correct a NIN from evidence and recheck it"),
                    ("return_identity_for_correction", "Can return an identity for correction"),
                    ("reject_identity", "Can finally reject an identity"),
                    (
                        "apply_identity_exception",
                        "Can verify an identity by staff-assisted exception",
                    ),
                    (
                        "run_ministry_nin_diagnostics",
                        "Can test the Ministry NIN service configuration, authentication and lookup",
                    ),
                ]
            },
        ),
    ]
