# Generated by Django 5.2.17 on 2026-09-21 16:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0003_eventedition_passport_identity_page_upload_enabled"),
        ("organizations", "0003_professionalaffiliation_biography_and_more"),
        ("registrations", "0006_alter_registration_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("name_fr", models.CharField(blank=True, default="", max_length=200)),
                ("name_ar", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_profiles",
                        to="events.eventedition",
                    ),
                ),
            ],
            options={
                "db_table": "accreditation_access_profile",
            },
        ),
        migrations.CreateModel(
            name="AccessProfileAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current"),
                            ("SUPERSEDED", "Superseded"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="CURRENT",
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateTimeField()),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                (
                    "access_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accreditation.accessprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_profile_assignments",
                        to="registrations.registration",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="accreditation.accessprofileassignment",
                    ),
                ),
            ],
            options={
                "db_table": "accreditation_access_profile_assignment",
            },
        ),
        migrations.CreateModel(
            name="AccessRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("name_fr", models.CharField(blank=True, default="", max_length=200)),
                ("name_ar", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "access_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="accreditation.accessprofile",
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_rules",
                        to="events.eventedition",
                    ),
                ),
            ],
            options={
                "db_table": "accreditation_access_rule",
            },
        ),
        migrations.CreateModel(
            name="AccessRuleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current"),
                            ("SUPERSEDED", "Superseded"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="CURRENT",
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateTimeField()),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                (
                    "access_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accreditation.accessrule",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_rule_assignments",
                        to="registrations.registration",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="accreditation.accessruleassignment",
                    ),
                ),
            ],
            options={
                "db_table": "accreditation_access_rule_assignment",
            },
        ),
        migrations.CreateModel(
            name="BadgeType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("name_fr", models.CharField(blank=True, default="", max_length=200)),
                ("name_ar", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("participant_visible", models.BooleanField(default=False)),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="badge_types",
                        to="events.eventedition",
                    ),
                ),
            ],
            options={
                "db_table": "accreditation_badge_type",
            },
        ),
        migrations.CreateModel(
            name="BadgeTypeAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current"),
                            ("SUPERSEDED", "Superseded"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="CURRENT",
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateTimeField()),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                (
                    "badge_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accreditation.badgetype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="badge_assignments",
                        to="registrations.registration",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="accreditation.badgetypeassignment",
                    ),
                ),
            ],
            options={
                "db_table": "accreditation_badge_type_assignment",
            },
        ),
        migrations.CreateModel(
            name="BulkAssignmentOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PARTICIPANT_ROLE", "Participant role"),
                            ("BADGE_TYPE", "Badge type"),
                            ("ACCESS_PROFILE", "Access profile"),
                            ("ACCESS_RULE", "Access rule"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reference_object_id", models.UUIDField()),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("target_registration_ids", models.JSONField(default=list)),
                ("preview_results", models.JSONField(blank=True, default=list)),
                ("execution_results", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEWED", "Previewed"),
                            ("EXECUTED", "Executed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PREVIEWED",
                        max_length=16,
                    ),
                ),
                ("previewed_at", models.DateTimeField()),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accreditation_bulk_assignment_operation",
            },
        ),
        migrations.CreateModel(
            name="ParticipantRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("name_fr", models.CharField(blank=True, default="", max_length=200)),
                ("name_ar", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participant_roles",
                        to="events.eventedition",
                    ),
                ),
            ],
            options={
                "db_table": "accreditation_participant_role",
            },
        ),
        migrations.CreateModel(
            name="ParticipantRoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current"),
                            ("SUPERSEDED", "Superseded"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="CURRENT",
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateTimeField()),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_assignments",
                        to="registrations.registration",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accreditation.participantrole",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="accreditation.participantroleassignment",
                    ),
                ),
            ],
            options={
                "db_table": "accreditation_participant_role_assignment",
            },
        ),
        migrations.AddConstraint(
            model_name="accessprofile",
            constraint=models.UniqueConstraint(
                fields=("event_edition", "code"), name="acc_accessprofile_event_code_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="accessprofileassignment",
            index=models.Index(
                fields=["registration", "status"], name="acc_profile_assign_reg_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="accessprofileassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CURRENT")),
                fields=("registration", "access_profile"),
                name="acc_profile_assignment_one_current_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessprofileassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__isnull", True),
                    ("effective_until__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="acc_profile_assignment_valid_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrule",
            constraint=models.UniqueConstraint(
                fields=("event_edition", "code"), name="acc_accessrule_event_code_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="accessruleassignment",
            index=models.Index(fields=["registration", "status"], name="acc_rule_assign_reg_idx"),
        ),
        migrations.AddConstraint(
            model_name="accessruleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CURRENT")),
                fields=("registration", "access_rule"),
                name="acc_rule_assignment_one_current_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessruleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__isnull", True),
                    ("effective_until__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="acc_rule_assignment_valid_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="badgetype",
            constraint=models.UniqueConstraint(
                fields=("event_edition", "code"), name="acc_badgetype_event_code_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="badgetypeassignment",
            index=models.Index(fields=["registration", "status"], name="acc_badge_assign_reg_idx"),
        ),
        migrations.AddConstraint(
            model_name="badgetypeassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CURRENT")),
                fields=("registration",),
                name="acc_badge_assignment_one_current_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="badgetypeassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__isnull", True),
                    ("effective_until__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="acc_badge_assignment_valid_range",
            ),
        ),
        migrations.AddIndex(
            model_name="bulkassignmentoperation",
            index=models.Index(
                fields=["event_edition", "status"], name="acc_bulkop_event_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="participantrole",
            constraint=models.UniqueConstraint(
                fields=("event_edition", "code"), name="acc_role_event_code_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="participantroleassignment",
            index=models.Index(fields=["registration", "status"], name="acc_role_assign_reg_idx"),
        ),
        migrations.AddConstraint(
            model_name="participantroleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CURRENT")),
                fields=("registration", "role"),
                name="acc_role_assignment_one_current_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="participantroleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__isnull", True),
                    ("effective_until__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="acc_role_assignment_valid_range",
            ),
        ),
    ]
