# Generated by Django 5.2.17 on 2026-09-21 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accreditation", "0001_initial"),
        ("events", "0003_eventedition_passport_identity_page_upload_enabled"),
        ("organizations", "0003_professionalaffiliation_biography_and_more"),
        ("registrations", "0006_alter_registration_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accessprofileassignment",
            name="acc_profile_assignment_one_current_uq",
        ),
        migrations.RemoveConstraint(
            model_name="participantroleassignment",
            name="acc_role_assignment_one_current_uq",
        ),
        migrations.AddField(
            model_name="accessprofileassignment",
            name="end_reason",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="accessprofileassignment",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessprofileassignment",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accessruleassignment",
            name="end_reason",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="accessruleassignment",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessruleassignment",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="badgetypeassignment",
            name="end_reason",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="badgetypeassignment",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badgetypeassignment",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participantroleassignment",
            name="end_reason",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="participantroleassignment",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participantroleassignment",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="accessprofileassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CURRENT")),
                fields=("registration",),
                name="acc_profile_assignment_one_current_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="participantroleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CURRENT")),
                fields=("registration",),
                name="acc_role_assignment_one_current_uq",
            ),
        ),
    ]
