"""Phase 3 Prompt 2: additive public reference on BadgeTypeAssignment.

The Digital Entry Pass QR carries a badge-assignment reference as its `bai`
claim. It must not be the assignment's UUIDv7 primary key: `FR-BDG-005`
forbids a direct internal record identifier in the QR, and a UUIDv7 is
time-ordered, so publishing it would leak assignment creation ordering.

This migration is additive and reversible. It adds the column with a blank
default, backfills a distinct random reference for every existing row, then
switches the field to its per-instance callable default and installs a
PARTIAL unique constraint that ignores blank values -- so there is never an
instant where the constraint is unsatisfiable.

No Phase 2 column is altered, dropped, or retyped, and no historical
migration is edited.
"""

from django.conf import settings
from django.db import migrations, models

import apps.accreditation.models


def backfill_public_references(apps_registry, schema_editor):
    """Assign one distinct random reference per existing assignment row.

    Written as an explicit per-row loop rather than a bulk default because
    a database-level default would give every pre-existing row the SAME
    value, which the unique constraint added below would then reject.
    Idempotent: rows that already carry a reference are left untouched, so
    re-running this migration is safe.
    """
    BadgeTypeAssignment = apps_registry.get_model("accreditation", "BadgeTypeAssignment")
    generate = apps.accreditation.models.generate_assignment_public_reference
    for assignment in BadgeTypeAssignment.objects.filter(public_reference="").iterator():
        assignment.public_reference = generate()
        assignment.save(update_fields=["public_reference"])


def clear_public_references(apps_registry, schema_editor):
    """Reverse: blank the column so the field can be reverted and dropped.

    The references are opaque, carry no meaning outside an issued
    credential, and are regenerated by the forward migration, so clearing
    them destroys no participant data.
    """
    BadgeTypeAssignment = apps_registry.get_model("accreditation", "BadgeTypeAssignment")
    BadgeTypeAssignment.objects.update(public_reference="")


class Migration(migrations.Migration):
    dependencies = [
        (
            "accreditation",
            "0002_remove_accessprofileassignment_acc_profile_assignment_one_current_uq_and_more",
        ),
        ("events", "0003_eventedition_passport_identity_page_upload_enabled"),
        ("organizations", "0003_professionalaffiliation_biography_and_more"),
        ("registrations", "0006_alter_registration_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="badgetypeassignment",
            name="public_reference",
            field=models.CharField(blank=True, default="", max_length=22),
        ),
        migrations.RunPython(backfill_public_references, clear_public_references),
        migrations.AlterField(
            model_name="badgetypeassignment",
            name="public_reference",
            field=models.CharField(
                blank=True,
                default=apps.accreditation.models.generate_assignment_public_reference,
                max_length=22,
            ),
        ),
        migrations.AddConstraint(
            model_name="badgetypeassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("public_reference", ""), _negated=True),
                fields=("public_reference",),
                name="acc_badge_assignment_public_ref_uq",
            ),
        ),
    ]
