# Generated by Django 5.2.17 on 2026-09-22 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accreditation", "0004_phase3_prompt2_corrections"),
        ("events", "0004_venue_zone_gate"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessprofile",
            name="reentry_policy",
            field=models.CharField(
                choices=[
                    ("REENTRY_ALLOWED", "Re-entry allowed"),
                    ("SINGLE_ENTRY", "Single entry only"),
                ],
                default="REENTRY_ALLOWED",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="accessprofile",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessprofile",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessrule",
            name="effect",
            field=models.CharField(
                choices=[("ALLOW", "Allow"), ("DENY", "Deny")], default="ALLOW", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="accessrule",
            name="event_type",
            field=models.CharField(
                choices=[("ENTRY", "Entry"), ("EXIT", "Exit"), ("ANY", "Entry or exit")],
                default="ENTRY",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="accessrule",
            name="gate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="events.gate",
            ),
        ),
        migrations.AddField(
            model_name="accessrule",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessrule",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessrule",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="events.zone",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_from__isnull", True),
                    ("valid_until__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="acc_accessprofile_valid_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gate__isnull", True), ("zone__isnull", False), _connector="OR"
                ),
                name="acc_accessrule_gate_requires_zone",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_from__isnull", True),
                    ("valid_until__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="acc_accessrule_valid_range",
            ),
        ),
    ]
