# Generated by Django 5.2.17 on 2026-10-06 21:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accreditation", "0005_access_checkpoint_rules"),
        ("events", "0007_ux2_localized_event_names"),
        ("registrations", "0010_ux2_grouped_interest_topics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceEntitlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ALL_CONFERENCE_DAYS", "All three conference days"),
                            ("FOLLOWING_TWO_DAYS", "The two days after the opening day"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("CURRENT", "Current"), ("SUPERSEDED", "Superseded")],
                        default="CURRENT",
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("APPROVAL", "Chosen at approval"),
                            ("LEGACY_CLASSIFICATION", "Classification of an earlier approval"),
                            ("CHANGE", "Change after approval"),
                        ],
                        max_length=24,
                    ),
                ),
                ("effective_from", models.DateTimeField()),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("decision_id", models.UUIDField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_entitlements",
                        to="registrations.registration",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="accreditation.attendanceentitlement",
                    ),
                ),
            ],
            options={
                "db_table": "accreditation_attendance_entitlement",
                "indexes": [
                    models.Index(
                        fields=["event_edition", "status", "category"],
                        name="acc_attendance_event_idx",
                    ),
                    models.Index(fields=["registration", "status"], name="acc_attendance_reg_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "CURRENT")),
                        fields=("registration",),
                        name="acc_attendance_one_current_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_until__isnull", True),
                            ("effective_until__gte", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="acc_attendance_valid_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendancePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("opening_date", models.DateField(blank=True, null=True)),
                ("second_date", models.DateField(blank=True, null=True)),
                ("third_date", models.DateField(blank=True, null=True)),
                ("opening_day_capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("enforcement_active", models.BooleanField(default=False)),
                ("enforcement_activated_at", models.DateTimeField(blank=True, null=True)),
                ("enforcement_deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enforcement_activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enforcement_deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_edition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_policy",
                        to="events.eventedition",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accreditation_attendance_policy",
                "permissions": [
                    (
                        "manage_attendancepolicy",
                        "Can configure attendance days, opening-day capacity and enforcement",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("opening_date__isnull", True),
                                ("second_date__isnull", True),
                                ("third_date__isnull", True),
                            ),
                            models.Q(
                                ("opening_date__isnull", False),
                                ("second_date__gt", models.F("opening_date")),
                                ("second_date__isnull", False),
                                ("third_date__gt", models.F("second_date")),
                                ("third_date__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="acc_attpolicy_dates_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("enforcement_active", False),
                            models.Q(
                                ("enforcement_activated_at__isnull", False),
                                ("opening_date__isnull", False),
                                ("opening_day_capacity__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="acc_attpolicy_active_requires_configuration",
                    ),
                ],
            },
        ),
    ]
