# Generated by Django 5.2.17 on 2026-10-07 05:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

ACTIVATED = "ACC_ATTENDANCE_ENFORCEMENT_ACTIVATED"


def rebuild_intervals(apps, schema_editor):
    """Rebuild the enforcement history kept so far in the policy row only.

    Nothing is invented. The policy kept the LAST activation and the LAST
    deactivation; earlier cycles were overwritten. The number of recorded
    activations (audit events, read only to know whether more than one cycle
    happened, never for timestamps) tells whether that is the whole history:

    * one activation at most: the known interval is the complete history;
    * more, or unknown: the period before the earliest known switch becomes
      an UNCERTAIN interval starting at the policy's creation, which counts as
      enforced -- an operation from that period is judged by the stricter
      rule instead of being silently accepted.
    """
    from django.utils import timezone

    Policy = apps.get_model("accreditation", "AttendancePolicy")
    Interval = apps.get_model("accreditation", "AttendanceEnforcementInterval")
    AuditEvent = apps.get_model("audit", "AuditEvent")
    now = timezone.now()
    for policy in Policy.objects.filter(enforcement_activated_at__isnull=False):
        start, end = policy.enforcement_activated_at, policy.enforcement_deactivated_at
        activations = AuditEvent.objects.filter(
            action_code=ACTIVATED, event_edition_id=policy.event_edition_id, result="SUCCESS"
        ).count()
        complete = activations == 1
        rows = []
        if policy.enforcement_active and end is None:
            rows.append((start, None, policy.enforcement_activated_by_id, None, "RECONSTRUCTED"))
        elif policy.enforcement_active:
            # Switched off at `end` and on again at `start`: the interval
            # that ended at `end` began at an unrecorded time.
            rows.append((policy.created_at, min(end, start), None, None, "UNCERTAIN"))
            rows.append((start, None, policy.enforcement_activated_by_id, None, "RECONSTRUCTED"))
        elif end is not None and end > start:
            if not complete:
                rows.append((policy.created_at, start, None, None, "UNCERTAIN"))
            rows.append(
                (
                    start,
                    end,
                    policy.enforcement_activated_by_id,
                    policy.enforcement_deactivated_by_id,
                    "RECONSTRUCTED",
                )
            )
        else:
            # Inconsistent switch fields: nothing reliable is known.
            rows.append((policy.created_at, max(now, start), None, None, "UNCERTAIN"))
        for started_at, ended_at, started_by, ended_by, source in rows:
            if ended_at is not None and ended_at <= started_at:
                continue
            Interval.objects.create(
                policy_id=policy.pk,
                started_at=started_at,
                ended_at=ended_at,
                started_by_id=started_by,
                ended_by_id=ended_by,
                source=source,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("accreditation", "0006_attendance_entitlements"),
        ("audit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceEnforcementInterval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("RECORDED", "Recorded when enforcement was switched on"),
                            ("RECONSTRUCTED", "Rebuilt from the last recorded switch"),
                            ("UNCERTAIN", "Earlier history not recorded (treated as enforced)"),
                        ],
                        default="RECORDED",
                        max_length=16,
                    ),
                ),
                (
                    "ended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enforcement_intervals",
                        to="accreditation.attendancepolicy",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accreditation_attendance_enforcement_interval",
                "ordering": ["started_at"],
                "indexes": [
                    models.Index(
                        fields=["policy", "started_at"], name="acc_attenf_policy_start_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("policy",),
                        name="acc_attenf_one_open_per_policy",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ended_at__isnull", True),
                            ("ended_at__gt", models.F("started_at")),
                            _connector="OR",
                        ),
                        name="acc_attenf_end_after_start",
                    ),
                ],
            },
        ),
        migrations.RunPython(rebuild_intervals, migrations.RunPython.noop),
    ]
