# Generated by Django 5.2.17 on 2026-09-19 23:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("people", "0002_identityverificationattempt"),
        ("registrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100, unique=True)),
                (
                    "channel",
                    models.CharField(choices=[("EMAIL", "Email"), ("SMS", "SMS")], max_length=8),
                ),
                ("purpose_code", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "communications_message_template",
            },
        ),
        migrations.CreateModel(
            name="MessageTemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language", models.CharField(max_length=8)),
                ("version_label", models.CharField(max_length=32)),
                ("subject", models.CharField(blank=True, default="", max_length=300)),
                ("body", models.TextField()),
                ("allowed_variables", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateTimeField()),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("content_hash", models.CharField(max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="communications.messagetemplate",
                    ),
                ),
            ],
            options={
                "db_table": "communications_message_template_version",
            },
        ),
        migrations.CreateModel(
            name="CommunicationMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(choices=[("EMAIL", "Email"), ("SMS", "SMS")], max_length=8),
                ),
                ("language", models.CharField(max_length=8)),
                ("destination_encrypted", apps.core.fields.EncryptedTextField()),
                ("destination_hash", apps.core.fields.BlindIndexField(max_length=64)),
                ("destination_hash_key_version", models.SmallIntegerField()),
                ("variable_snapshot", apps.core.fields.EncryptedTextField(blank=True, default="")),
                ("content_hash", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("DEFERRED", "Deferred"),
                            ("FAILED", "Failed"),
                            ("BOUNCED", "Bounced"),
                            ("UNDELIVERABLE", "Undeliverable"),
                            ("SUPPRESSED", "Suppressed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("suppression_reason", models.CharField(blank=True, default="", max_length=100)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="people.person",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="registrations.registration",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="communications.messagetemplateversion",
                    ),
                ),
            ],
            options={
                "db_table": "communications_message",
            },
        ),
        migrations.CreateModel(
            name="SuppressionEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(choices=[("EMAIL", "Email"), ("SMS", "SMS")], max_length=8),
                ),
                ("destination_hash", apps.core.fields.BlindIndexField(max_length=64)),
                ("destination_hash_key_version", models.SmallIntegerField()),
                ("reason", models.CharField(max_length=100)),
                ("provider_evidence", models.CharField(blank=True, default="", max_length=300)),
                ("active_from", models.DateTimeField()),
                ("active_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "communications_suppression_entry",
                "indexes": [
                    models.Index(
                        fields=["channel", "destination_hash"], name="comm_suppression_dest_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("provider_code", models.CharField(blank=True, default="", max_length=64)),
                ("provider_reference", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("DEFERRED", "Deferred"),
                            ("FAILED", "Failed"),
                            ("BOUNCED", "Bounced"),
                            ("UNDELIVERABLE", "Undeliverable"),
                            ("SUPPRESSED", "Suppressed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                ("response_code", models.CharField(blank=True, default="", max_length=100)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="communications.communicationmessage",
                    ),
                ),
            ],
            options={
                "db_table": "communications_delivery_attempt",
                "indexes": [
                    models.Index(fields=["message", "attempt_number"], name="comm_delivery_msg_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "attempt_number"), name="comm_delivery_msg_attempt_uq"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="messagetemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "language", "version_label"),
                name="comm_tmplversion_tmpl_lang_label_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="communicationmessage",
            index=models.Index(fields=["status", "queued_at"], name="comm_message_status_idx"),
        ),
        migrations.AddIndex(
            model_name="communicationmessage",
            index=models.Index(fields=["destination_hash"], name="comm_message_dest_hash_idx"),
        ),
    ]
