# Generated by Django 5.2.17 on 2026-09-21 19:23

from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0004_seed_prompt5_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicationmessage",
            name="rendered_body_encrypted",
            field=apps.core.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="communicationmessage",
            name="rendered_subject",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
