# Generated by Django 5.2.17 on 2026-09-19 23:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # ADR-0011: accounts.0001 (OperationalUser) must be the first
        # project application migration in the whole graph. core.0001 has
        # no FK-driven dependency on it, so this ordering edge is explicit
        # rather than incidental.
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("name_fr", models.CharField(blank=True, default="", max_length=200)),
                ("name_ar", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name_plural": "countries",
                "db_table": "core_country",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("name_fr", models.CharField(blank=True, default="", max_length=200)),
                ("name_ar", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "core_sector",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(max_length=200)),
                ("aggregate_type", models.CharField(max_length=100)),
                ("aggregate_id", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PUBLISHED", "Published"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "core_outbox_event",
                "indexes": [
                    models.Index(
                        fields=["status", "occurred_at"], name="core_outbox_status_occurred"
                    ),
                    models.Index(
                        fields=["aggregate_type", "aggregate_id"], name="core_outbox_aggregate"
                    ),
                ],
            },
        ),
    ]
