# Generated by Django 5.2.17 on 2026-09-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HumanChallengeUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("signature_digest", models.CharField(max_length=64, unique=True)),
                ("action", models.CharField(max_length=32)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "core_human_challenge_use",
                "indexes": [models.Index(fields=["expires_at"], name="core_humanchk_expires")],
            },
        ),
    ]
