# Generated by Django 5.2.17 on 2026-10-02 21:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_ux2_sector_taxonomy"),
    ]

    operations = [
        migrations.CreateModel(
            name="StagingProvisioningSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pattern_digest", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "core_staging_provisioning_set",
            },
        ),
        migrations.CreateModel(
            name="StagingProvisionedObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("ACCOUNT", "Operational account"),
                            ("MEMBERSHIP", "Scoped group membership"),
                            ("ORGANIZATION", "Organization"),
                            ("EVENT", "Event edition"),
                            ("CAMPAIGN", "Invitation campaign"),
                            ("LINK", "Invitation link"),
                        ],
                        max_length=16,
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("key", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provisioning_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_objects",
                        to="core.stagingprovisioningset",
                    ),
                ),
            ],
            options={
                "db_table": "core_staging_provisioned_object",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("object_type", "object_id"), name="core_staging_object_uq"
                    )
                ],
            },
        ),
    ]
