# Generated by Django 5.2.17 on 2026-09-19 23:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0001_initial"),
        ("registrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("storage_key", models.CharField(max_length=200, unique=True)),
                (
                    "bucket_class",
                    models.CharField(
                        choices=[
                            ("RESTRICTED", "Restricted"),
                            ("STANDARD_PROTECTED", "Standard protected"),
                        ],
                        max_length=24,
                    ),
                ),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.BigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("encryption_key_ref", models.CharField(blank=True, default="", max_length=200)),
                (
                    "malware_scan_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CLEAN", "Clean"),
                            ("REJECTED", "Rejected"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("purge_after", models.DateTimeField(blank=True, null=True)),
                ("legal_hold", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "documents_stored_object",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PROFILE_PHOTO", "Profile photo"),
                            ("PASSPORT_IDENTITY_PAGE", "Passport identity page"),
                            ("REQUESTED_EVIDENCE", "Requested evidence"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("purpose_code", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("REPLACED", "Replaced"),
                            ("REJECTED", "Rejected"),
                            ("PURGED", "Purged"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="people.person",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="registrations.registration",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="documents.document",
                    ),
                ),
                (
                    "verified_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stored_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document",
                        to="documents.storedobject",
                    ),
                ),
            ],
            options={
                "db_table": "documents_document",
                "indexes": [
                    models.Index(
                        fields=["registration", "document_type", "status"],
                        name="doc_document_reg_type_idx",
                    )
                ],
            },
        ),
    ]
