# Generated by Django 5.2.17 on 2026-10-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("PROFILE_PHOTO", "Profile photo"),
                    ("PASSPORT_IDENTITY_PAGE", "Passport identity page"),
                    ("NATIONAL_ID_CARD", "National identity card"),
                    ("REQUESTED_EVIDENCE", "Requested evidence"),
                    ("OTHER", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
