# Generated by Django 5.2.17 on 2026-09-19 23:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("events", "0001_initial"),
        ("organizations", "0001_initial"),
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestTopic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=200)),
                ("label_fr", models.CharField(blank=True, default="", max_length=200)),
                ("label_ar", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_topics",
                        to="events.eventedition",
                    ),
                ),
            ],
            options={
                "db_table": "registrations_interest_topic",
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("public_reference", models.CharField(max_length=32, unique=True)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVITATION", "Invitation"),
                            ("DELEGATION", "Delegation"),
                            ("ON_BEHALF", "On behalf"),
                            ("ON_SITE", "On site"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_context_key", models.CharField(max_length=200)),
                ("deduplication_key", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "public_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("ADDITIONAL_INFORMATION_REQUIRED", "Additional information required"),
                            ("APPROVED", "Approved"),
                            ("NOT_APPROVED", "Not approved"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                (
                    "internal_status",
                    models.CharField(
                        choices=[
                            ("PENDING_ASSIGNMENT", "Pending assignment"),
                            ("ASSIGNED", "Assigned"),
                            ("VERIFICATION_PENDING", "Verification pending"),
                            ("DUPLICATE_REVIEW", "Duplicate review"),
                            ("REVIEW_IN_PROGRESS", "Review in progress"),
                            ("AWAITING_APPLICANT", "Awaiting applicant"),
                            ("QUALIFICATION_COMPLETE", "Qualification complete"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PENDING_ASSIGNMENT",
                        max_length=32,
                    ),
                ),
                ("is_current_context", models.BooleanField(default=True)),
                ("preferred_language", models.CharField(default="en", max_length=8)),
                ("current_step", models.CharField(blank=True, default="", max_length=100)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="events.eventedition",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="people.person",
                    ),
                ),
                (
                    "source_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "registrations_registration",
            },
        ),
        migrations.CreateModel(
            name="RegistrationInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("priority", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                (
                    "interest_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="registrations.interesttopic",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "db_table": "registrations_interest",
            },
        ),
        migrations.CreateModel(
            name="RegistrationProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_given_names", models.CharField(blank=True, default="", max_length=200)),
                ("submitted_family_name", models.CharField(blank=True, default="", max_length=200)),
                ("submitted_full_name", models.CharField(blank=True, default="", max_length=400)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("objectives_text", models.CharField(blank=True, default="", max_length=2000)),
                (
                    "accessibility_needs_text",
                    models.CharField(blank=True, default="", max_length=2000),
                ),
                (
                    "country_of_residence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.country",
                    ),
                ),
                (
                    "nationality_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.country",
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="registrations.registration",
                    ),
                ),
                (
                    "verified_email_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="people.contactpoint",
                    ),
                ),
                (
                    "verified_mobile_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="people.contactpoint",
                    ),
                ),
            ],
            options={
                "db_table": "registrations_profile",
            },
        ),
        migrations.CreateModel(
            name="RegistrationSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "submission_kind",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial"),
                            ("ADDITIONAL_INFORMATION_RESPONSE", "Additional information response"),
                            ("AUTHORIZED_RESUBMISSION", "Authorized resubmission"),
                        ],
                        max_length=40,
                    ),
                ),
                ("snapshot_json", models.JSONField()),
                ("snapshot_hash", models.CharField(max_length=64)),
                (
                    "submitted_by_type",
                    models.CharField(
                        choices=[
                            ("PARTICIPANT", "Participant"),
                            ("OPERATIONAL_USER", "Operational user"),
                            ("SYSTEM_MIGRATION", "System migration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="registrations.registration",
                    ),
                ),
                (
                    "submitted_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "registrations_submission",
            },
        ),
        migrations.AddConstraint(
            model_name="interesttopic",
            constraint=models.UniqueConstraint(
                fields=("event_edition", "code"), name="reg_interesttopic_event_code_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["event_edition", "public_status", "created_at"],
                name="reg_regn_pub_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["event_edition", "internal_status", "updated_at"],
                name="reg_regn_int_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["person", "event_edition"], name="reg_registration_person_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["source_organization", "event_edition"], name="reg_registration_org_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current_context", True)),
                fields=("deduplication_key",),
                name="reg_registration_current_dedup_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationinterest",
            constraint=models.UniqueConstraint(
                fields=("registration", "interest_topic"), name="reg_interest_reg_topic_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="registrationsubmission",
            index=models.Index(
                fields=["registration", "submitted_at"], name="reg_submission_reg_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationsubmission",
            constraint=models.UniqueConstraint(
                fields=("registration", "sequence"), name="reg_submission_reg_sequence_uq"
            ),
        ),
    ]
