# Generated by Django 5.2.17 on 2026-09-20 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_identityverificationattempt"),
        ("registrations", "0002_seed_interest_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationprofile",
            name="declared_mobile_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="people.contactpoint",
            ),
        ),
    ]
