# Generated by Django 5.2.17 on 2026-09-20 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0003_registrationprofile_declared_mobile_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="registrationsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("submission_kind", "INITIAL")),
                fields=("registration",),
                name="reg_submission_one_initial_uq",
            ),
        ),
    ]
