# Generated by Django 5.2.17 on 2026-09-20 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_eventedition_passport_identity_page_upload_enabled"),
        ("invitations", "0001_initial"),
        ("organizations", "0003_professionalaffiliation_biography_and_more"),
        ("people", "0002_identityverificationattempt"),
        ("registrations", "0004_registrationsubmission_reg_submission_one_initial_uq"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="created_on_behalf_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="invitation_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="invitations.invitationcampaign",
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["invitation_campaign", "submitted_at"], name="reg_registration_camp_idx"
            ),
        ),
    ]
