# Generated by Django 5.2.17 on 2026-09-20 23:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0005_registration_claimed_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={
                "permissions": [
                    ("register_on_behalf", "Can create an on-behalf draft registration")
                ]
            },
        ),
    ]
