# Generated by Django 5.2.17 on 2026-09-22 23:47

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_venue_zone_gate"),
        ("invitations", "0002_delegationrow_claim_delivery_message_and_more"),
        ("organizations", "0003_professionalaffiliation_biography_and_more"),
        ("people", "0002_identityverificationattempt"),
        ("registrations", "0006_alter_registration_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                django.db.models.functions.text.Upper("public_reference"),
                name="reg_public_ref_upper_idx",
            ),
        ),
    ]
