# Generated by Django 5.2.17 on 2026-09-29 17:47

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0007_registration_reg_public_ref_upper_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccommodationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "answer",
                    models.CharField(
                        choices=[
                            ("NO", "No"),
                            ("YES", "Yes"),
                            ("PREFER_NOT_TO_SAY", "Prefer not to say"),
                        ],
                        max_length=24,
                    ),
                ),
                ("categories", models.JSONField(blank=True, default=list)),
                ("note_encrypted", apps.core.fields.EncryptedTextField(blank=True, default="")),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accommodation_request",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "db_table": "registrations_accommodation_request",
                "permissions": [
                    (
                        "coordinate_accommodation_support",
                        "Can view and arrange accommodation support requests",
                    )
                ],
            },
        ),
    ]
