# Generated by Django 5.2.17 on 2026-09-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0008_accommodation_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="interesttopic",
            name="group_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
