# Generated by Django 5.2.17 on 2026-09-21 19:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0003_eventedition_passport_identity_page_upload_enabled"),
        ("organizations", "0003_professionalaffiliation_biography_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset_kind",
                    models.CharField(
                        choices=[("REGISTRATIONS_SUMMARY", "Registrations summary")], max_length=32
                    ),
                ),
                ("schema_version", models.CharField(default="v1", max_length=16)),
                ("purpose_code", models.CharField(max_length=64)),
                ("reason", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("READY", "Ready"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                ("target_registration_ids", models.JSONField(blank=True, default=list)),
                ("row_count", models.PositiveIntegerField(blank=True, null=True)),
                ("storage_key", models.CharField(blank=True, default="", max_length=200)),
                ("content_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("retrieved_count", models.PositiveIntegerField(default=0)),
                ("last_retrieved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_requests",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_requests",
                        to="organizations.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exports_export_request",
                "indexes": [
                    models.Index(
                        fields=["event_edition", "status"], name="exp_request_event_status_idx"
                    )
                ],
            },
        ),
    ]
