# Generated by Django 5.2.17 on 2026-09-22 08:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accreditation", "0003_phase3_prompt2"),
        ("events", "0003_eventedition_passport_identity_page_upload_enabled"),
        ("people", "0002_identityverificationattempt"),
        ("registrations", "0006_alter_registration_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PassCredentialSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(max_length=22, unique=True)),
                ("fallback_reference", models.CharField(max_length=16, unique=True)),
                ("next_credential_version", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pass_series",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "db_table": "badges_pass_credential_series",
            },
        ),
        migrations.CreateModel(
            name="DigitalEntryPass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("credential_version", models.PositiveIntegerField()),
                ("jti", models.CharField(max_length=22, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INACTIVE", "Inactive"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                            ("REPLACED", "Replaced"),
                        ],
                        default="INACTIVE",
                        max_length=16,
                    ),
                ),
                ("event_code", models.CharField(max_length=32)),
                ("badge_type_code", models.CharField(max_length=64)),
                ("access_profile_code", models.CharField(max_length=64)),
                ("payload_version", models.PositiveSmallIntegerField()),
                ("signing_key_id", models.CharField(max_length=8)),
                ("payload_hash", models.CharField(max_length=64)),
                ("nonce", models.CharField(max_length=16)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("INITIAL_ISSUE", "Initial issue"),
                            ("REPLACEMENT_ISSUE", "Replacement issue"),
                            ("ASSIGNMENT_CHANGED", "Assignment changed"),
                            ("PARTICIPANT_REQUEST", "Participant request"),
                            ("SECURITY_CONCERN", "Security concern"),
                            ("ADMINISTRATIVE_ERROR", "Administrative error"),
                            ("LOST_OR_COMPROMISED", "Lost or compromised"),
                            ("REGISTRATION_CLOSED", "Registration closed"),
                            ("KEY_COMPROMISE", "Signing key compromise"),
                            ("VALIDITY_ENDED", "Validity period ended"),
                            ("OTHER_APPROVED", "Other approved reason"),
                        ],
                        default="INITIAL_ISSUE",
                        max_length=32,
                    ),
                ),
                ("reason_text", models.CharField(blank=True, default="", max_length=300)),
                (
                    "status_reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INITIAL_ISSUE", "Initial issue"),
                            ("REPLACEMENT_ISSUE", "Replacement issue"),
                            ("ASSIGNMENT_CHANGED", "Assignment changed"),
                            ("PARTICIPANT_REQUEST", "Participant request"),
                            ("SECURITY_CONCERN", "Security concern"),
                            ("ADMINISTRATIVE_ERROR", "Administrative error"),
                            ("LOST_OR_COMPROMISED", "Lost or compromised"),
                            ("REGISTRATION_CLOSED", "Registration closed"),
                            ("KEY_COMPROMISE", "Signing key compromise"),
                            ("VALIDITY_ENDED", "Validity period ended"),
                            ("OTHER_APPROVED", "Other approved reason"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("status_reason_text", models.CharField(blank=True, default="", max_length=300)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("resumed_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("replaced_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "access_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accreditation.accessprofileassignment",
                    ),
                ),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "badge_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accreditation.badgetypeassignment",
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entry_passes",
                        to="registrations.registration",
                    ),
                ),
                (
                    "replaced_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replaces",
                        to="badges.digitalentrypass",
                    ),
                ),
                (
                    "replaced_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resumed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accreditation.participantroleassignment",
                    ),
                ),
                (
                    "suspended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credentials",
                        to="badges.passcredentialseries",
                    ),
                ),
            ],
            options={
                "db_table": "badges_digital_entry_pass",
                "permissions": [
                    ("activate_digitalentrypass", "Can activate a Digital Entry Pass"),
                    ("suspend_digitalentrypass", "Can suspend a Digital Entry Pass"),
                    ("resume_digitalentrypass", "Can resume a suspended Digital Entry Pass"),
                    ("revoke_digitalentrypass", "Can revoke or replace a Digital Entry Pass"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PassLifecycleOperation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("operation_id", models.CharField(max_length=64, unique=True)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("GENERATE", "Generate"),
                            ("ACTIVATE", "Activate"),
                            ("SUSPEND", "Suspend"),
                            ("RESUME", "Resume"),
                            ("REVOKE", "Revoke"),
                            ("REPLACE", "Replace"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_pass",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="badges.digitalentrypass",
                    ),
                ),
                (
                    "resulting_pass",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="badges.digitalentrypass",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="badges.passcredentialseries",
                    ),
                ),
            ],
            options={
                "db_table": "badges_pass_lifecycle_operation",
            },
        ),
        migrations.CreateModel(
            name="VerificationKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key_id", models.CharField(max_length=8, unique=True)),
                ("algorithm", models.CharField(default="ES256", max_length=16)),
                ("public_key_pem", models.TextField()),
                ("public_key_fingerprint", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("RETIRED", "Retired"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("not_before", models.DateTimeField(blank=True, null=True)),
                ("not_after", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField()),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "revocation_reason_text",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "badges_verification_key",
                "permissions": [
                    (
                        "manage_verificationkey",
                        "Can publish, promote, retire and revoke verification keys",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ParticipantEventPseudonym",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pseudonym", models.CharField(max_length=22, unique=True)),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "badges_participant_event_pseudonym",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "event_edition"), name="bdg_pseudonym_person_event_uq"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="passcredentialseries",
            constraint=models.UniqueConstraint(
                fields=("registration",), name="bdg_series_registration_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="passcredentialseries",
            constraint=models.UniqueConstraint(
                fields=("public_id",), name="bdg_series_public_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="passcredentialseries",
            constraint=models.UniqueConstraint(
                fields=("fallback_reference",), name="bdg_series_fallback_ref_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="passcredentialseries",
            constraint=models.CheckConstraint(
                condition=models.Q(("next_credential_version__gte", 1)),
                name="bdg_series_next_version_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="digitalentrypass",
            index=models.Index(fields=["registration", "status"], name="bdg_pass_reg_status_idx"),
        ),
        migrations.AddIndex(
            model_name="digitalentrypass",
            index=models.Index(
                fields=["series", "credential_version"], name="bdg_pass_series_ver_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="digitalentrypass",
            index=models.Index(
                fields=["event_edition", "status", "valid_until"], name="bdg_pass_event_valid_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="digitalentrypass",
            index=models.Index(fields=["signing_key_id"], name="bdg_pass_signing_key_idx"),
        ),
        migrations.AddConstraint(
            model_name="digitalentrypass",
            constraint=models.UniqueConstraint(
                fields=("series", "credential_version"), name="bdg_pass_series_credver_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="digitalentrypass",
            constraint=models.UniqueConstraint(fields=("jti",), name="bdg_pass_jti_uq"),
        ),
        migrations.AddConstraint(
            model_name="digitalentrypass",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("INACTIVE", "ACTIVE", "SUSPENDED"))),
                fields=("registration",),
                name="bdg_pass_one_current_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="digitalentrypass",
            constraint=models.CheckConstraint(
                condition=models.Q(("valid_until__gt", models.F("valid_from"))),
                name="bdg_pass_valid_range_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="digitalentrypass",
            constraint=models.CheckConstraint(
                condition=models.Q(("credential_version__gte", 1)),
                name="bdg_pass_credver_positive_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="digitalentrypass",
            constraint=models.CheckConstraint(
                condition=models.Q(("payload_version__gte", 1)), name="bdg_pass_payload_version_ck"
            ),
        ),
        migrations.AddIndex(
            model_name="passlifecycleoperation",
            index=models.Index(fields=["series", "created_at"], name="bdg_pass_op_series_idx"),
        ),
        migrations.AddConstraint(
            model_name="passlifecycleoperation",
            constraint=models.UniqueConstraint(
                fields=("operation_id",), name="bdg_pass_operation_id_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationkey",
            index=models.Index(fields=["status", "not_before"], name="bdg_verifkey_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="verificationkey",
            constraint=models.UniqueConstraint(fields=("key_id",), name="bdg_verifkey_key_id_uq"),
        ),
        migrations.AddConstraint(
            model_name="verificationkey",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("algorithm",),
                name="bdg_verifkey_one_active_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationkey",
            constraint=models.CheckConstraint(
                condition=models.Q(("algorithm", "ES256")), name="bdg_verifkey_es256_only"
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationkey",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("not_after__isnull", True),
                    ("not_before__isnull", True),
                    ("not_after__gt", models.F("not_before")),
                    _connector="OR",
                ),
                name="bdg_verifkey_window_ck",
            ),
        ),
    ]
