# Generated by Django 5.2.17 on 2026-09-22 16:22

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accreditation", "0004_phase3_prompt2_corrections"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("badges", "0002_phase3_prompt2_corrections"),
        ("events", "0003_eventedition_passport_identity_page_upload_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=200)),
                ("name_fr", models.CharField(blank=True, default="", max_length=200)),
                ("name_ar", models.CharField(blank=True, default="", max_length=200)),
                (
                    "location_type",
                    models.CharField(
                        choices=[("CENTRAL", "Central store"), ("CHECKPOINT", "Checkpoint")],
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "custodian_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="auth.group",
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_locations",
                        to="events.eventedition",
                    ),
                ),
            ],
            options={
                "db_table": "badges_stock_location",
                "permissions": [("manage_stocklocation", "Can create and manage stock locations")],
            },
        ),
        migrations.CreateModel(
            name="PrintBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("public_reference", models.CharField(max_length=22, unique=True)),
                ("artwork_version", models.CharField(blank=True, default="", max_length=32)),
                ("planned_quantity", models.PositiveIntegerField()),
                ("produced_quantity", models.PositiveIntegerField(default=0)),
                ("accepted_quantity", models.PositiveIntegerField(default=0)),
                ("damaged_quantity", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY", "Ready for production"),
                            ("IN_PRODUCTION", "In production"),
                            ("RECEIVED", "Received"),
                            ("RECONCILED", "Reconciled"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("supplier_reference", models.CharField(blank=True, default="", max_length=200)),
                ("production_started_at", models.DateTimeField(blank=True, null=True)),
                ("production_completed_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "badge_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accreditation.badgetype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="The stock location the accepted quantity is receipted into.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_batches",
                        to="badges.stocklocation",
                    ),
                ),
            ],
            options={
                "db_table": "badges_print_batch",
                "permissions": [
                    ("manage_printbatch", "Can create, plan, and cancel print batches"),
                    ("receive_printbatch", "Can record production receipt for a print batch"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BadgeStockBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "badge_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accreditation.badgetype",
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balances",
                        to="badges.stocklocation",
                    ),
                ),
            ],
            options={
                "db_table": "badges_stock_balance",
            },
        ),
        migrations.CreateModel(
            name="BadgeIssuance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ISSUED", "Issued"),
                            ("REPLACED", "Replaced"),
                            ("RETURNED", "Returned"),
                            ("LOST", "Reported lost"),
                            ("VOIDED", "Voided"),
                        ],
                        default="ISSUED",
                        max_length=16,
                    ),
                ),
                ("optional_serial_number", models.CharField(blank=True, default="", max_length=64)),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("INITIAL_HANDOVER", "Initial handover"),
                            ("WRONG_BADGE_TYPE", "Wrong badge type issued"),
                            ("DAMAGED_BADGE", "Physical badge damaged"),
                            ("LOST_BADGE", "Physical badge lost"),
                            ("PARTICIPANT_REQUEST", "Participant request"),
                            ("EVENT_CONCLUDED", "Returned at end of event"),
                            ("ADMINISTRATIVE_ERROR", "Administrative error"),
                            ("OTHER_APPROVED", "Other approved reason"),
                        ],
                        default="INITIAL_HANDOVER",
                        max_length=32,
                    ),
                ),
                ("reason_text", models.CharField(blank=True, default="", max_length=300)),
                (
                    "status_reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INITIAL_HANDOVER", "Initial handover"),
                            ("WRONG_BADGE_TYPE", "Wrong badge type issued"),
                            ("DAMAGED_BADGE", "Physical badge damaged"),
                            ("LOST_BADGE", "Physical badge lost"),
                            ("PARTICIPANT_REQUEST", "Participant request"),
                            ("EVENT_CONCLUDED", "Returned at end of event"),
                            ("ADMINISTRATIVE_ERROR", "Administrative error"),
                            ("OTHER_APPROVED", "Other approved reason"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("status_reason_text", models.CharField(blank=True, default="", max_length=300)),
                ("issued_at", models.DateTimeField()),
                ("replaced_at", models.DateTimeField(blank=True, null=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("lost_reported_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "badge_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accreditation.badgetypeassignment",
                    ),
                ),
                (
                    "badge_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accreditation.badgetype",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lost_reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replaced_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replaces",
                        to="badges.badgeissuance",
                    ),
                ),
                (
                    "replaced_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "returned_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issuances",
                        to="badges.stocklocation",
                    ),
                ),
            ],
            options={
                "db_table": "badges_badge_issuance",
                "permissions": [
                    ("issue_badgeissuance", "Can issue and replace a physical badge"),
                    ("return_badgeissuance", "Can record a badge return, loss, or void"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("expected_quantity_at_count", models.IntegerField()),
                ("counted_quantity", models.PositiveIntegerField()),
                ("discrepancy", models.IntegerField()),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accreditation.badgetype",
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="badges.stocklocation",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "badges_stock_reconciliation",
                "permissions": [
                    ("reconcile_badgestock", "Can record a badge stock reconciliation count")
                ],
            },
        ),
        migrations.CreateModel(
            name="BadgeStockLedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("operation_id", models.CharField(max_length=64, unique=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("RECEIVE", "Receive"),
                            ("TRANSFER_OUT", "Transfer out"),
                            ("TRANSFER_IN", "Transfer in"),
                            ("ISSUE", "Issue"),
                            ("RETURN", "Return"),
                            ("ADJUSTMENT", "Reasoned adjustment"),
                            ("RECONCILIATION", "Reconciliation"),
                        ],
                        max_length=16,
                    ),
                ),
                ("quantity_delta", models.IntegerField()),
                (
                    "reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAMAGED_IN_STOCK", "Damaged while in stock"),
                            ("COUNT_CORRECTION", "Manual count correction"),
                            ("ADMINISTRATIVE_ERROR", "Administrative error"),
                            ("OTHER_APPROVED", "Other approved reason"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("reason_text", models.CharField(blank=True, default="", max_length=300)),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accreditation.badgetype",
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "issuance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="badges.badgeissuance",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "print_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="badges.printbatch",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="badges.stocklocation",
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="badges.stockreconciliation",
                    ),
                ),
            ],
            options={
                "db_table": "badges_stock_ledger_entry",
            },
        ),
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "Completed"), ("CANCELLED", "Cancelled")],
                        default="COMPLETED",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("completed_at", models.DateTimeField()),
                (
                    "badge_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accreditation.badgetype",
                    ),
                ),
                (
                    "destination_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="badges.stocklocation",
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="badges.stocklocation",
                    ),
                ),
            ],
            options={
                "db_table": "badges_stock_transfer",
                "permissions": [
                    ("transfer_badgestock", "Can transfer badge stock between locations")
                ],
            },
        ),
        migrations.CreateModel(
            name="BadgeStockOperation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("operation_id", models.CharField(max_length=64, unique=True)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("LOCATION_CREATE", "Create stock location"),
                            ("BATCH_CREATE", "Create print batch"),
                            ("BATCH_STATUS_CHANGE", "Change print batch status"),
                            ("BATCH_RECEIVE", "Receive print batch"),
                            ("TRANSFER", "Transfer stock"),
                            ("ISSUE", "Issue badge"),
                            ("REPLACE_ISSUANCE", "Replace issued badge"),
                            ("RETURN_ISSUANCE", "Return issued badge"),
                            ("MARK_LOST", "Mark issued badge lost"),
                            ("VOID_ISSUANCE", "Void issuance"),
                            ("ADJUSTMENT", "Reasoned stock adjustment"),
                            ("RECONCILIATION", "Record stock reconciliation"),
                        ],
                        max_length=24,
                    ),
                ),
                ("command_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("target_type", models.CharField(blank=True, default="", max_length=32)),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issuance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="badges.badgeissuance",
                    ),
                ),
                (
                    "ledger_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="badges.badgestockledgerentry",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "print_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="badges.printbatch",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="badges.stocklocation",
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="badges.stockreconciliation",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="badges.stocktransfer",
                    ),
                ),
            ],
            options={
                "db_table": "badges_stock_operation",
            },
        ),
        migrations.AddField(
            model_name="badgestockledgerentry",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="badges.stocktransfer",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocation",
            constraint=models.UniqueConstraint(
                fields=("event_edition", "code"), name="bdg_stockloc_event_code_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="printbatch",
            index=models.Index(fields=["event_edition", "status"], name="bdg_printbatch_event_idx"),
        ),
        migrations.AddIndex(
            model_name="printbatch",
            index=models.Index(fields=["badge_type"], name="bdg_printbatch_badgetype_idx"),
        ),
        migrations.AddConstraint(
            model_name="printbatch",
            constraint=models.UniqueConstraint(
                fields=("public_reference",), name="bdg_printbatch_ref_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="printbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("planned_quantity__gte", 1)),
                name="bdg_printbatch_planned_positive_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="printbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ["RECEIVED", "RECONCILED", "CLOSED"]), _negated=True),
                    (
                        "produced_quantity",
                        django.db.models.expressions.CombinedExpression(
                            models.F("accepted_quantity"), "+", models.F("damaged_quantity")
                        ),
                    ),
                    _connector="OR",
                ),
                name="bdg_printbatch_receipt_balances_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="badgestockbalance",
            constraint=models.UniqueConstraint(
                fields=("event_edition", "badge_type", "location"), name="bdg_balance_scope_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="badgestockbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="bdg_balance_nonneg_ck"
            ),
        ),
        migrations.AddIndex(
            model_name="badgeissuance",
            index=models.Index(
                fields=["badge_assignment", "status"], name="bdg_issuance_assign_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="badgeissuance",
            index=models.Index(fields=["location", "status"], name="bdg_issuance_location_idx"),
        ),
        migrations.AddConstraint(
            model_name="badgeissuance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ISSUED")),
                fields=("badge_assignment",),
                name="bdg_issuance_one_current_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="stockreconciliation",
            index=models.Index(
                fields=["event_edition", "badge_type", "location", "recorded_at"],
                name="bdg_reconciliation_scope_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["event_edition", "badge_type"], name="bdg_transfer_event_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="bdg_transfer_qty_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_location", models.F("destination_location")), _negated=True
                ),
                name="bdg_transfer_distinct_locations_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="badgestockoperation",
            index=models.Index(fields=["target_type", "target_id"], name="bdg_stockop_target_idx"),
        ),
        migrations.AddConstraint(
            model_name="badgestockoperation",
            constraint=models.UniqueConstraint(
                fields=("operation_id",), name="bdg_stockop_operation_id_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="badgestockledgerentry",
            index=models.Index(
                fields=["event_edition", "badge_type", "location"], name="bdg_ledger_balance_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="badgestockledgerentry",
            index=models.Index(fields=["recorded_at"], name="bdg_ledger_recorded_idx"),
        ),
        migrations.AddConstraint(
            model_name="badgestockledgerentry",
            constraint=models.UniqueConstraint(
                fields=("operation_id",), name="bdg_ledger_operation_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="badgestockledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_delta", 0), _negated=True),
                name="bdg_ledger_qty_nonzero_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="badgestockledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("entry_type", "RECEIVE"),
                        ("issuance__isnull", True),
                        ("print_batch__isnull", False),
                        ("reconciliation__isnull", True),
                        ("transfer__isnull", True),
                    ),
                    models.Q(
                        ("entry_type__in", ["TRANSFER_OUT", "TRANSFER_IN"]),
                        ("issuance__isnull", True),
                        ("print_batch__isnull", True),
                        ("reconciliation__isnull", True),
                        ("transfer__isnull", False),
                    ),
                    models.Q(
                        ("entry_type__in", ["ISSUE", "RETURN"]),
                        ("issuance__isnull", False),
                        ("print_batch__isnull", True),
                        ("reconciliation__isnull", True),
                        ("transfer__isnull", True),
                    ),
                    models.Q(
                        ("entry_type", "RECONCILIATION"),
                        ("issuance__isnull", True),
                        ("print_batch__isnull", True),
                        ("reconciliation__isnull", False),
                        ("transfer__isnull", True),
                    ),
                    models.Q(
                        ("entry_type", "ADJUSTMENT"),
                        ("issuance__isnull", True),
                        ("print_batch__isnull", True),
                        ("reconciliation__isnull", True),
                        ("transfer__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="bdg_ledger_entry_type_reference_ck",
            ),
        ),
    ]
