# Generated by Django 5.2.17 on 2026-09-22 18:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_issuance_registration(apps, schema_editor):
    """Fill `BadgeIssuance.registration` from its assignment.

    Runs BEFORE `bdg_issuance_one_current_per_reg_uq` is installed, so the
    new "one current physical badge per Registration Context" rule actually
    covers rows that already existed rather than silently exempting them
    through the constraint's `registration__isnull=False` condition.
    Idempotent: only rows whose column is still NULL are touched.
    """
    BadgeIssuance = apps.get_model("badges", "BadgeIssuance")
    for issuance in BadgeIssuance.objects.filter(registration__isnull=True).select_related(
        "badge_assignment"
    ):
        issuance.registration_id = issuance.badge_assignment.registration_id
        issuance.save(update_fields=["registration"])


def clear_issuance_registration(apps, schema_editor):
    """Reverse of the backfill: blank the column so the field can be dropped."""
    BadgeIssuance = apps.get_model("badges", "BadgeIssuance")
    BadgeIssuance.objects.update(registration=None)


class Migration(migrations.Migration):
    dependencies = [
        ("accreditation", "0004_phase3_prompt2_corrections"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("badges", "0003_phase3_prompt3"),
        ("events", "0003_eventedition_passport_identity_page_upload_enabled"),
        ("registrations", "0006_alter_registration_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeStockAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("quantity", models.PositiveIntegerField()),
                ("consumed_quantity", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CONSUMED", "Fully consumed"),
                            ("RELEASED", "Released"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "purpose_code",
                    models.CharField(
                        choices=[
                            ("CHECKPOINT_OPENING", "Checkpoint opening stock"),
                            ("SHIFT_RESERVE", "Shift reserve"),
                            ("ORGANIZATION_DELEGATION", "Delegation collection"),
                            ("PROTOCOL_RESERVE", "Protocol reserve"),
                            ("OPERATIONAL_BUFFER", "Operational buffer"),
                            ("OTHER_APPROVED", "Other approved purpose"),
                        ],
                        max_length=32,
                    ),
                ),
                ("purpose_text", models.CharField(blank=True, default="", max_length=300)),
                ("allocated_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("release_reason_text", models.CharField(blank=True, default="", max_length=300)),
            ],
            options={
                "db_table": "badges_stock_allocation",
                "permissions": [
                    ("allocate_badgestock", "Can allocate and release reserved badge stock")
                ],
            },
        ),
        migrations.AddField(
            model_name="badgeissuance",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="registrations.registration",
            ),
        ),
        migrations.AddField(
            model_name="badgestockbalance",
            name="reserved_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="badgestockoperation",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("LOCATION_CREATE", "Create stock location"),
                    ("BATCH_CREATE", "Create print batch"),
                    ("BATCH_STATUS_CHANGE", "Change print batch status"),
                    ("BATCH_RECEIVE", "Receive print batch"),
                    ("TRANSFER", "Transfer stock"),
                    ("ALLOCATE", "Allocate stock"),
                    ("RELEASE_ALLOCATION", "Release stock allocation"),
                    ("ISSUE", "Issue badge"),
                    ("REPLACE_ISSUANCE", "Replace issued badge"),
                    ("RETURN_ISSUANCE", "Return issued badge"),
                    ("MARK_LOST", "Mark issued badge lost"),
                    ("VOID_ISSUANCE", "Void issuance"),
                    ("ADJUSTMENT", "Reasoned stock adjustment"),
                    ("RECONCILIATION", "Record stock reconciliation"),
                ],
                max_length=24,
            ),
        ),
        migrations.RunPython(
            backfill_issuance_registration,
            reverse_code=clear_issuance_registration,
            elidable=False,
        ),
        migrations.AddIndex(
            model_name="badgeissuance",
            index=models.Index(fields=["registration", "status"], name="bdg_issuance_reg_idx"),
        ),
        migrations.AddConstraint(
            model_name="badgeissuance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("registration__isnull", False), ("status", "ISSUED")),
                fields=("registration",),
                name="bdg_issuance_one_current_per_reg_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="badgestockbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__gte", 0)),
                name="bdg_balance_reserved_nonneg_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="badgestockbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__lte", models.F("quantity"))),
                name="bdg_balance_reserved_within_onhand_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="badgestockledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("entry_type__in", ["RECEIVE", "TRANSFER_IN", "RETURN"]), _negated=True
                    ),
                    ("quantity_delta__gt", 0),
                    _connector="OR",
                ),
                name="bdg_ledger_positive_direction_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="badgestockledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("entry_type__in", ["TRANSFER_OUT", "ISSUE"]), _negated=True),
                    ("quantity_delta__lt", 0),
                    _connector="OR",
                ),
                name="bdg_ledger_negative_direction_ck",
            ),
        ),
        migrations.AddField(
            model_name="badgestockallocation",
            name="allocated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="badgestockallocation",
            name="badge_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accreditation.badgetype",
            ),
        ),
        migrations.AddField(
            model_name="badgestockallocation",
            name="event_edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="badgestockallocation",
            name="held_for_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="badgestockallocation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="badges.stocklocation",
            ),
        ),
        migrations.AddField(
            model_name="badgestockallocation",
            name="released_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="badgestockoperation",
            name="allocation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="badges.badgestockallocation",
            ),
        ),
        migrations.AddIndex(
            model_name="badgestockallocation",
            index=models.Index(
                fields=["event_edition", "badge_type", "location", "status"],
                name="bdg_allocation_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="badgestockallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="bdg_allocation_qty_positive_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="badgestockallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("consumed_quantity__lte", models.F("quantity"))),
                name="bdg_allocation_consumed_within_qty_ck",
            ),
        ),
        # The stock ledger is append-only in the same enforceable sense
        # `audit_event` already is (ADR-0008, `audit/0001_initial`): a
        # `BEFORE UPDATE OR DELETE` trigger refuses the statement in the
        # database, not only in application code, so a stray `.update()`,
        # `.delete()`, admin action, or hand-typed SQL cannot rewrite
        # recorded stock history. As with the audit trigger, the owning
        # local role can still drop it, which is why real database-role
        # isolation stays a separately verified deployment fact and is
        # never claimed here.
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION badges_stock_ledger_block_update_delete()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION
                        'badges_stock_ledger_entry rows are append-only: % is not permitted',
                        TG_OP;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER badges_stock_ledger_prevent_update_delete
                BEFORE UPDATE OR DELETE ON badges_stock_ledger_entry
                FOR EACH ROW EXECUTE FUNCTION badges_stock_ledger_block_update_delete();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS badges_stock_ledger_prevent_update_delete
                    ON badges_stock_ledger_entry;
                DROP FUNCTION IF EXISTS badges_stock_ledger_block_update_delete();
            """,
        ),
    ]
