# Generated by Django 5.2.17 on 2026-09-22 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0004_phase3_prompt3_corrections"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stocklocation",
            options={
                "permissions": [
                    ("manage_stocklocation", "Can create and manage stock locations"),
                    ("view_stockaccounting", "Can view the badge stock accounting dashboard"),
                ]
            },
        ),
    ]
