# Generated by Django 5.2.17 on 2026-09-22

import django.db.models.deletion
from django.db import migrations, models


def backfill_any_late_null_registrations(apps, schema_editor):
    """Close rows written while the additive 0004 field was still nullable."""
    BadgeIssuance = apps.get_model("badges", "BadgeIssuance")
    queryset = BadgeIssuance.objects.filter(registration__isnull=True).select_related(
        "badge_assignment"
    )
    for issuance in queryset.iterator():
        issuance.registration_id = issuance.badge_assignment.registration_id
        issuance.save(update_fields=["registration"])


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0005_phase3_prompt3_accounting_permission"),
    ]

    operations = [
        migrations.RunPython(
            backfill_any_late_null_registrations,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="badgeissuance",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="registrations.registration",
            ),
        ),
    ]
