# Generated by Django 5.2.17 on 2026-10-06 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0006_badgeissuance_registration_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="badgeissuance",
            name="attendance_marking",
            field=models.CharField(blank=True, db_default="", default="", max_length=24),
        ),
        migrations.AddField(
            model_name="badgeissuance",
            name="attendance_marking_recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badgeissuance",
            name="attendance_marking_recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
