"""Owner-approved country and territory catalog, version 1 (C-01, 2026-10-04).

FROZEN DATA: never edit this module. A later catalog is a new module and a new
reviewed migration, so the migration that installed this version keeps
installing exactly this data on a fresh database.

Source: the owner-supplied file `ASC2026_STAGING_COUNTRIES (1).sql` (SHA-256
`3c82fc8c4e5061fa8441f465738ceb2b4b1c8e9b1274f00f5fbb9cc1ef2728ca`), which states:
codes from the pycountry 24.6.1 ISO 3166-1 snapshot, display names from
Babel 2.17.0 / Unicode CLDR, territories included, IL and XK excluded, and
the owner-requested Palestine labels for PS. Every `(code, English, French,
Arabic)` row below is copied from that file unchanged (248 rows). The SQL
itself is not used: it only inserted missing rows (`ON CONFLICT DO
NOTHING`), so it never reconciled labels or inactive approved rows.

The catalog decides which countries can be selected. It decides nothing about
nationality, residence or identity-document policy.
"""

from __future__ import annotations

CATALOG_VERSION = "countries-v1"
APPROVED_ON = "2026-10-04"
SOURCE_FILE = "ASC2026_STAGING_COUNTRIES (1).sql"
SOURCE_SHA256 = "3c82fc8c4e5061fa8441f465738ceb2b4b1c8e9b1274f00f5fbb9cc1ef2728ca"

#: Never selectable, even when a row exists (kept for history, never deleted).
EXCLUDED_CODES = ("IL", "XK")

#: SHA-256 of `json.dumps(ENTRIES, ensure_ascii=False)`; a test pins it.
ENTRIES_SHA256 = "03feb7e17c866d1f07cba1bb4b0a0ebc29a5dfdd9924cead72482dcf3db21609"

#: (ISO 3166-1 alpha-2 code, English, French, Arabic), sorted by code.
ENTRIES: tuple[tuple[str, str, str, str], ...] = (
    ("AD", "Andorra", "Andorre", "أندورا"),
    ("AE", "United Arab Emirates", "Émirats arabes unis", "الإمارات العربية المتحدة"),
    ("AF", "Afghanistan", "Afghanistan", "أفغانستان"),
    ("AG", "Antigua & Barbuda", "Antigua-et-Barbuda", "أنتيغوا وبربودا"),
    ("AI", "Anguilla", "Anguilla", "أنغويلا"),
    ("AL", "Albania", "Albanie", "ألبانيا"),
    ("AM", "Armenia", "Arménie", "أرمينيا"),
    ("AO", "Angola", "Angola", "أنغولا"),
    ("AQ", "Antarctica", "Antarctique", "أنتاركتيكا"),
    ("AR", "Argentina", "Argentine", "الأرجنتين"),
    ("AS", "American Samoa", "Samoa américaines", "ساموا الأمريكية"),
    ("AT", "Austria", "Autriche", "النمسا"),
    ("AU", "Australia", "Australie", "أستراليا"),
    ("AW", "Aruba", "Aruba", "أروبا"),
    ("AX", "Åland Islands", "Îles Åland", "جزر آلاند"),
    ("AZ", "Azerbaijan", "Azerbaïdjan", "أذربيجان"),
    ("BA", "Bosnia & Herzegovina", "Bosnie-Herzégovine", "البوسنة والهرسك"),
    ("BB", "Barbados", "Barbade", "بربادوس"),
    ("BD", "Bangladesh", "Bangladesh", "بنغلاديش"),
    ("BE", "Belgium", "Belgique", "بلجيكا"),
    ("BF", "Burkina Faso", "Burkina Faso", "بوركينا فاسو"),
    ("BG", "Bulgaria", "Bulgarie", "بلغاريا"),
    ("BH", "Bahrain", "Bahreïn", "البحرين"),
    ("BI", "Burundi", "Burundi", "بوروندي"),
    ("BJ", "Benin", "Bénin", "بنين"),
    ("BL", "St. Barthélemy", "Saint-Barthélemy", "سان بارتليمي"),
    ("BM", "Bermuda", "Bermudes", "برمودا"),
    ("BN", "Brunei", "Brunei", "بروناي"),
    ("BO", "Bolivia", "Bolivie", "بوليفيا"),
    ("BQ", "Caribbean Netherlands", "Pays-Bas caribéens", "هولندا الكاريبية"),
    ("BR", "Brazil", "Brésil", "البرازيل"),
    ("BS", "Bahamas", "Bahamas", "جزر البهاما"),
    ("BT", "Bhutan", "Bhoutan", "بوتان"),
    ("BV", "Bouvet Island", "Île Bouvet", "جزيرة بوفيه"),
    ("BW", "Botswana", "Botswana", "بوتسوانا"),
    ("BY", "Belarus", "Biélorussie", "بيلاروس"),
    ("BZ", "Belize", "Belize", "بليز"),
    ("CA", "Canada", "Canada", "كندا"),
    ("CC", "Cocos (Keeling) Islands", "Îles Cocos", "جزر كوكوس (كيلينغ)"),
    ("CD", "Congo - Kinshasa", "Congo-Kinshasa", "الكونغو - كينشاسا"),
    ("CF", "Central African Republic", "République centrafricaine", "جمهورية أفريقيا الوسطى"),
    ("CG", "Congo - Brazzaville", "Congo-Brazzaville", "الكونغو - برازافيل"),
    ("CH", "Switzerland", "Suisse", "سويسرا"),
    ("CI", "Côte d’Ivoire", "Côte d’Ivoire", "ساحل العاج"),
    ("CK", "Cook Islands", "Îles Cook", "جزر كوك"),
    ("CL", "Chile", "Chili", "تشيلي"),
    ("CM", "Cameroon", "Cameroun", "الكاميرون"),
    ("CN", "China", "Chine", "الصين"),
    ("CO", "Colombia", "Colombie", "كولومبيا"),
    ("CR", "Costa Rica", "Costa Rica", "كوستاريكا"),
    ("CU", "Cuba", "Cuba", "كوبا"),
    ("CV", "Cape Verde", "Cap-Vert", "الرأس الأخضر"),
    ("CW", "Curaçao", "Curaçao", "كوراساو"),
    ("CX", "Christmas Island", "Île Christmas", "جزيرة كريسماس"),
    ("CY", "Cyprus", "Chypre", "قبرص"),
    ("CZ", "Czechia", "Tchéquie", "التشيك"),
    ("DE", "Germany", "Allemagne", "ألمانيا"),
    ("DJ", "Djibouti", "Djibouti", "جيبوتي"),
    ("DK", "Denmark", "Danemark", "الدانمرك"),
    ("DM", "Dominica", "Dominique", "دومينيكا"),
    ("DO", "Dominican Republic", "République dominicaine", "جمهورية الدومينيكان"),
    ("DZ", "Algeria", "Algérie", "الجزائر"),
    ("EC", "Ecuador", "Équateur", "الإكوادور"),
    ("EE", "Estonia", "Estonie", "إستونيا"),
    ("EG", "Egypt", "Égypte", "مصر"),
    ("EH", "Western Sahara", "Sahara occidental", "الصحراء الغربية"),
    ("ER", "Eritrea", "Érythrée", "إريتريا"),
    ("ES", "Spain", "Espagne", "إسبانيا"),
    ("ET", "Ethiopia", "Éthiopie", "إثيوبيا"),
    ("FI", "Finland", "Finlande", "فنلندا"),
    ("FJ", "Fiji", "Fidji", "فيجي"),
    ("FK", "Falkland Islands", "Îles Malouines", "جزر فوكلاند"),
    ("FM", "Micronesia", "Micronésie", "ميكرونيزيا"),
    ("FO", "Faroe Islands", "Îles Féroé", "جزر فارو"),
    ("FR", "France", "France", "فرنسا"),
    ("GA", "Gabon", "Gabon", "الغابون"),
    ("GB", "United Kingdom", "Royaume-Uni", "المملكة المتحدة"),
    ("GD", "Grenada", "Grenade", "غرينادا"),
    ("GE", "Georgia", "Géorgie", "جورجيا"),
    ("GF", "French Guiana", "Guyane française", "غويانا الفرنسية"),
    ("GG", "Guernsey", "Guernesey", "غيرنزي"),
    ("GH", "Ghana", "Ghana", "غانا"),
    ("GI", "Gibraltar", "Gibraltar", "جبل طارق"),
    ("GL", "Greenland", "Groenland", "غرينلاند"),
    ("GM", "Gambia", "Gambie", "غامبيا"),
    ("GN", "Guinea", "Guinée", "غينيا"),
    ("GP", "Guadeloupe", "Guadeloupe", "غوادلوب"),
    ("GQ", "Equatorial Guinea", "Guinée équatoriale", "غينيا الاستوائية"),
    ("GR", "Greece", "Grèce", "اليونان"),
    (
        "GS",
        "South Georgia & South Sandwich Islands",
        "Géorgie du Sud-et-les Îles Sandwich du Sud",
        "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
    ),
    ("GT", "Guatemala", "Guatemala", "غواتيمالا"),
    ("GU", "Guam", "Guam", "غوام"),
    ("GW", "Guinea-Bissau", "Guinée-Bissau", "غينيا بيساو"),
    ("GY", "Guyana", "Guyana", "غيانا"),
    (
        "HK",
        "Hong Kong SAR China",
        "R.A.S. chinoise de Hong Kong",
        "هونغ كونغ الصينية (منطقة إدارية خاصة)",
    ),
    ("HM", "Heard & McDonald Islands", "Îles Heard-et-MacDonald", "جزيرة هيرد وجزر ماكدونالد"),
    ("HN", "Honduras", "Honduras", "هندوراس"),
    ("HR", "Croatia", "Croatie", "كرواتيا"),
    ("HT", "Haiti", "Haïti", "هايتي"),
    ("HU", "Hungary", "Hongrie", "هنغاريا"),
    ("ID", "Indonesia", "Indonésie", "إندونيسيا"),
    ("IE", "Ireland", "Irlande", "أيرلندا"),
    ("IM", "Isle of Man", "Île de Man", "جزيرة مان"),
    ("IN", "India", "Inde", "الهند"),
    (
        "IO",
        "British Indian Ocean Territory",
        "Territoire britannique de l’océan Indien",
        "الإقليم البريطاني في المحيط الهندي",
    ),
    ("IQ", "Iraq", "Irak", "العراق"),
    ("IR", "Iran", "Iran", "إيران"),
    ("IS", "Iceland", "Islande", "آيسلندا"),
    ("IT", "Italy", "Italie", "إيطاليا"),
    ("JE", "Jersey", "Jersey", "جيرسي"),
    ("JM", "Jamaica", "Jamaïque", "جامايكا"),
    ("JO", "Jordan", "Jordanie", "الأردن"),
    ("JP", "Japan", "Japon", "اليابان"),
    ("KE", "Kenya", "Kenya", "كينيا"),
    ("KG", "Kyrgyzstan", "Kirghizstan", "قيرغيزستان"),
    ("KH", "Cambodia", "Cambodge", "كمبوديا"),
    ("KI", "Kiribati", "Kiribati", "كيريباتي"),
    ("KM", "Comoros", "Comores", "جزر القمر"),
    ("KN", "St. Kitts & Nevis", "Saint-Christophe-et-Niévès", "سانت كيتس ونيفيس"),
    ("KP", "North Korea", "Corée du Nord", "كوريا الشمالية"),
    ("KR", "South Korea", "Corée du Sud", "كوريا الجنوبية"),
    ("KW", "Kuwait", "Koweït", "الكويت"),
    ("KY", "Cayman Islands", "Îles Caïmans", "جزر كايمان"),
    ("KZ", "Kazakhstan", "Kazakhstan", "كازاخستان"),
    ("LA", "Laos", "Laos", "لاوس"),
    ("LB", "Lebanon", "Liban", "لبنان"),
    ("LC", "St. Lucia", "Sainte-Lucie", "سانت لوسيا"),
    ("LI", "Liechtenstein", "Liechtenstein", "ليختنشتاين"),
    ("LK", "Sri Lanka", "Sri Lanka", "سريلانكا"),
    ("LR", "Liberia", "Liberia", "ليبيريا"),
    ("LS", "Lesotho", "Lesotho", "ليسوتو"),
    ("LT", "Lithuania", "Lituanie", "ليتوانيا"),
    ("LU", "Luxembourg", "Luxembourg", "لوكسمبورغ"),
    ("LV", "Latvia", "Lettonie", "لاتفيا"),
    ("LY", "Libya", "Libye", "ليبيا"),
    ("MA", "Morocco", "Maroc", "المغرب"),
    ("MC", "Monaco", "Monaco", "موناكو"),
    ("MD", "Moldova", "Moldavie", "مولدوفا"),
    ("ME", "Montenegro", "Monténégro", "الجبل الأسود"),
    ("MF", "St. Martin", "Saint-Martin", "سان مارتن"),
    ("MG", "Madagascar", "Madagascar", "مدغشقر"),
    ("MH", "Marshall Islands", "Îles Marshall", "جزر مارشال"),
    ("MK", "North Macedonia", "Macédoine du Nord", "مقدونيا الشمالية"),
    ("ML", "Mali", "Mali", "مالي"),
    ("MM", "Myanmar (Burma)", "Myanmar (Birmanie)", "ميانمار (بورما)"),
    ("MN", "Mongolia", "Mongolie", "منغوليا"),
    ("MO", "Macao SAR China", "R.A.S. chinoise de Macao", "منطقة ماكاو الإدارية الخاصة"),
    ("MP", "Northern Mariana Islands", "Îles Mariannes du Nord", "جزر ماريانا الشمالية"),
    ("MQ", "Martinique", "Martinique", "جزر المارتينيك"),
    ("MR", "Mauritania", "Mauritanie", "موريتانيا"),
    ("MS", "Montserrat", "Montserrat", "مونتسرات"),
    ("MT", "Malta", "Malte", "مالطا"),
    ("MU", "Mauritius", "Maurice", "موريشيوس"),
    ("MV", "Maldives", "Maldives", "جزر المالديف"),
    ("MW", "Malawi", "Malawi", "ملاوي"),
    ("MX", "Mexico", "Mexique", "المكسيك"),
    ("MY", "Malaysia", "Malaisie", "ماليزيا"),
    ("MZ", "Mozambique", "Mozambique", "موزمبيق"),
    ("NA", "Namibia", "Namibie", "ناميبيا"),
    ("NC", "New Caledonia", "Nouvelle-Calédonie", "كاليدونيا الجديدة"),
    ("NE", "Niger", "Niger", "النيجر"),
    ("NF", "Norfolk Island", "Île Norfolk", "جزيرة نورفولك"),
    ("NG", "Nigeria", "Nigeria", "نيجيريا"),
    ("NI", "Nicaragua", "Nicaragua", "نيكاراغوا"),
    ("NL", "Netherlands", "Pays-Bas", "هولندا"),
    ("NO", "Norway", "Norvège", "النرويج"),
    ("NP", "Nepal", "Népal", "نيبال"),
    ("NR", "Nauru", "Nauru", "ناورو"),
    ("NU", "Niue", "Niue", "نيوي"),
    ("NZ", "New Zealand", "Nouvelle-Zélande", "نيوزيلندا"),
    ("OM", "Oman", "Oman", "عُمان"),
    ("PA", "Panama", "Panama", "بنما"),
    ("PE", "Peru", "Pérou", "بيرو"),
    ("PF", "French Polynesia", "Polynésie française", "بولينيزيا الفرنسية"),
    ("PG", "Papua New Guinea", "Papouasie-Nouvelle-Guinée", "بابوا غينيا الجديدة"),
    ("PH", "Philippines", "Philippines", "الفلبين"),
    ("PK", "Pakistan", "Pakistan", "باكستان"),
    ("PL", "Poland", "Pologne", "بولندا"),
    ("PM", "St. Pierre & Miquelon", "Saint-Pierre-et-Miquelon", "سان بيير ومكويلون"),
    ("PN", "Pitcairn Islands", "Îles Pitcairn", "جزر بيتكيرن"),
    ("PR", "Puerto Rico", "Porto Rico", "بورتوريكو"),
    ("PS", "Palestine", "Palestine", "فلسطين"),
    ("PT", "Portugal", "Portugal", "البرتغال"),
    ("PW", "Palau", "Palaos", "بالاو"),
    ("PY", "Paraguay", "Paraguay", "باراغواي"),
    ("QA", "Qatar", "Qatar", "قطر"),
    ("RE", "Réunion", "La Réunion", "روينيون"),
    ("RO", "Romania", "Roumanie", "رومانيا"),
    ("RS", "Serbia", "Serbie", "صربيا"),
    ("RU", "Russia", "Russie", "روسيا"),
    ("RW", "Rwanda", "Rwanda", "رواندا"),
    ("SA", "Saudi Arabia", "Arabie saoudite", "المملكة العربية السعودية"),
    ("SB", "Solomon Islands", "Îles Salomon", "جزر سليمان"),
    ("SC", "Seychelles", "Seychelles", "سيشل"),
    ("SD", "Sudan", "Soudan", "السودان"),
    ("SE", "Sweden", "Suède", "السويد"),
    ("SG", "Singapore", "Singapour", "سنغافورة"),
    ("SH", "St. Helena", "Sainte-Hélène", "سانت هيلينا"),
    ("SI", "Slovenia", "Slovénie", "سلوفينيا"),
    ("SJ", "Svalbard & Jan Mayen", "Svalbard et Jan Mayen", "سفالبارد وجان ماين"),
    ("SK", "Slovakia", "Slovaquie", "سلوفاكيا"),
    ("SL", "Sierra Leone", "Sierra Leone", "سيراليون"),
    ("SM", "San Marino", "Saint-Marin", "سان مارينو"),
    ("SN", "Senegal", "Sénégal", "السنغال"),
    ("SO", "Somalia", "Somalie", "الصومال"),
    ("SR", "Suriname", "Suriname", "سورينام"),
    ("SS", "South Sudan", "Soudan du Sud", "جنوب السودان"),
    ("ST", "São Tomé & Príncipe", "Sao Tomé-et-Principe", "ساو تومي وبرينسيبي"),
    ("SV", "El Salvador", "Salvador", "السلفادور"),
    ("SX", "Sint Maarten", "Saint-Martin (partie néerlandaise)", "سانت مارتن"),
    ("SY", "Syria", "Syrie", "سوريا"),
    ("SZ", "Eswatini", "Eswatini", "إسواتيني"),
    ("TC", "Turks & Caicos Islands", "Îles Turques-et-Caïques", "جزر توركس وكايكوس"),
    ("TD", "Chad", "Tchad", "تشاد"),
    (
        "TF",
        "French Southern Territories",
        "Terres australes françaises",
        "الأقاليم الجنوبية الفرنسية",
    ),
    ("TG", "Togo", "Togo", "توغو"),
    ("TH", "Thailand", "Thaïlande", "تايلاند"),
    ("TJ", "Tajikistan", "Tadjikistan", "طاجيكستان"),
    ("TK", "Tokelau", "Tokelau", "توكيلاو"),
    ("TL", "Timor-Leste", "Timor oriental", "تيمور - ليشتي"),
    ("TM", "Turkmenistan", "Turkménistan", "تركمانستان"),
    ("TN", "Tunisia", "Tunisie", "تونس"),
    ("TO", "Tonga", "Tonga", "تونغا"),
    ("TR", "Türkiye", "Turquie", "تركيا"),
    ("TT", "Trinidad & Tobago", "Trinité-et-Tobago", "ترينيداد وتوباغو"),
    ("TV", "Tuvalu", "Tuvalu", "توفالو"),
    ("TW", "Taiwan", "Taïwan", "تايوان"),
    ("TZ", "Tanzania", "Tanzanie", "تنزانيا"),
    ("UA", "Ukraine", "Ukraine", "أوكرانيا"),
    ("UG", "Uganda", "Ouganda", "أوغندا"),
    (
        "UM",
        "U.S. Outlying Islands",
        "Îles mineures éloignées des États-Unis",
        "جزر الولايات المتحدة النائية",
    ),
    ("US", "United States", "États-Unis", "الولايات المتحدة"),
    ("UY", "Uruguay", "Uruguay", "أورغواي"),
    ("UZ", "Uzbekistan", "Ouzbékistan", "أوزبكستان"),
    ("VA", "Vatican City", "État de la Cité du Vatican", "الفاتيكان"),
    (
        "VC",
        "St. Vincent & Grenadines",
        "Saint-Vincent-et-les Grenadines",
        "سانت فنسنت وجزر غرينادين",
    ),
    ("VE", "Venezuela", "Venezuela", "فنزويلا"),
    ("VG", "British Virgin Islands", "Îles Vierges britanniques", "جزر فيرجن البريطانية"),
    ("VI", "U.S. Virgin Islands", "Îles Vierges des États-Unis", "جزر فيرجن الأمريكية"),
    ("VN", "Vietnam", "Viêt Nam", "فيتنام"),
    ("VU", "Vanuatu", "Vanuatu", "فانواتو"),
    ("WF", "Wallis & Futuna", "Wallis-et-Futuna", "جزر والس وفوتونا"),
    ("WS", "Samoa", "Samoa", "ساموا"),
    ("YE", "Yemen", "Yémen", "اليمن"),
    ("YT", "Mayotte", "Mayotte", "مايوت"),
    ("ZA", "South Africa", "Afrique du Sud", "جنوب أفريقيا"),
    ("ZM", "Zambia", "Zambie", "زامبيا"),
    ("ZW", "Zimbabwe", "Zimbabwe", "زيمبابوي"),
)
