# Generated by Django 5.2.17 on 2026-09-19 23:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("people", "0002_identityverificationattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_uuid", models.UUIDField(default=uuid.uuid7, editable=False, unique=True)),
                ("occurred_at", models.DateTimeField()),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("PARTICIPANT", "Participant"),
                            ("OPERATIONAL_USER", "Operational user"),
                            ("SYSTEM", "System"),
                            ("DEVICE", "Device"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_code", models.CharField(max_length=100)),
                ("target_type", models.CharField(blank=True, default="", max_length=100)),
                ("target_uuid", models.UUIDField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("DENIED", "Denied"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, default="", max_length=100)),
                ("before_summary", models.JSONField(blank=True, null=True)),
                ("after_summary", models.JSONField(blank=True, null=True)),
                ("correlation_id", models.CharField(max_length=64)),
                ("network_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                (
                    "actor_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="people.person",
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
            ],
            options={
                "db_table": "audit_event",
                "indexes": [
                    models.Index(
                        fields=["event_edition", "occurred_at"], name="aud_event_edition_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_uuid", "occurred_at"],
                        name="aud_event_target_idx",
                    ),
                    models.Index(fields=["actor_user", "occurred_at"], name="aud_event_actor_idx"),
                ],
            },
        ),
        # ADR-0008: local, defence-in-depth append-only protection. The
        # owning local role CAN disable/drop this trigger -- real
        # database-role privilege isolation is a separate, post-migration
        # check (`scripts/check.py audit-isolation`) run with restricted
        # runtime credentials, never claimed by this migration alone.
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION audit_event_block_update_delete()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION
                        'audit_event rows are append-only: % is not permitted', TG_OP;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER audit_event_prevent_update_delete
                BEFORE UPDATE OR DELETE ON audit_event
                FOR EACH ROW EXECUTE FUNCTION audit_event_block_update_delete();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS audit_event_prevent_update_delete ON audit_event;
                DROP FUNCTION IF EXISTS audit_event_block_update_delete();
            """,
        ),
    ]
