# Generated by Django 5.2.17 on 2026-09-21 13:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("documents", "0001_initial"),
        ("events", "0003_eventedition_passport_identity_page_upload_enabled"),
        ("organizations", "0003_professionalaffiliation_biography_and_more"),
        ("people", "0002_identityverificationattempt"),
        ("registrations", "0006_alter_registration_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("IDENTITY", "Identity"),
                            ("DUPLICATE", "Duplicate"),
                            ("RESTRICTED", "Restricted"),
                            ("INFORMATION_RESPONSE", "Information response"),
                        ],
                        max_length=24,
                    ),
                ),
                ("version_label", models.CharField(max_length=32)),
                ("items", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_checklist_definition",
            },
        ),
        migrations.CreateModel(
            name="InformationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("RESPONSE_IN_PROGRESS", "Response in progress"),
                            ("SUBMITTED", "Submitted"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("IDENTITY_CORRECTION", "Identity correction"),
                            ("DOCUMENT_UPLOAD", "Document upload"),
                            ("CLARIFICATION", "Clarification"),
                            ("OTHER", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("message_en", models.CharField(max_length=2000)),
                ("message_fr", models.CharField(blank=True, default="", max_length=2000)),
                ("message_ar", models.CharField(blank=True, default="", max_length=2000)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, default="", max_length=300)),
                ("draft_snapshot_json", models.JSONField(blank=True, default=dict)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="information_requests",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_information_request",
            },
        ),
        migrations.CreateModel(
            name="InformationResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("snapshot_json", models.JSONField()),
                ("snapshot_hash", models.CharField(max_length=64)),
                ("submitted_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                (
                    "information_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="response",
                        to="reviews.informationrequest",
                    ),
                ),
                (
                    "submitted_by_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_information_response",
            },
        ),
        migrations.CreateModel(
            name="RegistrationDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("NOT_APPROVED", "Not approved")],
                        max_length=16,
                    ),
                ),
                ("internal_reason_code", models.CharField(max_length=64)),
                (
                    "internal_note_encrypted",
                    apps.core.fields.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "participant_reason_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("decided_at", models.DateTimeField()),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="registrations.registration",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="reviews.registrationdecision",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_registration_decision",
            },
        ),
        migrations.CreateModel(
            name="RequestItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("FIELD_CORRECTION", "Field correction"),
                            ("DOCUMENT_UPLOAD", "Document upload"),
                            ("CLARIFICATION", "Clarification"),
                        ],
                        max_length=24,
                    ),
                ),
                ("field_code", models.CharField(blank=True, default="", max_length=64)),
                ("document_type", models.CharField(blank=True, default="", max_length=32)),
                ("is_required", models.BooleanField(default=True)),
                ("instructions_en", models.CharField(blank=True, default="", max_length=500)),
                ("instructions_fr", models.CharField(blank=True, default="", max_length=500)),
                ("instructions_ar", models.CharField(blank=True, default="", max_length=500)),
                (
                    "information_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="reviews.informationrequest",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_request_item",
            },
        ),
        migrations.CreateModel(
            name="ResponseItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("value_encrypted", apps.core.fields.EncryptedTextField(blank=True, default="")),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "request_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reviews.requestitem",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="reviews.informationresponse",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_response_item",
            },
        ),
        migrations.CreateModel(
            name="ReviewCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("IDENTITY", "Identity"),
                            ("DUPLICATE", "Duplicate"),
                            ("RESTRICTED", "Restricted"),
                            ("INFORMATION_RESPONSE", "Information response"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "queue_code",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("IDENTITY", "Identity"),
                            ("DUPLICATE", "Duplicate"),
                            ("RESTRICTED", "Restricted"),
                            ("INFORMATION_RESPONSE", "Information response"),
                            ("SPECIALIST", "Specialist"),
                        ],
                        max_length=24,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In progress"),
                            ("WAITING", "Waiting"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_cases",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_review_case",
                "permissions": [
                    ("assign_reviewcase", "Can assign or reassign a review case"),
                    ("change_reviewcase_status", "Can start or change a review case's status"),
                    ("view_duplicatecandidates", "Can view duplicate candidates for a review case"),
                    ("reopen_reviewcase", "Can reopen a closed registration for review"),
                    ("cancel_registration", "Can operationally cancel a registration"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReviewAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="auth.group",
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="reviews.reviewcase",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_review_assignment",
            },
        ),
        migrations.CreateModel(
            name="InternalReviewNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("note_encrypted", apps.core.fields.EncryptedTextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_notes",
                        to="reviews.reviewcase",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_internal_review_note",
            },
        ),
        migrations.AddField(
            model_name="informationrequest",
            name="review_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="information_requests",
                to="reviews.reviewcase",
            ),
        ),
        migrations.CreateModel(
            name="DuplicateCandidateResolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("SAME_PERSON_ANOTHER_CONTEXT", "Same person, another context"),
                            ("ACCIDENTAL_DUPLICATE", "Accidental duplicate"),
                            ("DIFFERENT_PERSON", "Different person"),
                            ("INSUFFICIENT_EVIDENCE", "Insufficient evidence"),
                            ("ESCALATED_RESTRICTED", "Escalated to restricted specialist"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=500)),
                ("reviewed_at", models.DateTimeField()),
                (
                    "candidate_identity_identifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="people.identityidentifier",
                    ),
                ),
                (
                    "candidate_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="people.person",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_resolutions",
                        to="reviews.reviewcase",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_duplicate_candidate_resolution",
            },
        ),
        migrations.CreateModel(
            name="ChecklistResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("item_code", models.CharField(max_length=64)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("NOT_APPLICABLE", "Not applicable"),
                            ("NEEDS_FOLLOW_UP", "Needs follow-up"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=1000)),
                ("recorded_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checklist_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reviews.checklistdefinition",
                    ),
                ),
                (
                    "review_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_results",
                        to="reviews.reviewcase",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_checklist_result",
            },
        ),
        migrations.AddConstraint(
            model_name="checklistdefinition",
            constraint=models.UniqueConstraint(
                fields=("event_edition", "case_type", "version_label"),
                name="rev_checklistdef_event_type_version_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="registrationdecision",
            index=models.Index(fields=["registration", "is_current"], name="rev_decision_reg_idx"),
        ),
        migrations.AddConstraint(
            model_name="registrationdecision",
            constraint=models.UniqueConstraint(
                fields=("registration", "sequence"), name="rev_decision_reg_sequence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationdecision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("registration",),
                name="rev_decision_one_current_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="requestitem",
            index=models.Index(fields=["information_request"], name="rev_reqitem_request_idx"),
        ),
        migrations.AddConstraint(
            model_name="responseitem",
            constraint=models.UniqueConstraint(
                fields=("response", "request_item"), name="rev_respitem_response_item_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewcase",
            index=models.Index(
                fields=["event_edition", "status", "queue_code"], name="rev_case_event_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewcase",
            index=models.Index(fields=["organization", "status"], name="rev_case_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="reviewcase",
            index=models.Index(fields=["registration", "status"], name="rev_case_reg_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="reviewcase",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__gte", 1), ("priority__lte", 100)),
                name="rev_case_priority_bounded",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewassignment",
            index=models.Index(fields=["review_case", "is_current"], name="rev_assign_case_idx"),
        ),
        migrations.AddConstraint(
            model_name="reviewassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("review_case",),
                name="rev_assignment_one_current_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("assigned_group__isnull", True),
                        ("assigned_user__isnull", False),
                    ),
                    models.Q(
                        ("assigned_group__isnull", False),
                        ("assigned_user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="rev_assignment_exactly_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="internalreviewnote",
            index=models.Index(fields=["review_case", "created_at"], name="rev_note_case_idx"),
        ),
        migrations.AddIndex(
            model_name="informationrequest",
            index=models.Index(
                fields=["registration", "status"], name="rev_inforeq_reg_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="informationrequest",
            constraint=models.UniqueConstraint(
                fields=("registration", "sequence"), name="rev_inforeq_reg_sequence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="informationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["DRAFT", "SENT", "RESPONSE_IN_PROGRESS", "SUBMITTED", "OVERDUE"],
                    )
                ),
                fields=("registration",),
                name="rev_inforeq_one_active_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="duplicatecandidateresolution",
            index=models.Index(fields=["review_case"], name="rev_dupres_case_idx"),
        ),
        migrations.AddIndex(
            model_name="checklistresult",
            index=models.Index(
                fields=["review_case", "item_code", "recorded_at"], name="rev_checkresult_case_idx"
            ),
        ),
    ]
