# Generated by Django 5.2.17 on 2026-09-19 23:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("official_name", models.CharField(max_length=300)),
                ("normalized_name", models.CharField(blank=True, default="", max_length=300)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("MINISTRY", "Ministry"),
                            ("PUBLIC_BODY", "Public body"),
                            ("COMPANY", "Company"),
                            ("STARTUP", "Startup"),
                            ("INSTITUTION", "Institution"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("MERGED", "Merged"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "country_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.country",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merged_organizations",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_organization",
            },
        ),
        migrations.CreateModel(
            name="OrganizationAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias_name", models.CharField(max_length=300)),
                ("language", models.CharField(blank=True, default="", max_length=8)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_organization_alias",
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["normalized_name"], name="org_organization_norm_idx"),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=models.Q(("merged_into", models.F("id")), _negated=True),
                name="org_organization_no_self_merge",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationalias",
            index=models.Index(fields=["organization"], name="org_alias_organization_idx"),
        ),
    ]
