# Generated by Django 5.2.17 on 2026-09-19 23:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("organizations", "0001_initial"),
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalAffiliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_organization_name", models.CharField(max_length=300)),
                ("job_title", models.CharField(blank=True, default="", max_length=200)),
                ("department", models.CharField(blank=True, default="", max_length=200)),
                (
                    "country_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.country",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affiliations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_affiliation",
                        to="registrations.registration",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.sector",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_professional_affiliation",
                "indexes": [models.Index(fields=["organization"], name="org_affiliation_org_idx")],
            },
        ),
    ]
