# Generated by Django 5.2.17 on 2026-09-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_professionalaffiliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionalaffiliation",
            name="biography",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="professionalaffiliation",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MINISTRY", "Ministry"),
                    ("PUBLIC_BODY", "Public body"),
                    ("COMPANY", "Company"),
                    ("STARTUP", "Startup"),
                    ("INSTITUTION", "Institution"),
                    ("OTHER", "Other"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="professionalaffiliation",
            name="organization_website",
            field=models.URLField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="professionalaffiliation",
            name="professional_profile_url",
            field=models.URLField(blank=True, default="", max_length=300),
        ),
    ]
