# Generated by Django 5.2.17 on 2026-09-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_professionalaffiliation_biography_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionalaffiliation",
            name="operating_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NATIONAL", "National"),
                    ("REGIONAL", "Regional (several countries)"),
                    ("MULTINATIONAL", "Multinational or global"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("MINISTRY", "Ministry"),
                    ("PUBLIC_BODY", "Public body"),
                    ("COMPANY", "Company"),
                    ("STARTUP", "Startup"),
                    ("INSTITUTION", "Institution"),
                    ("OTHER", "Other"),
                    ("LOCAL_GOV", "Local or regional government"),
                    ("INTL_ORG", "International or intergovernmental organization"),
                    ("DIPLOMATIC", "Embassy or diplomatic mission"),
                    ("SME", "Small or medium enterprise"),
                    ("INCUBATOR", "Incubator, accelerator or technology park"),
                    ("INVESTOR", "Investor (venture capital, angel or fund)"),
                    ("FINANCIAL", "Bank or financial institution"),
                    ("UNIVERSITY", "University or higher education"),
                    ("RESEARCH", "Research centre"),
                    ("NGO", "Non-profit, NGO or association"),
                    ("BUSINESS_ASSOC", "Chamber, federation or professional association"),
                    ("MEDIA", "Media or press"),
                    ("FREELANCE", "Independent or self-employed"),
                    ("STUDENT", "Student (no organization)"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="professionalaffiliation",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MINISTRY", "Ministry"),
                    ("PUBLIC_BODY", "Public body"),
                    ("COMPANY", "Company"),
                    ("STARTUP", "Startup"),
                    ("INSTITUTION", "Institution"),
                    ("OTHER", "Other"),
                    ("LOCAL_GOV", "Local or regional government"),
                    ("INTL_ORG", "International or intergovernmental organization"),
                    ("DIPLOMATIC", "Embassy or diplomatic mission"),
                    ("SME", "Small or medium enterprise"),
                    ("INCUBATOR", "Incubator, accelerator or technology park"),
                    ("INVESTOR", "Investor (venture capital, angel or fund)"),
                    ("FINANCIAL", "Bank or financial institution"),
                    ("UNIVERSITY", "University or higher education"),
                    ("RESEARCH", "Research centre"),
                    ("NGO", "Non-profit, NGO or association"),
                    ("BUSINESS_ASSOC", "Chamber, federation or professional association"),
                    ("MEDIA", "Media or press"),
                    ("FREELANCE", "Independent or self-employed"),
                    ("STUDENT", "Student (no organization)"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
