# Generated by Django 5.2.17 on 2026-09-22 21:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accreditation", "0005_access_checkpoint_rules"),
        ("badges", "0006_badgeissuance_registration_required"),
        ("events", "0004_venue_zone_gate"),
        ("people", "0002_identityverificationattempt"),
        ("registrations", "0006_alter_registration_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("public_id", models.CharField(max_length=22, unique=True)),
                ("public_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_ENROLLMENT", "Pending enrollment"),
                            ("ENROLLED", "Enrolled"),
                            ("SUSPENDED", "Suspended"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING_ENROLLMENT",
                        max_length=24,
                    ),
                ),
                ("device_key_id", models.CharField(blank=True, default="", max_length=16)),
                ("credential_hash", models.CharField(blank=True, default="", max_length=64)),
                ("activation_code_hash", models.CharField(blank=True, default="", max_length=64)),
                ("activation_code_expires_at", models.DateTimeField(blank=True, null=True)),
                ("enrolled_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("app_version", models.CharField(blank=True, default="", max_length=64)),
                ("platform_summary", models.CharField(blank=True, default="", max_length=200)),
                ("data_wipe_requested_at", models.DateTimeField(blank=True, null=True)),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                ("status_reason_code", models.CharField(blank=True, default="", max_length=32)),
                ("status_reason_text", models.CharField(blank=True, default="", max_length=300)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "status_changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "entry_device",
                "permissions": [
                    ("manage_entrydevice", "Can enroll, rescope, suspend, and revoke entry devices")
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("scope_version", models.PositiveIntegerField()),
                ("is_current", models.BooleanField(default=True)),
                ("verification_methods", models.JSONField(default=list)),
                ("offline_capable", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.gate",
                    ),
                ),
                ("permitted_zones", models.ManyToManyField(related_name="+", to="events.zone")),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.venue",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scopes",
                        to="entry.entrydevice",
                    ),
                ),
            ],
            options={
                "db_table": "entry_device_scope",
            },
        ),
        migrations.CreateModel(
            name="EntryDeviceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("end_reason", models.CharField(blank=True, default="", max_length=32)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="entry.entrydevice",
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.gate",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="entry.devicescope",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.zone",
                    ),
                ),
            ],
            options={
                "db_table": "entry_device_session",
            },
        ),
        migrations.CreateModel(
            name="EntryOperatorSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("last_activity_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("end_reason", models.CharField(blank=True, default="", max_length=32)),
                (
                    "device_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operator_sessions",
                        to="entry.entrydevicesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "entry_operator_session",
            },
        ),
        migrations.CreateModel(
            name="EntryOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("operation_id", models.CharField(max_length=64, unique=True)),
                (
                    "original_result",
                    models.CharField(
                        choices=[
                            ("ALLOWED", "Allowed"),
                            ("ALLOWED_WITH_ADVISORY", "Allowed with advisory"),
                            ("MANUAL_REVIEW", "Manual review required"),
                            ("DENIED", "Denied"),
                            ("STALE", "Stale credential or verification"),
                            ("UNSUPPORTED", "Unsupported credential"),
                            ("TECHNICAL_ERROR", "Technical error"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "original_reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No reason"),
                            ("PRIOR_ENTRY", "Previously admitted"),
                            ("RECENT_REENTRY", "Very recent previous admission"),
                            ("INVALID_CREDENTIAL", "Credential not valid"),
                            ("NO_MATCH", "No matching approved registration"),
                            ("UNSUPPORTED_CREDENTIAL", "Credential format not supported"),
                            ("WRONG_EVENT", "Credential belongs to another event"),
                            ("REGISTRATION_NOT_APPROVED", "Registration not approved"),
                            ("SECURITY_RESTRICTION", "Security restriction"),
                            ("RESTRICTION_REVIEW", "Security review required"),
                            ("PASS_REVOKED", "Pass revoked"),
                            ("PASS_REPLACED", "Pass replaced by a newer version"),
                            ("PASS_SUSPENDED", "Pass suspended"),
                            ("PASS_INACTIVE", "Pass not yet activated"),
                            ("PASS_EXPIRED", "Pass validity ended"),
                            ("PASS_NOT_YET_VALID", "Pass validity not started"),
                            ("NO_ACTIVE_PASS", "No active pass"),
                            ("ASSIGNMENT_CHANGED", "Assignment changed since pass issue"),
                            ("NO_ACCESS_ASSIGNMENT", "No current access assignment"),
                            ("OUTSIDE_TIME_WINDOW", "Outside the access time window"),
                            ("WRONG_ZONE", "Not permitted at this checkpoint"),
                            ("ACCESS_RULE_DENY", "Checkpoint closed for this access profile"),
                            ("ALREADY_ADMITTED", "Single-entry access already used"),
                            ("IDENTITY_UNVERIFIED", "Identity reference not verified"),
                            ("VERIFICATION_STALE", "Verification expired; verify again"),
                            ("TECHNICAL_ERROR", "Technical error"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "final_decision",
                    models.CharField(
                        choices=[
                            ("ADMIT", "Admit"),
                            ("DO_NOT_ADMIT", "Do not admit"),
                            ("REDIRECTED", "Redirected"),
                        ],
                        default="ADMIT",
                        max_length=16,
                    ),
                ),
                ("reason_code", models.CharField(max_length=64)),
                ("note_encrypted", apps.core.fields.EncryptedTextField(blank=True, default="")),
                ("occurred_at", models.DateTimeField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="entry.entrydevice",
                    ),
                ),
                (
                    "digital_entry_pass",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="badges.digitalentrypass",
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.gate",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="registrations.registration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.zone",
                    ),
                ),
            ],
            options={
                "db_table": "entry_override",
            },
        ),
        migrations.CreateModel(
            name="EntryEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("operation_id", models.CharField(max_length=64, unique=True)),
                ("command_fingerprint", models.CharField(max_length=64)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("ENTRY", "Entry"), ("EXIT", "Exit")],
                        default="ENTRY",
                        max_length=8,
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("QR", "Digital Entry Pass QR"),
                            ("NIN", "National identity number"),
                            ("PASSPORT", "Passport number"),
                            ("REFERENCE", "Registration reference"),
                            ("MANUAL", "Controlled manual search"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("ALLOWED", "Allowed"),
                            ("ALLOWED_WITH_ADVISORY", "Allowed with advisory"),
                            ("MANUAL_REVIEW", "Manual review required"),
                            ("DENIED", "Denied"),
                            ("STALE", "Stale credential or verification"),
                            ("UNSUPPORTED", "Unsupported credential"),
                            ("TECHNICAL_ERROR", "Technical error"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No reason"),
                            ("PRIOR_ENTRY", "Previously admitted"),
                            ("RECENT_REENTRY", "Very recent previous admission"),
                            ("INVALID_CREDENTIAL", "Credential not valid"),
                            ("NO_MATCH", "No matching approved registration"),
                            ("UNSUPPORTED_CREDENTIAL", "Credential format not supported"),
                            ("WRONG_EVENT", "Credential belongs to another event"),
                            ("REGISTRATION_NOT_APPROVED", "Registration not approved"),
                            ("SECURITY_RESTRICTION", "Security restriction"),
                            ("RESTRICTION_REVIEW", "Security review required"),
                            ("PASS_REVOKED", "Pass revoked"),
                            ("PASS_REPLACED", "Pass replaced by a newer version"),
                            ("PASS_SUSPENDED", "Pass suspended"),
                            ("PASS_INACTIVE", "Pass not yet activated"),
                            ("PASS_EXPIRED", "Pass validity ended"),
                            ("PASS_NOT_YET_VALID", "Pass validity not started"),
                            ("NO_ACTIVE_PASS", "No active pass"),
                            ("ASSIGNMENT_CHANGED", "Assignment changed since pass issue"),
                            ("NO_ACCESS_ASSIGNMENT", "No current access assignment"),
                            ("OUTSIDE_TIME_WINDOW", "Outside the access time window"),
                            ("WRONG_ZONE", "Not permitted at this checkpoint"),
                            ("ACCESS_RULE_DENY", "Checkpoint closed for this access profile"),
                            ("ALREADY_ADMITTED", "Single-entry access already used"),
                            ("IDENTITY_UNVERIFIED", "Identity reference not verified"),
                            ("VERIFICATION_STALE", "Verification expired; verify again"),
                            ("TECHNICAL_ERROR", "Technical error"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("advisory_codes", models.JSONField(blank=True, default=list)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("ADMIT", "Admit"),
                            ("DO_NOT_ADMIT", "Do not admit"),
                            ("REDIRECTED", "Redirected"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "decision_reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FOLLOWS_RESULT", "Follows the verification result"),
                            ("IDENTITY_MISMATCH", "Person does not match the record"),
                            ("SENT_TO_REVIEW_DESK", "Sent to the review desk"),
                            ("SENT_TO_OTHER_CHECKPOINT", "Sent to a permitted checkpoint"),
                            ("PARTICIPANT_LEFT", "Participant left the checkpoint"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField()),
                ("offline", models.BooleanField(default=False)),
                ("package_version", models.BigIntegerField(blank=True, null=True)),
                (
                    "badge_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accreditation.badgetypeassignment",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="entry.entrydevice",
                    ),
                ),
                (
                    "device_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="entry.entrydevicesession",
                    ),
                ),
                (
                    "digital_entry_pass",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="badges.digitalentrypass",
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.gate",
                    ),
                ),
                (
                    "operator_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prior_entry_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="entry.entryevent",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="registrations.registration",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.zone",
                    ),
                ),
                (
                    "operator_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="entry.entryoperatorsession",
                    ),
                ),
                (
                    "override",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entry_event",
                        to="entry.entryoverride",
                    ),
                ),
            ],
            options={
                "db_table": "entry_event",
                "permissions": [
                    (
                        "verify_entry",
                        "Can verify credentials and record entry decisions at a checkpoint",
                    ),
                    (
                        "lookup_identity_reference",
                        "Can look up a participant by NIN or passport number at a checkpoint",
                    ),
                    (
                        "lookup_registration_reference",
                        "Can look up a participant by registration reference at a checkpoint",
                    ),
                    ("manual_search_entry", "Can run the controlled manual search at a checkpoint"),
                    ("override_entry", "Can record a reason-coded supervisor override"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntryOverrideReason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("name_fr", models.CharField(blank=True, default="", max_length=200)),
                ("name_ar", models.CharField(blank=True, default="", max_length=200)),
                ("overridable_reason_codes", models.JSONField(default=list)),
                ("requires_note", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
            ],
            options={
                "db_table": "entry_override_reason",
                "permissions": [
                    ("manage_entryoverridereason", "Can configure the entry override catalogue")
                ],
            },
        ),
        migrations.AddField(
            model_name="entryoverride",
            name="reason",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.entryoverridereason",
            ),
        ),
        migrations.CreateModel(
            name="SecurityRestriction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("DENY_ENTRY", "Deny entry"),
                            ("MANUAL_REVIEW", "Require manual review"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SECURITY_CONCERN", "Security concern"),
                            ("IDENTITY_DISPUTE", "Identity dispute"),
                            ("ACCREDITATION_HOLD", "Accreditation hold"),
                            ("OTHER_APPROVED", "Other approved reason"),
                        ],
                        max_length=24,
                    ),
                ),
                ("is_overrideable", models.BooleanField(default=False)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("reason_encrypted", apps.core.fields.EncryptedTextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("REVOKED", "Revoked")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason_code", models.CharField(blank=True, default="", max_length=32)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="people.person",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="registrations.registration",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "entry_security_restriction",
                "permissions": [
                    ("manage_securityrestriction", "Can create and revoke security restrictions"),
                    (
                        "view_restriction_reason",
                        "Can see the category of a security restriction at a checkpoint",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="entrydevice",
            index=models.Index(
                fields=["event_edition", "status"], name="entry_device_event_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entrydevice",
            constraint=models.UniqueConstraint(
                fields=("public_id",), name="entry_device_public_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="entrydevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("credential_hash", ""), _negated=True),
                fields=("credential_hash",),
                name="entry_device_credential_hash_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="entrydevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("device_key_id", ""), _negated=True),
                fields=("device_key_id",),
                name="entry_device_key_id_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="entrydevice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "ENROLLED"), _negated=True),
                    models.Q(
                        models.Q(("credential_hash", ""), _negated=True),
                        ("enrolled_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="entry_device_enrolled_has_credential",
            ),
        ),
        migrations.AddConstraint(
            model_name="devicescope",
            constraint=models.UniqueConstraint(
                fields=("device", "scope_version"), name="entry_scope_device_version_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="devicescope",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("device",),
                name="entry_scope_one_current_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="devicescope",
            constraint=models.CheckConstraint(
                condition=models.Q(("offline_capable", False)), name="entry_scope_online_only"
            ),
        ),
        migrations.AddConstraint(
            model_name="devicescope",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_version__gte", 1)), name="entry_scope_version_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="entrydevicesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("device",),
                name="entry_devsession_one_open_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="entrydevicesession",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("started_at"))),
                name="entry_devsession_valid_range",
            ),
        ),
        migrations.AddIndex(
            model_name="entryoperatorsession",
            index=models.Index(fields=["user", "ended_at"], name="entry_opsession_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="entryoperatorsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("device_session", "user"),
                name="entry_opsession_one_open_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="entryoperatorsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("started_at"))),
                name="entry_opsession_valid_range",
            ),
        ),
        migrations.AddIndex(
            model_name="entryevent",
            index=models.Index(
                fields=["event_edition", "occurred_at"], name="entry_event_event_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entryevent",
            index=models.Index(fields=["registration", "-occurred_at"], name="entry_event_reg_idx"),
        ),
        migrations.AddIndex(
            model_name="entryevent",
            index=models.Index(fields=["gate", "occurred_at"], name="entry_event_gate_idx"),
        ),
        migrations.AddConstraint(
            model_name="entryevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("decision", "ADMIT"), _negated=True),
                    ("result__in", ["ALLOWED", "ALLOWED_WITH_ADVISORY"]),
                    ("override__isnull", False),
                    _connector="OR",
                ),
                name="entry_event_admit_requires_allowed_or_override",
            ),
        ),
        migrations.AddConstraint(
            model_name="entryevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("offline", False), ("package_version__isnull", True)),
                name="entry_event_online_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="entryevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("result__in", ["UNSUPPORTED", "TECHNICAL_ERROR"]), _negated=True
                ),
                name="entry_event_resolved_result_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="entryoverridereason",
            constraint=models.UniqueConstraint(
                fields=("event_edition", "code"), name="entry_override_reason_code_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="entryoverride",
            index=models.Index(
                fields=["registration", "occurred_at"], name="entry_override_reg_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entryoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(("final_decision", "ADMIT")), name="entry_override_admit_only"
            ),
        ),
        migrations.AddConstraint(
            model_name="entryoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("original_result__in", ["ALLOWED", "ALLOWED_WITH_ADVISORY"]), _negated=True
                ),
                name="entry_override_not_for_allowed",
            ),
        ),
        migrations.AddIndex(
            model_name="securityrestriction",
            index=models.Index(fields=["person", "status"], name="entry_restriction_person_idx"),
        ),
        migrations.AddIndex(
            model_name="securityrestriction",
            index=models.Index(fields=["registration", "status"], name="entry_restriction_reg_idx"),
        ),
        migrations.AddConstraint(
            model_name="securityrestriction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("person__isnull", False), ("registration__isnull", True)),
                    models.Q(("person__isnull", True), ("registration__isnull", False)),
                    _connector="OR",
                ),
                name="entry_restriction_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="securityrestriction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_at__isnull", True),
                    ("ends_at__gt", models.F("starts_at")),
                    _connector="OR",
                ),
                name="entry_restriction_valid_range",
            ),
        ),
        # Entry Events and overrides are append-only evidence in the same
        # enforceable sense as `audit_event` (ADR-0008) and the stock ledger
        # (`badges.0004`): a `BEFORE UPDATE OR DELETE` trigger refuses the
        # statement in the database, so no stray `.update()`, `.delete()`,
        # admin action, or hand-typed SQL can rewrite recorded entry history.
        # Corrections are later, linked records -- never edits (Flow §10.10).
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION entry_block_update_delete()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION
                        '% rows are append-only: % is not permitted',
                        TG_TABLE_NAME, TG_OP;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER entry_event_prevent_update_delete
                BEFORE UPDATE OR DELETE ON entry_event
                FOR EACH ROW EXECUTE FUNCTION entry_block_update_delete();

                CREATE TRIGGER entry_override_prevent_update_delete
                BEFORE UPDATE OR DELETE ON entry_override
                FOR EACH ROW EXECUTE FUNCTION entry_block_update_delete();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS entry_event_prevent_update_delete ON entry_event;
                DROP TRIGGER IF EXISTS entry_override_prevent_update_delete ON entry_override;
                DROP FUNCTION IF EXISTS entry_block_update_delete();
            """,
        ),
    ]
