# Generated by Django 5.2.17 on 2026-09-22 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entry", "0001_initial"),
        ("events", "0004_venue_zone_gate"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationSample",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("occurred_at", models.DateTimeField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("QR", "Digital Entry Pass QR"),
                            ("NIN", "National identity number"),
                            ("PASSPORT", "Passport number"),
                            ("REFERENCE", "Registration reference"),
                            ("MANUAL", "Controlled manual search"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("ALLOWED", "Allowed"),
                            ("ALLOWED_WITH_ADVISORY", "Allowed with advisory"),
                            ("MANUAL_REVIEW", "Manual review required"),
                            ("DENIED", "Denied"),
                            ("STALE", "Stale credential or verification"),
                            ("UNSUPPORTED", "Unsupported credential"),
                            ("TECHNICAL_ERROR", "Technical error"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, default="", max_length=32)),
                ("credential_code", models.CharField(blank=True, default="", max_length=32)),
                ("latency_ms", models.PositiveIntegerField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="entry.entrydevice",
                    ),
                ),
                (
                    "event_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.eventedition",
                    ),
                ),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.gate",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.zone",
                    ),
                ),
            ],
            options={
                "db_table": "entry_verification_sample",
                "permissions": [
                    (
                        "view_entry_observability",
                        "Can view entry verification metrics, device health, and anomaly signals",
                    )
                ],
                "indexes": [
                    models.Index(fields=["gate", "occurred_at"], name="entry_sample_gate_idx"),
                    models.Index(
                        fields=["event_edition", "occurred_at"], name="entry_sample_event_idx"
                    ),
                ],
            },
        ),
    ]
