"""Phase 4 Prompt 2 (ADR-0023): enrolled-device offline PREPARATION.

Additive. The only relaxation is dropping `entry_scope_online_only`: a scope
version may now be offline-capable. `entry_event_online_only` is deliberately
left in place, so no offline admission can be recorded until Phase 4
Prompt 3. The approved Prompt 4 constraint `entry_device_enrolled_has_
credential` is untouched; OFFLINE_READY gets its own twin constraint.

Evidence and immutability triggers (database-enforced, like `entry.0001`):

* `entry_device_wipe_order`, `entry_device_evidence_report`,
  `entry_offline_delta`: append-only (the existing
  `entry_block_update_delete()` function from `entry.0001`);
* `entry_offline_package`: never deleted; content columns immutable
  (`entry_offline_package_guard()`), lifecycle/download bookkeeping mutable;
* `entry_device_key`: never deleted; key material immutable, only
  ACTIVE -> RETIRED;
* `entry_offline_grant`: never deleted; only the revocation columns change.

Reversal: safe while none of the new tables holds a row. Once offline
records exist, reversing is deliberately not supported (the reverse
operations would drop evidence); see ADR-0023 "Migration".
"""

# Generated by Django 5.2.17 on 2026-09-23 21:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.fields

_OFFLINE_TABLES = (
    "entry_offline_event_setting",
    "entry_device_key",
    "entry_offline_package",
    "entry_offline_delta",
    "entry_offline_grant",
    "entry_device_wipe_order",
    "entry_device_evidence_report",
    "entry_offline_nonce",
)


def _refuse_reversal_once_offline_records_exist(apps, schema_editor):
    """Reverse guard (runs FIRST when this migration is unapplied).

    Reversal is safe only while no offline record exists. Afterwards it is
    deliberately unavailable: unapplying would drop device keys, package
    metadata, grants and wipe/evidence records, and would re-impose the
    online-only scope constraint on offline-capable scopes.
    """
    with schema_editor.connection.cursor() as cursor:
        for table in _OFFLINE_TABLES:
            cursor.execute(f"SELECT EXISTS (SELECT 1 FROM {table})")  # noqa: S608 - fixed names
            if cursor.fetchone()[0]:
                raise RuntimeError(
                    f"entry.0003 cannot be reversed: {table} holds offline records "
                    "(reversal is deliberately unavailable once offline records exist)."
                )
        cursor.execute(
            "SELECT EXISTS (SELECT 1 FROM entry_device_scope WHERE offline_capable) "
            "OR EXISTS (SELECT 1 FROM entry_device WHERE status = 'OFFLINE_READY' "
            "OR offline_prepared_at IS NOT NULL)"
        )
        if cursor.fetchone()[0]:
            raise RuntimeError(
                "entry.0003 cannot be reversed: offline-capable scopes or prepared devices exist."
            )


class Migration(migrations.Migration):
    dependencies = [
        ("entry", "0002_verificationsample"),
        ("events", "0004_venue_zone_gate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceEvidenceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pending_operations", models.PositiveIntegerField()),
                ("locked_operations", models.PositiveIntegerField()),
                ("sequence_low", models.BigIntegerField(blank=True, null=True)),
                ("sequence_high", models.BigIntegerField(blank=True, null=True)),
                ("chain_head", models.CharField(blank=True, default="", max_length=64)),
                ("received_at", models.DateTimeField()),
            ],
            options={
                "db_table": "entry_device_evidence_report",
            },
        ),
        migrations.CreateModel(
            name="DeviceWipeOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("public_id", models.CharField(max_length=22, unique=True)),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("DEVICE_LOST", "Device lost"),
                            ("DEVICE_STOLEN", "Device stolen"),
                            ("DEVICE_COMPROMISED", "Device compromised"),
                            ("SECURITY_ORDER", "Security authority order"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note_encrypted", apps.core.fields.EncryptedTextField(blank=True, default="")),
                ("confirmed", models.BooleanField()),
                ("mfa_verified_at", models.DateTimeField()),
                ("signing_key_id", models.CharField(max_length=8)),
                ("known_pending_operations", models.PositiveIntegerField(blank=True, null=True)),
                ("known_locked_operations", models.PositiveIntegerField(blank=True, null=True)),
                ("known_sequence_high", models.BigIntegerField(blank=True, null=True)),
                ("known_chain_head", models.CharField(blank=True, default="", max_length=64)),
                ("known_reported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_evidence_loss",
                    models.CharField(
                        choices=[
                            ("NONE_REPORTED", "No unacknowledged operations reported"),
                            ("OPERATIONS_AT_RISK", "Unacknowledged operations may be destroyed"),
                            ("UNKNOWN", "Unknown: the device never reported its local store"),
                        ],
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "entry_device_wipe_order",
            },
        ),
        migrations.CreateModel(
            name="EntryDeviceKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("SIGN", "Operation signing (ECDSA P-256)"),
                            ("UNWRAP", "Package unwrapping (ECDH P-256)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("key_version", models.PositiveIntegerField()),
                ("public_key_spki", models.TextField()),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RETIRED", "Retired")],
                        default="ACTIVE",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "entry_device_key",
            },
        ),
        migrations.CreateModel(
            name="OfflineCriticalDelta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("delta_version", models.BigIntegerField()),
                ("issued_at", models.DateTimeField()),
                ("critical_delta_cutoff_at", models.DateTimeField()),
                ("manifest_sha256", models.CharField(max_length=64)),
                ("response_sha256", models.CharField(max_length=64)),
                ("counts", models.JSONField(default=dict)),
                ("rebuild_required", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "entry_offline_delta",
            },
        ),
        migrations.CreateModel(
            name="OfflineEventSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("enabled", models.BooleanField(default=False)),
                ("changed_at", models.DateTimeField()),
                ("reason_code", models.CharField(blank=True, default="", max_length=32)),
            ],
            options={
                "db_table": "entry_offline_event_setting",
                "permissions": [
                    (
                        "enable_offline_entry",
                        "Can enable or disable offline continuity for an event",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OfflineOperatorGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("public_id", models.CharField(max_length=22, unique=True)),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[("STANDARD", "Standard"), ("SENSITIVE", "Sensitive")],
                        max_length=16,
                    ),
                ),
                ("may_override", models.BooleanField(default=False)),
                ("signing_key_id", models.CharField(max_length=8)),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.CharField(blank=True, default="", max_length=32)),
            ],
            options={
                "db_table": "entry_offline_grant",
            },
        ),
        migrations.CreateModel(
            name="OfflinePackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("public_id", models.CharField(max_length=22, unique=True)),
                ("package_version", models.BigIntegerField()),
                ("scope_version", models.PositiveIntegerField()),
                ("schema_version", models.PositiveSmallIntegerField()),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[("STANDARD", "Standard"), ("SENSITIVE", "Sensitive")],
                        max_length=16,
                    ),
                ),
                ("signing_key_id", models.CharField(max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("SUPERSEDED", "Superseded"),
                            ("EXPIRED", "Expired"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="READY",
                        max_length=16,
                    ),
                ),
                ("issued_at", models.DateTimeField()),
                ("data_cutoff_at", models.DateTimeField()),
                ("aging_at", models.DateTimeField()),
                ("stale_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("manifest_sha256", models.CharField(max_length=64)),
                ("ciphertext_sha256", models.CharField(max_length=64)),
                ("response_sha256", models.CharField(max_length=64)),
                ("response_bytes", models.PositiveIntegerField()),
                ("entry_count", models.PositiveIntegerField()),
                ("stored_object_key", models.CharField(max_length=64)),
                ("stored_object_deleted_at", models.DateTimeField(blank=True, null=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("first_downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("last_downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("activation_reported_at", models.DateTimeField(blank=True, null=True)),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                ("status_reason_code", models.CharField(blank=True, default="", max_length=32)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "entry_offline_package",
            },
        ),
        migrations.CreateModel(
            name="OfflineRequestNonce",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nonce_digest", models.CharField(max_length=64, unique=True)),
                ("purpose", models.CharField(max_length=24)),
                ("used_at", models.DateTimeField()),
            ],
            options={
                "db_table": "entry_offline_nonce",
            },
        ),
        migrations.AlterModelOptions(
            name="entrydevice",
            options={
                "permissions": [
                    (
                        "manage_entrydevice",
                        "Can enroll, rescope, suspend, and revoke entry devices",
                    ),
                    (
                        "emergency_wipe_device",
                        "Can order a destructive emergency wipe of an entry device local store",
                    ),
                ]
            },
        ),
        migrations.RemoveConstraint(
            model_name="devicescope",
            name="entry_scope_online_only",
        ),
        migrations.AddField(
            model_name="devicescope",
            name="offline_sensitivity",
            field=models.CharField(
                choices=[("STANDARD", "Standard"), ("SENSITIVE", "Sensitive")],
                default="STANDARD",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="entrydevice",
            name="offline_blocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrydevice",
            name="offline_prepared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrydevice",
            name="offline_prepared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entrydevice",
            name="offline_self_test_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrydevice",
            name="reported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrydevice",
            name="reported_chain_head",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="entrydevice",
            name="reported_delta_version",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrydevice",
            name="reported_locked_operations",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrydevice",
            name="reported_package_version",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrydevice",
            name="reported_pending_operations",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrydevice",
            name="reported_sequence_high",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrydevice",
            name="reported_state",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AlterField(
            model_name="entrydevice",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_ENROLLMENT", "Pending enrollment"),
                    ("ENROLLED", "Enrolled"),
                    ("OFFLINE_READY", "Offline ready"),
                    ("SUSPENDED", "Suspended"),
                    ("REVOKED", "Revoked"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING_ENROLLMENT",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="entrydevice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "OFFLINE_READY"), _negated=True),
                    models.Q(
                        models.Q(("credential_hash", ""), _negated=True),
                        ("enrolled_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="entry_device_offline_ready_has_credential",
            ),
        ),
        migrations.AddConstraint(
            model_name="entrydevice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "OFFLINE_READY"), _negated=True),
                    models.Q(
                        ("offline_prepared_at__isnull", False),
                        ("offline_self_test_at__isnull", False),
                        ("offline_blocked_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="entry_device_offline_ready_prepared",
            ),
        ),
        migrations.AddField(
            model_name="deviceevidencereport",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.entrydevice",
            ),
        ),
        migrations.AddField(
            model_name="devicewipeorder",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.entrydevice",
            ),
        ),
        migrations.AddField(
            model_name="devicewipeorder",
            name="event_edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="devicewipeorder",
            name="ordered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deviceevidencereport",
            name="wipe_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.devicewipeorder",
            ),
        ),
        migrations.AddField(
            model_name="entrydevicekey",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entrydevicekey",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offline_keys",
                to="entry.entrydevice",
            ),
        ),
        migrations.AddField(
            model_name="offlinecriticaldelta",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.entrydevice",
            ),
        ),
        migrations.AddField(
            model_name="offlineeventsetting",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="offlineeventsetting",
            name="event_edition",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="offlineoperatorgrant",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.entrydevice",
            ),
        ),
        migrations.AddField(
            model_name="offlineoperatorgrant",
            name="device_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.entrydevicesession",
            ),
        ),
        migrations.AddField(
            model_name="offlineoperatorgrant",
            name="operator_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.entryoperatorsession",
            ),
        ),
        migrations.AddField(
            model_name="offlineoperatorgrant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="offlinepackage",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages",
                to="entry.entrydevice",
            ),
        ),
        migrations.AddField(
            model_name="offlinepackage",
            name="event_edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="offlinepackage",
            name="recipient_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.entrydevicekey",
            ),
        ),
        migrations.AddField(
            model_name="offlinepackage",
            name="scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.devicescope",
            ),
        ),
        migrations.AddField(
            model_name="offlinecriticaldelta",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deltas",
                to="entry.offlinepackage",
            ),
        ),
        migrations.AddField(
            model_name="offlinerequestnonce",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.entrydevice",
            ),
        ),
        migrations.AddConstraint(
            model_name="devicewipeorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("confirmed", True)), name="entry_wipe_order_confirmed"
            ),
        ),
        migrations.AddConstraint(
            model_name="entrydevicekey",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("device", "purpose"),
                name="entry_device_key_one_active_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="entrydevicekey",
            constraint=models.UniqueConstraint(
                fields=("device", "purpose", "key_version"), name="entry_device_key_version_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="entrydevicekey",
            constraint=models.UniqueConstraint(
                fields=("fingerprint",), name="entry_device_key_fp_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="entrydevicekey",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("retired_at__isnull", True), ("status", "ACTIVE")),
                    models.Q(("retired_at__isnull", False), ("status", "RETIRED")),
                    _connector="OR",
                ),
                name="entry_device_key_status_coherent",
            ),
        ),
        migrations.AddIndex(
            model_name="offlineoperatorgrant",
            index=models.Index(fields=["device", "revoked_at"], name="entry_ogrant_device_idx"),
        ),
        migrations.AddIndex(
            model_name="offlineoperatorgrant",
            index=models.Index(fields=["operator_session"], name="entry_ogrant_opsession_idx"),
        ),
        migrations.AddConstraint(
            model_name="offlineoperatorgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("issued_at"))),
                name="entry_ogrant_valid_range",
            ),
        ),
        migrations.AddIndex(
            model_name="offlinepackage",
            index=models.Index(fields=["device", "-package_version"], name="entry_opkg_device_idx"),
        ),
        migrations.AddIndex(
            model_name="offlinepackage",
            index=models.Index(fields=["status", "expires_at"], name="entry_opkg_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="offlinepackage",
            constraint=models.UniqueConstraint(
                fields=("device", "package_version"), name="entry_opkg_device_version_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="offlinepackage",
            constraint=models.CheckConstraint(
                condition=models.Q(("package_version__gte", 1)), name="entry_opkg_version_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="offlinepackage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("aging_at__gt", models.F("data_cutoff_at")),
                    ("stale_at__gte", models.F("aging_at")),
                    ("expires_at__gte", models.F("stale_at")),
                ),
                name="entry_opkg_bands_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="offlinecriticaldelta",
            constraint=models.UniqueConstraint(
                fields=("package", "delta_version"), name="entry_odelta_package_version_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="offlinecriticaldelta",
            constraint=models.CheckConstraint(
                condition=models.Q(("delta_version__gte", 1)), name="entry_odelta_version_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinerequestnonce",
            index=models.Index(fields=["used_at"], name="entry_ononce_used_idx"),
        ),
        # --- Evidence and immutability triggers (see module docstring) ---
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER entry_wipe_order_prevent_update_delete
                BEFORE UPDATE OR DELETE ON entry_device_wipe_order
                FOR EACH ROW EXECUTE FUNCTION entry_block_update_delete();

                CREATE TRIGGER entry_evidence_report_prevent_update_delete
                BEFORE UPDATE OR DELETE ON entry_device_evidence_report
                FOR EACH ROW EXECUTE FUNCTION entry_block_update_delete();

                CREATE TRIGGER entry_offline_delta_prevent_update_delete
                BEFORE UPDATE OR DELETE ON entry_offline_delta
                FOR EACH ROW EXECUTE FUNCTION entry_block_update_delete();

                CREATE FUNCTION entry_offline_package_guard()
                RETURNS trigger AS $$
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        RAISE EXCEPTION 'entry_offline_package rows are never deleted';
                    END IF;
                    IF NEW.public_id IS DISTINCT FROM OLD.public_id
                       OR NEW.device_id IS DISTINCT FROM OLD.device_id
                       OR NEW.scope_id IS DISTINCT FROM OLD.scope_id
                       OR NEW.event_edition_id IS DISTINCT FROM OLD.event_edition_id
                       OR NEW.package_version IS DISTINCT FROM OLD.package_version
                       OR NEW.scope_version IS DISTINCT FROM OLD.scope_version
                       OR NEW.schema_version IS DISTINCT FROM OLD.schema_version
                       OR NEW.sensitivity IS DISTINCT FROM OLD.sensitivity
                       OR NEW.signing_key_id IS DISTINCT FROM OLD.signing_key_id
                       OR NEW.recipient_key_id IS DISTINCT FROM OLD.recipient_key_id
                       OR NEW.issued_at IS DISTINCT FROM OLD.issued_at
                       OR NEW.data_cutoff_at IS DISTINCT FROM OLD.data_cutoff_at
                       OR NEW.aging_at IS DISTINCT FROM OLD.aging_at
                       OR NEW.stale_at IS DISTINCT FROM OLD.stale_at
                       OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
                       OR NEW.manifest_sha256 IS DISTINCT FROM OLD.manifest_sha256
                       OR NEW.ciphertext_sha256 IS DISTINCT FROM OLD.ciphertext_sha256
                       OR NEW.response_sha256 IS DISTINCT FROM OLD.response_sha256
                       OR NEW.response_bytes IS DISTINCT FROM OLD.response_bytes
                       OR NEW.entry_count IS DISTINCT FROM OLD.entry_count
                       OR NEW.stored_object_key IS DISTINCT FROM OLD.stored_object_key
                       OR NEW.created_at IS DISTINCT FROM OLD.created_at
                       OR (OLD.stored_object_deleted_at IS NOT NULL
                           AND NEW.stored_object_deleted_at IS DISTINCT FROM
                               OLD.stored_object_deleted_at)
                       OR (OLD.status <> 'READY' AND NEW.status IS DISTINCT FROM OLD.status)
                    THEN
                        RAISE EXCEPTION 'entry_offline_package content is immutable';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER entry_offline_package_guard
                BEFORE UPDATE OR DELETE ON entry_offline_package
                FOR EACH ROW EXECUTE FUNCTION entry_offline_package_guard();

                CREATE FUNCTION entry_device_key_guard()
                RETURNS trigger AS $$
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        RAISE EXCEPTION 'entry_device_key rows are never deleted';
                    END IF;
                    IF NEW.device_id IS DISTINCT FROM OLD.device_id
                       OR NEW.purpose IS DISTINCT FROM OLD.purpose
                       OR NEW.key_version IS DISTINCT FROM OLD.key_version
                       OR NEW.public_key_spki IS DISTINCT FROM OLD.public_key_spki
                       OR NEW.fingerprint IS DISTINCT FROM OLD.fingerprint
                       OR NEW.created_at IS DISTINCT FROM OLD.created_at
                       OR NEW.created_by_id IS DISTINCT FROM OLD.created_by_id
                       OR (OLD.status = 'RETIRED' AND (
                           NEW.status IS DISTINCT FROM OLD.status
                           OR NEW.retired_at IS DISTINCT FROM OLD.retired_at))
                    THEN
                        RAISE EXCEPTION 'entry_device_key material is immutable';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER entry_device_key_guard
                BEFORE UPDATE OR DELETE ON entry_device_key
                FOR EACH ROW EXECUTE FUNCTION entry_device_key_guard();

                CREATE FUNCTION entry_offline_grant_guard()
                RETURNS trigger AS $$
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        RAISE EXCEPTION 'entry_offline_grant rows are never deleted';
                    END IF;
                    IF NEW.public_id IS DISTINCT FROM OLD.public_id
                       OR NEW.device_id IS DISTINCT FROM OLD.device_id
                       OR NEW.device_session_id IS DISTINCT FROM OLD.device_session_id
                       OR NEW.operator_session_id IS DISTINCT FROM OLD.operator_session_id
                       OR NEW.user_id IS DISTINCT FROM OLD.user_id
                       OR NEW.sensitivity IS DISTINCT FROM OLD.sensitivity
                       OR NEW.may_override IS DISTINCT FROM OLD.may_override
                       OR NEW.signing_key_id IS DISTINCT FROM OLD.signing_key_id
                       OR NEW.issued_at IS DISTINCT FROM OLD.issued_at
                       OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
                       OR (OLD.revoked_at IS NOT NULL AND (
                           NEW.revoked_at IS DISTINCT FROM OLD.revoked_at
                           OR NEW.revoke_reason IS DISTINCT FROM OLD.revoke_reason))
                    THEN
                        RAISE EXCEPTION 'entry_offline_grant is immutable except revocation';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER entry_offline_grant_guard
                BEFORE UPDATE OR DELETE ON entry_offline_grant
                FOR EACH ROW EXECUTE FUNCTION entry_offline_grant_guard();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS entry_offline_grant_guard ON entry_offline_grant;
                DROP FUNCTION IF EXISTS entry_offline_grant_guard();
                DROP TRIGGER IF EXISTS entry_device_key_guard ON entry_device_key;
                DROP FUNCTION IF EXISTS entry_device_key_guard();
                DROP TRIGGER IF EXISTS entry_offline_package_guard ON entry_offline_package;
                DROP FUNCTION IF EXISTS entry_offline_package_guard();
                DROP TRIGGER IF EXISTS entry_offline_delta_prevent_update_delete
                    ON entry_offline_delta;
                DROP TRIGGER IF EXISTS entry_evidence_report_prevent_update_delete
                    ON entry_device_evidence_report;
                DROP TRIGGER IF EXISTS entry_wipe_order_prevent_update_delete
                    ON entry_device_wipe_order;
            """,
        ),
        # Last operation, so its reverse runs first on unapply.
        migrations.RunPython(
            migrations.RunPython.noop, reverse_code=_refuse_reversal_once_offline_records_exist
        ),
    ]
