"""Phase 4 Prompt 3 (ADR-0024): offline operation synchronization and
reconciliation.

Additive, with one deliberate replacement:

* `entry_sync_operation` -- the durable inbox of signed offline operations
  (Schema §11.3): UNIQUE `operation_id`, UNIQUE (device, store, sequence),
  status/processed coherence; the `entry_sync_operation_guard()` trigger
  forbids DELETE, keeps every evidence column immutable from insert, keeps
  the outcome immutable once final, and lets only the duplicate counter grow;
* `entry_reconciliation_case` (Schema §11.7) -- never deleted; identity and
  evidence immutable; OPEN -> CLOSED once (`entry_reconciliation_case_guard()`);
* `entry_reconciliation_case_operation` and `entry_reconciliation_action` --
  append-only (the existing `entry_block_update_delete()` from `entry.0001`);
* `entry_event`: nullable one-to-one `sync_operation`, `offline_conflict`;
  `entry_event_online_only` is REPLACED by `entry_event_offline_coherent`
  (an online event carries no offline evidence; an offline event always
  names its package version and its one sync operation). The existing
  append-only trigger keeps covering every column;
* `entry_override`: `offline`, nullable one-to-one `sync_operation`, and
  `entry_override_offline_coherent`;
* `entry_verification_sample.mode` (ONLINE by default);
* the permission `entry.reconcile_offline_operation`;
* choices only (no SQL): the offline reason codes.

`ADD COLUMN ... DEFAULT` on the append-only tables fires no row trigger and
rewrites no evidence (reviewed with `sqlmigrate`).

Reversal: safe while no synchronization record exists. Once one does -- a
sync operation, a reconciliation case, an offline Entry Event or override,
or an offline telemetry sample -- reversing is deliberately unavailable: it
would drop durable entry evidence and re-impose the online-only rule on
offline Entry Events.
"""

# Generated by Django 5.2.17 on 2026-09-24 21:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.fields

_SYNC_OPERATION_GUARD = """
CREATE FUNCTION entry_sync_operation_guard()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'entry_sync_operation rows are never deleted';
    END IF;
    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.public_id IS DISTINCT FROM OLD.public_id
       OR NEW.operation_id IS DISTINCT FROM OLD.operation_id
       OR NEW.device_id IS DISTINCT FROM OLD.device_id
       OR NEW.event_edition_id IS DISTINCT FROM OLD.event_edition_id
       OR NEW.store_id IS DISTINCT FROM OLD.store_id
       OR NEW.device_sequence IS DISTINCT FROM OLD.device_sequence
       OR NEW.operation_type IS DISTINCT FROM OLD.operation_type
       OR NEW.schema_version IS DISTINCT FROM OLD.schema_version
       OR NEW.payload_json IS DISTINCT FROM OLD.payload_json
       OR NEW.payload_hash IS DISTINCT FROM OLD.payload_hash
       OR NEW.signature IS DISTINCT FROM OLD.signature
       OR NEW.signing_key_id IS DISTINCT FROM OLD.signing_key_id
       OR NEW.prev_hash IS DISTINCT FROM OLD.prev_hash
       OR NEW.chain_hash IS DISTINCT FROM OLD.chain_hash
       OR NEW.note_encrypted IS DISTINCT FROM OLD.note_encrypted
       OR NEW.occurred_at IS DISTINCT FROM OLD.occurred_at
       OR NEW.received_at IS DISTINCT FROM OLD.received_at
       OR NEW.package_id IS DISTINCT FROM OLD.package_id
       OR NEW.package_version IS DISTINCT FROM OLD.package_version
       OR NEW.delta_version IS DISTINCT FROM OLD.delta_version
       OR NEW.grant_id IS DISTINCT FROM OLD.grant_id
       OR NEW.operator_user_id IS DISTINCT FROM OLD.operator_user_id
       OR NEW.gate_id IS DISTINCT FROM OLD.gate_id
       OR NEW.zone_id IS DISTINCT FROM OLD.zone_id
       OR NEW.digital_entry_pass_id IS DISTINCT FROM OLD.digital_entry_pass_id
       OR NEW.registration_id IS DISTINCT FROM OLD.registration_id
       OR NEW.flags IS DISTINCT FROM OLD.flags
       OR NEW.duplicate_submissions < OLD.duplicate_submissions
       OR (OLD.status <> 'PENDING' AND (
           NEW.status IS DISTINCT FROM OLD.status
           OR NEW.outcome_code IS DISTINCT FROM OLD.outcome_code
           OR NEW.conflict_type IS DISTINCT FROM OLD.conflict_type
           OR NEW.server_evaluation IS DISTINCT FROM OLD.server_evaluation
           OR NEW.result_reference IS DISTINCT FROM OLD.result_reference
           OR NEW.processed_at IS DISTINCT FROM OLD.processed_at))
    THEN
        RAISE EXCEPTION 'entry_sync_operation evidence is immutable';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER entry_sync_operation_guard
BEFORE UPDATE OR DELETE ON entry_sync_operation
FOR EACH ROW EXECUTE FUNCTION entry_sync_operation_guard();

CREATE FUNCTION entry_reconciliation_case_guard()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'entry_reconciliation_case rows are never deleted';
    END IF;
    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.public_id IS DISTINCT FROM OLD.public_id
       OR NEW.event_edition_id IS DISTINCT FROM OLD.event_edition_id
       OR NEW.venue_id IS DISTINCT FROM OLD.venue_id
       OR NEW.gate_id IS DISTINCT FROM OLD.gate_id
       OR NEW.device_id IS DISTINCT FROM OLD.device_id
       OR NEW.case_type IS DISTINCT FROM OLD.case_type
       OR NEW.severity IS DISTINCT FROM OLD.severity
       OR NEW.sync_operation_id IS DISTINCT FROM OLD.sync_operation_id
       OR NEW.entry_event_id IS DISTINCT FROM OLD.entry_event_id
       OR NEW.related_entry_event_id IS DISTINCT FROM OLD.related_entry_event_id
       OR NEW.registration_id IS DISTINCT FROM OLD.registration_id
       OR NEW.device_known_state IS DISTINCT FROM OLD.device_known_state
       OR NEW.server_known_state IS DISTINCT FROM OLD.server_known_state
       OR NEW.operational_fact IS DISTINCT FROM OLD.operational_fact
       OR NEW.opened_at IS DISTINCT FROM OLD.opened_at
       OR NEW.version < OLD.version
       OR (OLD.status = 'CLOSED' AND (
           NEW.status IS DISTINCT FROM OLD.status
           OR NEW.closed_at IS DISTINCT FROM OLD.closed_at
           OR NEW.closed_by_id IS DISTINCT FROM OLD.closed_by_id))
    THEN
        RAISE EXCEPTION 'entry_reconciliation_case evidence is immutable; only closure is allowed';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER entry_reconciliation_case_guard
BEFORE UPDATE OR DELETE ON entry_reconciliation_case
FOR EACH ROW EXECUTE FUNCTION entry_reconciliation_case_guard();

CREATE TRIGGER entry_reconciliation_action_prevent_update_delete
BEFORE UPDATE OR DELETE ON entry_reconciliation_action
FOR EACH ROW EXECUTE FUNCTION entry_block_update_delete();

CREATE TRIGGER entry_reconciliation_link_prevent_update_delete
BEFORE UPDATE OR DELETE ON entry_reconciliation_case_operation
FOR EACH ROW EXECUTE FUNCTION entry_block_update_delete();
"""

_DROP_GUARDS = """
DROP TRIGGER IF EXISTS entry_reconciliation_link_prevent_update_delete
    ON entry_reconciliation_case_operation;
DROP TRIGGER IF EXISTS entry_reconciliation_action_prevent_update_delete
    ON entry_reconciliation_action;
DROP TRIGGER IF EXISTS entry_reconciliation_case_guard ON entry_reconciliation_case;
DROP FUNCTION IF EXISTS entry_reconciliation_case_guard();
DROP TRIGGER IF EXISTS entry_sync_operation_guard ON entry_sync_operation;
DROP FUNCTION IF EXISTS entry_sync_operation_guard();
"""


def _refuse_reversal_once_sync_records_exist(apps, schema_editor):
    """Reverse guard (runs FIRST when this migration is unapplied)."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT EXISTS (SELECT 1 FROM entry_sync_operation)"
            " OR EXISTS (SELECT 1 FROM entry_reconciliation_case)"
            " OR EXISTS (SELECT 1 FROM entry_event WHERE offline)"
            " OR EXISTS (SELECT 1 FROM entry_override WHERE offline)"
            " OR EXISTS (SELECT 1 FROM entry_verification_sample WHERE mode = 'OFFLINE')"
        )
        if cursor.fetchone()[0]:
            raise RuntimeError(
                "entry.0005 cannot be reversed: offline synchronization records exist "
                "(reversal is deliberately unavailable once offline records exist; it would "
                "drop durable entry evidence)."
            )


class Migration(migrations.Migration):
    dependencies = [
        ("accreditation", "0005_access_checkpoint_rules"),
        ("badges", "0006_badgeissuance_registration_required"),
        ("entry", "0004_offline_build_lifecycle_and_journal"),
        ("events", "0004_venue_zone_gate"),
        ("registrations", "0007_registration_reg_public_ref_upper_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("NOTE", "Note added"), ("CLOSE", "Case closed")], max_length=8
                    ),
                ),
                ("note_encrypted", apps.core.fields.EncryptedTextField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "entry_reconciliation_action",
            },
        ),
        migrations.CreateModel(
            name="ReconciliationCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("public_id", models.CharField(max_length=22, unique=True)),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("DUPLICATE_ENTRY", "Duplicate entry under a single-entry rule"),
                            (
                                "DUPLICATE_ADMISSION_ADVISORY",
                                "Closely timed admissions on different devices",
                            ),
                            ("PASS_REVOKED", "Pass revoked before the offline admission"),
                            ("PASS_SUSPENDED", "Pass suspended before the offline admission"),
                            ("PASS_REPLACED", "Pass replaced before the offline admission"),
                            ("WRONG_EVENT", "Pass of another event"),
                            ("WRONG_SCOPE", "Device scope changed before the offline admission"),
                            ("PACKAGE_UNUSABLE", "Offline data withdrawn before the admission"),
                            ("PACKAGE_STALE", "Admission on stale offline data"),
                            ("PACKAGE_EXPIRED", "Admission on expired offline data"),
                            ("ACCESS_CHANGED", "Access rule, assignment or registration changed"),
                            ("RESTRICTION_ADDED", "Security restriction found at synchronization"),
                            (
                                "AUTHORIZATION_WITHDRAWN",
                                "Operator authorization withdrawn before the admission",
                            ),
                            (
                                "NON_OVERRIDEABLE_RESTRICTION",
                                "Override despite a non-overrideable restriction",
                            ),
                            ("POLICY_VIOLATION", "Offline policy violated"),
                            (
                                "OPERATION_ID_REUSED",
                                "Operation identifier reused with other content",
                            ),
                            ("UNSUPPORTED_OPERATION", "Unsupported or malformed operation"),
                            ("SECURITY_REJECTION", "Operation failed its security checks"),
                            ("QUARANTINED_DEVICE", "Upload from a suspended or revoked device"),
                            ("SEQUENCE_GAP", "Missing local records (sequence gap)"),
                            ("CHAIN_BREAK", "Local record chain broken"),
                            ("CLOCK_ANOMALY", "Device clock anomaly"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("SECURITY", "Security"),
                            ("CONFLICT", "Conflict"),
                            ("ADVISORY", "Advisory"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=8,
                    ),
                ),
                ("device_known_state", models.JSONField(default=dict)),
                ("server_known_state", models.JSONField(default=dict)),
                ("operational_fact", models.JSONField(default=dict)),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "entry_reconciliation_case",
                "permissions": [
                    (
                        "reconcile_offline_operation",
                        "Can review and close offline synchronization reconciliation cases",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReconciliationCaseOperation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("linked_at", models.DateTimeField()),
            ],
            options={
                "db_table": "entry_reconciliation_case_operation",
            },
        ),
        migrations.CreateModel(
            name="SyncOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("public_id", models.CharField(max_length=22, unique=True)),
                ("operation_id", models.CharField(max_length=36, unique=True)),
                ("store_id", models.CharField(max_length=22)),
                ("device_sequence", models.BigIntegerField()),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("ENTRY_DECISION", "Offline entry decision"),
                            ("VERIFICATION_ATTEMPT", "Offline verification attempt"),
                            ("UNSUPPORTED", "Unsupported operation"),
                        ],
                        max_length=24,
                    ),
                ),
                ("schema_version", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("payload_json", models.JSONField(default=dict)),
                ("payload_hash", models.CharField(max_length=64)),
                ("signature", models.CharField(blank=True, default="", max_length=128)),
                ("prev_hash", models.CharField(blank=True, default="", max_length=64)),
                ("chain_hash", models.CharField(blank=True, default="", max_length=64)),
                ("note_encrypted", apps.core.fields.EncryptedTextField(blank=True, default="")),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField()),
                ("package_version", models.BigIntegerField(blank=True, null=True)),
                ("delta_version", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Received, not processed yet"),
                            ("APPLIED", "Applied"),
                            ("CONFLICT", "Conflict"),
                            ("RECONCILIATION_REQUIRED", "Requires reconciliation"),
                            ("SECURITY_CONFLICT", "Security conflict"),
                            ("REJECTED", "Rejected"),
                            ("QUARANTINED", "Quarantined"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                ("outcome_code", models.CharField(blank=True, default="", max_length=40)),
                ("conflict_type", models.CharField(blank=True, default="", max_length=40)),
                ("server_evaluation", models.JSONField(default=dict)),
                ("flags", models.JSONField(default=list)),
                ("result_reference", models.UUIDField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("duplicate_submissions", models.PositiveIntegerField(default=0)),
                ("last_duplicate_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "entry_sync_operation",
            },
        ),
        migrations.RemoveConstraint(
            model_name="entryevent",
            name="entry_event_online_only",
        ),
        migrations.AddField(
            model_name="entryevent",
            name="offline_conflict",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="entryoverride",
            name="offline",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="verificationsample",
            name="mode",
            field=models.CharField(
                choices=[("ONLINE", "Online"), ("OFFLINE", "Offline")],
                default="ONLINE",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="entryevent",
            name="reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No reason"),
                    ("PRIOR_ENTRY", "Previously admitted"),
                    ("RECENT_REENTRY", "Very recent previous admission"),
                    ("INVALID_CREDENTIAL", "Credential not valid"),
                    ("NO_MATCH", "No matching approved registration"),
                    ("UNSUPPORTED_CREDENTIAL", "Credential format not supported"),
                    ("WRONG_EVENT", "Credential belongs to another event"),
                    ("REGISTRATION_NOT_APPROVED", "Registration not approved"),
                    ("SECURITY_RESTRICTION", "Security restriction"),
                    ("RESTRICTION_REVIEW", "Security review required"),
                    ("PASS_REVOKED", "Pass revoked"),
                    ("PASS_REPLACED", "Pass replaced by a newer version"),
                    ("PASS_SUSPENDED", "Pass suspended"),
                    ("PASS_INACTIVE", "Pass not yet activated"),
                    ("PASS_EXPIRED", "Pass validity ended"),
                    ("PASS_NOT_YET_VALID", "Pass validity not started"),
                    ("NO_ACTIVE_PASS", "No active pass"),
                    ("ASSIGNMENT_CHANGED", "Assignment changed since pass issue"),
                    ("NO_ACCESS_ASSIGNMENT", "No current access assignment"),
                    ("OUTSIDE_TIME_WINDOW", "Outside the access time window"),
                    ("WRONG_ZONE", "Not permitted at this checkpoint"),
                    ("ACCESS_RULE_DENY", "Checkpoint closed for this access profile"),
                    ("ALREADY_ADMITTED", "Single-entry access already used"),
                    ("IDENTITY_UNVERIFIED", "Identity reference not verified"),
                    ("VERIFICATION_STALE", "Verification expired; verify again"),
                    ("TECHNICAL_ERROR", "Technical error"),
                    ("OFFLINE_LOCAL_MISS", "Not in this device's offline data — manual review"),
                    ("OFFLINE_DATA_STALE", "Offline data too old for an admission — manual review"),
                    (
                        "OFFLINE_DATA_CHANGED",
                        "Offline data no longer current for this pass — manual review",
                    ),
                    (
                        "OFFLINE_PACKAGE_EXPIRED",
                        "Offline data expired — follow the manual procedure",
                    ),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="entryoverride",
            name="original_reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No reason"),
                    ("PRIOR_ENTRY", "Previously admitted"),
                    ("RECENT_REENTRY", "Very recent previous admission"),
                    ("INVALID_CREDENTIAL", "Credential not valid"),
                    ("NO_MATCH", "No matching approved registration"),
                    ("UNSUPPORTED_CREDENTIAL", "Credential format not supported"),
                    ("WRONG_EVENT", "Credential belongs to another event"),
                    ("REGISTRATION_NOT_APPROVED", "Registration not approved"),
                    ("SECURITY_RESTRICTION", "Security restriction"),
                    ("RESTRICTION_REVIEW", "Security review required"),
                    ("PASS_REVOKED", "Pass revoked"),
                    ("PASS_REPLACED", "Pass replaced by a newer version"),
                    ("PASS_SUSPENDED", "Pass suspended"),
                    ("PASS_INACTIVE", "Pass not yet activated"),
                    ("PASS_EXPIRED", "Pass validity ended"),
                    ("PASS_NOT_YET_VALID", "Pass validity not started"),
                    ("NO_ACTIVE_PASS", "No active pass"),
                    ("ASSIGNMENT_CHANGED", "Assignment changed since pass issue"),
                    ("NO_ACCESS_ASSIGNMENT", "No current access assignment"),
                    ("OUTSIDE_TIME_WINDOW", "Outside the access time window"),
                    ("WRONG_ZONE", "Not permitted at this checkpoint"),
                    ("ACCESS_RULE_DENY", "Checkpoint closed for this access profile"),
                    ("ALREADY_ADMITTED", "Single-entry access already used"),
                    ("IDENTITY_UNVERIFIED", "Identity reference not verified"),
                    ("VERIFICATION_STALE", "Verification expired; verify again"),
                    ("TECHNICAL_ERROR", "Technical error"),
                    ("OFFLINE_LOCAL_MISS", "Not in this device's offline data — manual review"),
                    ("OFFLINE_DATA_STALE", "Offline data too old for an admission — manual review"),
                    (
                        "OFFLINE_DATA_CHANGED",
                        "Offline data no longer current for this pass — manual review",
                    ),
                    (
                        "OFFLINE_PACKAGE_EXPIRED",
                        "Offline data expired — follow the manual procedure",
                    ),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationaction",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationcase",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationcase",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.entrydevice",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationcase",
            name="entry_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.entryevent",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationcase",
            name="event_edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationcase",
            name="gate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="events.gate"
            ),
        ),
        migrations.AddField(
            model_name="reconciliationcase",
            name="registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="registrations.registration",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationcase",
            name="related_entry_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.entryevent",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationcase",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="events.venue"
            ),
        ),
        migrations.AddField(
            model_name="reconciliationaction",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actions",
                to="entry.reconciliationcase",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationcaseoperation",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="links",
                to="entry.reconciliationcase",
            ),
        ),
        migrations.AddField(
            model_name="syncoperation",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.entrydevice",
            ),
        ),
        migrations.AddField(
            model_name="syncoperation",
            name="digital_entry_pass",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="badges.digitalentrypass",
            ),
        ),
        migrations.AddField(
            model_name="syncoperation",
            name="event_edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="events.eventedition",
            ),
        ),
        migrations.AddField(
            model_name="syncoperation",
            name="gate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="events.gate",
            ),
        ),
        migrations.AddField(
            model_name="syncoperation",
            name="grant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.offlineoperatorgrant",
            ),
        ),
        migrations.AddField(
            model_name="syncoperation",
            name="operator_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="syncoperation",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.offlinepackage",
            ),
        ),
        migrations.AddField(
            model_name="syncoperation",
            name="registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="registrations.registration",
            ),
        ),
        migrations.AddField(
            model_name="syncoperation",
            name="signing_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.entrydevicekey",
            ),
        ),
        migrations.AddField(
            model_name="syncoperation",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="events.zone",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationcaseoperation",
            name="sync_operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.syncoperation",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationcase",
            name="sync_operation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="entry.syncoperation",
            ),
        ),
        migrations.AddField(
            model_name="entryevent",
            name="sync_operation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entry_event",
                to="entry.syncoperation",
            ),
        ),
        migrations.AddField(
            model_name="entryoverride",
            name="sync_operation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entry_override",
                to="entry.syncoperation",
            ),
        ),
        migrations.AddConstraint(
            model_name="entryevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("offline", False),
                        ("package_version__isnull", True),
                        ("sync_operation__isnull", True),
                        ("offline_conflict", False),
                    ),
                    models.Q(
                        ("offline", True),
                        ("package_version__isnull", False),
                        ("sync_operation__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="entry_event_offline_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="entryoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("offline", False), ("sync_operation__isnull", True)),
                    models.Q(("offline", True), ("sync_operation__isnull", False)),
                    _connector="OR",
                ),
                name="entry_override_offline_coherent",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationaction",
            index=models.Index(fields=["case", "created_at"], name="entry_recon_action_case_idx"),
        ),
        migrations.AddIndex(
            model_name="syncoperation",
            index=models.Index(
                fields=["device", "status", "occurred_at"], name="entry_syncop_device_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncoperation",
            index=models.Index(fields=["event_edition", "status"], name="entry_syncop_event_idx"),
        ),
        migrations.AddConstraint(
            model_name="syncoperation",
            constraint=models.UniqueConstraint(
                fields=("device", "store_id", "device_sequence"),
                name="entry_syncop_store_sequence_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(("device_sequence__gte", 1)),
                name="entry_syncop_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "PENDING"), ("processed_at__isnull", True)),
                    models.Q(
                        models.Q(("status", "PENDING"), _negated=True),
                        ("processed_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="entry_syncop_processed_iff_final",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "operation_type__in",
                        ["ENTRY_DECISION", "VERIFICATION_ATTEMPT", "UNSUPPORTED"],
                    )
                ),
                name="entry_syncop_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "PENDING",
                            "APPLIED",
                            "CONFLICT",
                            "RECONCILIATION_REQUIRED",
                            "SECURITY_CONFLICT",
                            "REJECTED",
                            "QUARANTINED",
                        ],
                    )
                ),
                name="entry_syncop_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliationcaseoperation",
            constraint=models.UniqueConstraint(
                fields=("case", "sync_operation"), name="entry_recon_case_operation_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationcase",
            index=models.Index(
                fields=["event_edition", "status", "opened_at"], name="entry_recon_event_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationcase",
            index=models.Index(fields=["gate", "status"], name="entry_recon_gate_idx"),
        ),
        migrations.AddConstraint(
            model_name="reconciliationcase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "OPEN"), ("closed_at__isnull", True), ("closed_by__isnull", True)
                    ),
                    models.Q(
                        ("status", "CLOSED"),
                        ("closed_at__isnull", False),
                        ("closed_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="entry_recon_closed_coherent",
            ),
        ),
        migrations.RunSQL(sql=_SYNC_OPERATION_GUARD, reverse_sql=_DROP_GUARDS),
        # Last operation, so its reverse runs first on unapply.
        migrations.RunPython(
            migrations.RunPython.noop, reverse_code=_refuse_reversal_once_sync_records_exist
        ),
    ]
