# Generated by Django 5.2.17 on 2026-10-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entry", "0005_offline_sync_and_reconciliation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entryevent",
            name="reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No reason"),
                    ("PRIOR_ENTRY", "Previously admitted"),
                    ("RECENT_REENTRY", "Very recent previous admission"),
                    ("INVALID_CREDENTIAL", "Credential not valid"),
                    ("NO_MATCH", "No matching approved registration"),
                    ("UNSUPPORTED_CREDENTIAL", "Credential format not supported"),
                    ("WRONG_EVENT", "Credential belongs to another event"),
                    ("REGISTRATION_NOT_APPROVED", "Registration not approved"),
                    ("SECURITY_RESTRICTION", "Security restriction"),
                    ("RESTRICTION_REVIEW", "Security review required"),
                    ("PASS_REVOKED", "Pass revoked"),
                    ("PASS_REPLACED", "Pass replaced by a newer version"),
                    ("PASS_SUSPENDED", "Pass suspended"),
                    ("PASS_INACTIVE", "Pass not yet activated"),
                    ("PASS_EXPIRED", "Pass validity ended"),
                    ("PASS_NOT_YET_VALID", "Pass validity not started"),
                    ("NO_ACTIVE_PASS", "No active pass"),
                    ("ASSIGNMENT_CHANGED", "Assignment changed since pass issue"),
                    ("NO_ACCESS_ASSIGNMENT", "No current access assignment"),
                    ("OUTSIDE_TIME_WINDOW", "Outside the access time window"),
                    ("WRONG_ZONE", "Not permitted at this checkpoint"),
                    ("ACCESS_RULE_DENY", "Checkpoint closed for this access profile"),
                    ("ALREADY_ADMITTED", "Single-entry access already used"),
                    ("IDENTITY_UNVERIFIED", "Identity reference not verified"),
                    (
                        "ATTENDANCE_DAY_NOT_AUTHORIZED",
                        "Approval does not include today (opening day not authorized)",
                    ),
                    ("ATTENDANCE_UNCLASSIFIED", "Attendance days not yet classified"),
                    ("ATTENDANCE_NOT_CONFERENCE_DAY", "Today is not a conference day"),
                    ("VERIFICATION_STALE", "Verification expired; verify again"),
                    ("TECHNICAL_ERROR", "Technical error"),
                    ("OFFLINE_LOCAL_MISS", "Not in this device's offline data — manual review"),
                    ("OFFLINE_DATA_STALE", "Offline data too old for an admission — manual review"),
                    (
                        "OFFLINE_DATA_CHANGED",
                        "Offline data no longer current for this pass — manual review",
                    ),
                    (
                        "OFFLINE_PACKAGE_EXPIRED",
                        "Offline data expired — follow the manual procedure",
                    ),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="entryoverride",
            name="original_reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No reason"),
                    ("PRIOR_ENTRY", "Previously admitted"),
                    ("RECENT_REENTRY", "Very recent previous admission"),
                    ("INVALID_CREDENTIAL", "Credential not valid"),
                    ("NO_MATCH", "No matching approved registration"),
                    ("UNSUPPORTED_CREDENTIAL", "Credential format not supported"),
                    ("WRONG_EVENT", "Credential belongs to another event"),
                    ("REGISTRATION_NOT_APPROVED", "Registration not approved"),
                    ("SECURITY_RESTRICTION", "Security restriction"),
                    ("RESTRICTION_REVIEW", "Security review required"),
                    ("PASS_REVOKED", "Pass revoked"),
                    ("PASS_REPLACED", "Pass replaced by a newer version"),
                    ("PASS_SUSPENDED", "Pass suspended"),
                    ("PASS_INACTIVE", "Pass not yet activated"),
                    ("PASS_EXPIRED", "Pass validity ended"),
                    ("PASS_NOT_YET_VALID", "Pass validity not started"),
                    ("NO_ACTIVE_PASS", "No active pass"),
                    ("ASSIGNMENT_CHANGED", "Assignment changed since pass issue"),
                    ("NO_ACCESS_ASSIGNMENT", "No current access assignment"),
                    ("OUTSIDE_TIME_WINDOW", "Outside the access time window"),
                    ("WRONG_ZONE", "Not permitted at this checkpoint"),
                    ("ACCESS_RULE_DENY", "Checkpoint closed for this access profile"),
                    ("ALREADY_ADMITTED", "Single-entry access already used"),
                    ("IDENTITY_UNVERIFIED", "Identity reference not verified"),
                    (
                        "ATTENDANCE_DAY_NOT_AUTHORIZED",
                        "Approval does not include today (opening day not authorized)",
                    ),
                    ("ATTENDANCE_UNCLASSIFIED", "Attendance days not yet classified"),
                    ("ATTENDANCE_NOT_CONFERENCE_DAY", "Today is not a conference day"),
                    ("VERIFICATION_STALE", "Verification expired; verify again"),
                    ("TECHNICAL_ERROR", "Technical error"),
                    ("OFFLINE_LOCAL_MISS", "Not in this device's offline data — manual review"),
                    ("OFFLINE_DATA_STALE", "Offline data too old for an admission — manual review"),
                    (
                        "OFFLINE_DATA_CHANGED",
                        "Offline data no longer current for this pass — manual review",
                    ),
                    (
                        "OFFLINE_PACKAGE_EXPIRED",
                        "Offline data expired — follow the manual procedure",
                    ),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
